plotData = {'epsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                 'assignbordertime': [0.00417304,
                                                      0.00436282,
                                                      0.00440383,
                                                      0.00146008],
                                 'assigngridtime': [0.157513,
                                                    0.157231,
                                                    0.159533,
                                                    0.162444],
                                 'buildcoreptquadtree': [-1, -1, -1, -1],
                                 'buildgetnbrkdt': [0.0018239,
                                                    0.00131702,
                                                    0.000339985,
                                                    0.000393152],
                                 'clustercoretime': [0.359436,
                                                     0.495848,
                                                     57.0222,
                                                     0.775919],
                                 'config-id': '07-07-real2',
                                 'configuration': 'nd-approx/nd-exactbcp/nd-exactquadtree/nd-exactbcpbucketing: '
                                                  'after the kdtree scanleft '
                                                  'change, to obtain a new '
                                                  'result for household '
                                                  'dataset; jemalloc for all, '
                                                  'bucketing only for '
                                                  'nd-exactquadtree, array kdt '
                                                  'for all, array quadtree for '
                                                  'any config that involve a '
                                                  'quadtree, long variable '
                                                  'type for any config that '
                                                  'involve a quadtree, double '
                                                  'datatype, commit: ',
                                 'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                 'dataset': '3D_GeoLife_24M.pbbs',
                                 'dim': {3.0},
                                 'dimname': '3D_GeoLife_',
                                 'eps': {40.0, 80.0, 20.0, 160.0},
                                 'machine': 'aws-c5.18x',
                                 'markcoretime': [0.0625401,
                                                  0.022002,
                                                  0.100332,
                                                  0.00916505],
                                 'minpts': {100.0},
                                 'ndalgo': {'nd'},
                                 'numborder': [7391.0, 3791.0, 3572.0, 990.0],
                                 'numclusterpts': [24846295.0,
                                                   24859769.0,
                                                   24868067.0,
                                                   24873703.0],
                                 'numclusters': [91.0, 63.0, 56.0, 24.0],
                                 'numcore': [24838633.0,
                                             24855827.0,
                                             24864335.0,
                                             24872696.0],
                                 'numgrids': [22919.0, 9684.0, 3612.0, 1694.0],
                                 'numnoise': [30954.0, 17360.0, 9071.0, 3292.0],
                                 'numprocs': {72.0},
                                 'numpts': [24876978.0,
                                            24876978.0,
                                            24876978.0,
                                            24876978.0],
                                 'numpts_attr': {24876978.0},
                                 'rho': {0.01},
                                 'rounds': {3.0},
                                 'serialalgo': {'parallel'},
                                 'testcount': 4,
                                 'totaltime': [0.585836,
                                               0.6811,
                                               57.2869,
                                               0.949609],
                                 'variable': 'eps',
                                 'x': [20.0, 40.0, 80.0, 160.0]},
              '7D_HouseHold_2M': {'algo': {'exact'},
                                  'assignbordertime': [0.140824,
                                                       0.0839961,
                                                       0.141136,
                                                       0.221174,
                                                       0.212827,
                                                       0.209265],
                                  'assigngridtime': [0.037302,
                                                     0.0290079,
                                                     0.0384841,
                                                     0.0262852,
                                                     0.0322099,
                                                     0.0318971],
                                  'buildcoreptquadtree': [-1,
                                                          -1,
                                                          -1,
                                                          -1,
                                                          -1,
                                                          -1],
                                  'buildgetnbrkdt': [0.102026,
                                                     0.0608652,
                                                     0.0361869,
                                                     0.0274138,
                                                     0.0306461,
                                                     0.0198061],
                                  'clustercoretime': [0.251842,
                                                      0.154461,
                                                      0.1882,
                                                      1.11027,
                                                      1.69418,
                                                      3.60623],
                                  'config-id': '07-07-real2',
                                  'configuration': 'nd-approx/nd-exactbcp/nd-exactquadtree/nd-exactbcpbucketing: '
                                                   'after the kdtree scanleft '
                                                   'change, to obtain a new '
                                                   'result for household '
                                                   'dataset; jemalloc for all, '
                                                   'bucketing only for '
                                                   'nd-exactquadtree, array '
                                                   'kdt for all, array '
                                                   'quadtree for any config '
                                                   'that involve a quadtree, '
                                                   'long variable type for any '
                                                   'config that involve a '
                                                   'quadtree, double datatype, '
                                                   'commit: ',
                                  'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                  'dataset': '7D_HouseHold_2M.pbbs',
                                  'dim': {7.0},
                                  'dimname': '7D_HouseHold_',
                                  'eps': {1000.0,
                                          1400.0,
                                          1800.0,
                                          2200.0,
                                          2600.0,
                                          3000.0},
                                  'machine': 'aws-c5.18x',
                                  'markcoretime': [1.92376,
                                                   2.20317,
                                                   3.2586,
                                                   7.51119,
                                                   7.93579,
                                                   8.62419],
                                  'minpts': {100.0},
                                  'ndalgo': {'nd'},
                                  'numborder': [123077.0,
                                                148926.0,
                                                121447.0,
                                                97189.0,
                                                76854.0,
                                                64485.0],
                                  'numclusterpts': [1220205.0,
                                                    1507976.0,
                                                    1668837.0,
                                                    1760132.0,
                                                    1815454.0,
                                                    1855854.0],
                                  'numclusters': [55.0,
                                                  30.0,
                                                  27.0,
                                                  30.0,
                                                  38.0,
                                                  48.0],
                                  'numcore': [1096868.0,
                                              1358900.0,
                                              1547291.0,
                                              1662856.0,
                                              1738555.0,
                                              1791293.0],
                                  'numgrids': [987740.0,
                                               796144.0,
                                               664053.0,
                                               570752.0,
                                               498785.0,
                                               442979.0],
                                  'numnoise': [829335.0,
                                               541454.0,
                                               380542.0,
                                               289235.0,
                                               233871.0,
                                               193502.0],
                                  'numprocs': {72.0},
                                  'numpts': [2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0],
                                  'numpts_attr': {2049280.0},
                                  'rho': {0.01},
                                  'rounds': {3.0},
                                  'serialalgo': {'parallel'},
                                  'testcount': 6,
                                  'totaltime': [2.46787,
                                                2.54414,
                                                3.69447,
                                                8.97353,
                                                9.92852,
                                                12.5115],
                                  'variable': 'eps',
                                  'x': [1000.0,
                                        1400.0,
                                        1800.0,
                                        2200.0,
                                        2600.0,
                                        3000.0]}},
 'minptsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                    'assignbordertime': [0.004246,
                                                         0.00436282,
                                                         0.00414896,
                                                         0.00915504,
                                                         0.105345,
                                                         0.191822],
                                    'assigngridtime': [0.164145,
                                                       0.157231,
                                                       0.156637,
                                                       0.19933,
                                                       0.167979,
                                                       0.159552],
                                    'buildcoreptquadtree': [-1,
                                                            -1,
                                                            -1,
                                                            -1,
                                                            -1,
                                                            -1],
                                    'buildgetnbrkdt': [0.00132394,
                                                       0.00131702,
                                                       0.00120997,
                                                       0.00124788,
                                                       0.00126505,
                                                       0.00122905],
                                    'clustercoretime': [0.510918,
                                                        0.495848,
                                                        0.502217,
                                                        0.513611,
                                                        0.468001,
                                                        0.53481],
                                    'config-id': '07-07-real2',
                                    'configuration': 'nd-approx/nd-exactbcp/nd-exactquadtree/nd-exactbcpbucketing: '
                                                     'after the kdtree '
                                                     'scanleft change, to '
                                                     'obtain a new result for '
                                                     'household dataset; '
                                                     'jemalloc for all, '
                                                     'bucketing only for '
                                                     'nd-exactquadtree, array '
                                                     'kdt for all, array '
                                                     'quadtree for any config '
                                                     'that involve a quadtree, '
                                                     'long variable type for '
                                                     'any config that involve '
                                                     'a quadtree, double '
                                                     'datatype, commit: ',
                                    'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                    'dataset': '3D_GeoLife_24M.pbbs',
                                    'dim': {3.0},
                                    'dimname': '3D_GeoLife_',
                                    'eps': {40.0},
                                    'machine': 'aws-c5.18x',
                                    'markcoretime': [0.0151899,
                                                     0.022002,
                                                     0.052489,
                                                     0.127727,
                                                     0.902303,
                                                     2.37963],
                                    'minpts': {10.0,
                                               100.0,
                                               500.0,
                                               1000.0,
                                               5000.0,
                                               10000.0},
                                    'ndalgo': {'nd'},
                                    'numborder': [320.0,
                                                  3791.0,
                                                  8860.0,
                                                  17546.0,
                                                  100090.0,
                                                  91985.0],
                                    'numclusterpts': [24875629.0,
                                                      24859769.0,
                                                      24824591.0,
                                                      24795161.0,
                                                      24501634.0,
                                                      24141423.0],
                                    'numclusters': [84.0,
                                                    63.0,
                                                    26.0,
                                                    21.0,
                                                    19.0,
                                                    8.0],
                                    'numcore': [24875293.0,
                                                24855827.0,
                                                24815481.0,
                                                24776376.0,
                                                24400085.0,
                                                24049438.0],
                                    'numgrids': [9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0],
                                    'numnoise': [1365.0,
                                                 17360.0,
                                                 52637.0,
                                                 83056.0,
                                                 376803.0,
                                                 735555.0],
                                    'numprocs': {72.0},
                                    'numpts': [24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0],
                                    'numpts_attr': {24876978.0},
                                    'rho': {0.01},
                                    'rounds': {3.0},
                                    'serialalgo': {'parallel'},
                                    'testcount': 6,
                                    'totaltime': [0.696025,
                                                  0.6811,
                                                  0.717001,
                                                  0.851408,
                                                  1.64526,
                                                  3.26737],
                                    'variable': 'minpts',
                                    'x': [10.0,
                                          100.0,
                                          500.0,
                                          1000.0,
                                          5000.0,
                                          10000.0]},
                 '7D_HouseHold_2M': {'algo': {'exact'},
                                     'assignbordertime': [0.0192318,
                                                          0.135343,
                                                          0.452303,
                                                          0.799005,
                                                          2.44118,
                                                          2.09956],
                                     'assigngridtime': [0.0288241,
                                                        0.0295651,
                                                        0.0298889,
                                                        0.03774,
                                                        0.0260851,
                                                        0.028908],
                                     'buildcoreptquadtree': [-1,
                                                             -1,
                                                             -1,
                                                             -1,
                                                             -1,
                                                             -1],
                                     'buildgetnbrkdt': [0.0350039,
                                                        0.0331481,
                                                        0.033303,
                                                        0.0338159,
                                                        0.032028,
                                                        0.0333202],
                                     'clustercoretime': [0.367379,
                                                         0.192706,
                                                         0.09132,
                                                         0.0571051,
                                                         0.0108569,
                                                         0.00545001],
                                     'config-id': '07-07-real2',
                                     'configuration': 'nd-approx/nd-exactbcp/nd-exactquadtree/nd-exactbcpbucketing: '
                                                      'after the kdtree '
                                                      'scanleft change, to '
                                                      'obtain a new result for '
                                                      'household dataset; '
                                                      'jemalloc for all, '
                                                      'bucketing only for '
                                                      'nd-exactquadtree, array '
                                                      'kdt for all, array '
                                                      'quadtree for any config '
                                                      'that involve a '
                                                      'quadtree, long variable '
                                                      'type for any config '
                                                      'that involve a '
                                                      'quadtree, double '
                                                      'datatype, commit: ',
                                     'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                     'dataset': '7D_HouseHold_2M.pbbs',
                                     'dim': {7.0},
                                     'dimname': '7D_HouseHold_',
                                     'eps': {2000.0},
                                     'machine': 'aws-c5.18x',
                                     'markcoretime': [2.05322,
                                                      3.41208,
                                                      5.05918,
                                                      6.16452,
                                                      12.439,
                                                      14.6235],
                                     'minpts': {10.0,
                                                100.0,
                                                500.0,
                                                1000.0,
                                                5000.0,
                                                10000.0},
                                     'ndalgo': {'nd'},
                                     'numborder': [42452.0,
                                                   108607.0,
                                                   174591.0,
                                                   209145.0,
                                                   318927.0,
                                                   233083.0],
                                     'numclusterpts': [1910253.0,
                                                       1721856.0,
                                                       1462453.0,
                                                       1319491.0,
                                                       874953.0,
                                                       514766.0],
                                     'numclusters': [599.0,
                                                     27.0,
                                                     13.0,
                                                     13.0,
                                                     8.0,
                                                     4.0],
                                     'numcore': [1867325.0,
                                                 1613187.0,
                                                 1287762.0,
                                                 1109405.0,
                                                 555715.0,
                                                 281683.0],
                                     'numgrids': [613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0],
                                     'numnoise': [139503.0,
                                                  327486.0,
                                                  586927.0,
                                                  730730.0,
                                                  1174638.0,
                                                  1534514.0],
                                     'numprocs': {72.0},
                                     'numpts': [2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0],
                                     'numpts_attr': {2049280.0},
                                     'rho': {0.01},
                                     'rounds': {3.0},
                                     'serialalgo': {'parallel'},
                                     'testcount': 6,
                                     'totaltime': [2.51817,
                                                   3.8327,
                                                   5.69215,
                                                   7.14015,
                                                   15.0019,
                                                   16.8822],
                                     'variable': 'minpts',
                                     'x': [10.0,
                                           100.0,
                                           500.0,
                                           1000.0,
                                           5000.0,
                                           10000.0]}},
 'numprocsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                      'assignbordertime': [0.00995016,
                                                           0.00493407,
                                                           0.00309396,
                                                           0.00309515,
                                                           0.00282001,
                                                           0.00246501,
                                                           0.00436282],
                                      'assigngridtime': [1.69679,
                                                         0.521578,
                                                         0.304763,
                                                         0.193846,
                                                         0.165254,
                                                         0.147738,
                                                         0.157231],
                                      'buildcoreptquadtree': [-1,
                                                              -1,
                                                              -1,
                                                              -1,
                                                              -1,
                                                              -1,
                                                              -1],
                                      'buildgetnbrkdt': [0.000612974,
                                                         0.000757933,
                                                         0.000710011,
                                                         0.000766993,
                                                         0.000750065,
                                                         0.000849009,
                                                         0.00131702],
                                      'clustercoretime': [1.21048,
                                                          0.800713,
                                                          0.472489,
                                                          0.371823,
                                                          0.314502,
                                                          0.33286,
                                                          0.495848],
                                      'config-id': '07-07-real2',
                                      'configuration': 'nd-approx/nd-exactbcp/nd-exactquadtree/nd-exactbcpbucketing: '
                                                       'after the kdtree '
                                                       'scanleft change, to '
                                                       'obtain a new result '
                                                       'for household dataset; '
                                                       'jemalloc for all, '
                                                       'bucketing only for '
                                                       'nd-exactquadtree, '
                                                       'array kdt for all, '
                                                       'array quadtree for any '
                                                       'config that involve a '
                                                       'quadtree, long '
                                                       'variable type for any '
                                                       'config that involve a '
                                                       'quadtree, double '
                                                       'datatype, commit: ',
                                      'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                      'dataset': '3D_GeoLife_24M.pbbs',
                                      'dim': {3.0},
                                      'dimname': '3D_GeoLife_',
                                      'eps': {40.0},
                                      'machine': 'aws-c5.18x',
                                      'markcoretime': [0.625459,
                                                       0.163421,
                                                       0.0856948,
                                                       0.0440831,
                                                       0.031723,
                                                       0.0224221,
                                                       0.022002],
                                      'minpts': {100.0},
                                      'ndalgo': {'nd'},
                                      'numborder': [3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0],
                                      'numclusterpts': [24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0],
                                      'numclusters': [63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0],
                                      'numcore': [24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0],
                                      'numgrids': [9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0],
                                      'numnoise': [17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0],
                                      'numprocs': {1.0,
                                                   4.0,
                                                   8.0,
                                                   16.0,
                                                   24.0,
                                                   36.0,
                                                   72.0},
                                      'numpts': [24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0],
                                      'numpts_attr': {24876978.0},
                                      'rho': {0.01},
                                      'rounds': {3.0},
                                      'serialalgo': {'parallel'},
                                      'testcount': 7,
                                      'totaltime': [3.54366,
                                                    1.49192,
                                                    0.867326,
                                                    0.614085,
                                                    0.515257,
                                                    0.506504,
                                                    0.6811],
                                      'variable': 'numprocs',
                                      'x': [1.0,
                                            4.0,
                                            8.0,
                                            16.0,
                                            24.0,
                                            36.0,
                                            72.0]},
                   '7D_HouseHold_2M': {'algo': {'exact'},
                                       'assignbordertime': [3.26238,
                                                            0.904425,
                                                            0.479283,
                                                            0.270927,
                                                            0.184225,
                                                            0.132679,
                                                            0.135343],
                                       'assigngridtime': [0.713356,
                                                          0.212062,
                                                          0.121268,
                                                          0.064431,
                                                          0.046113,
                                                          0.0385439,
                                                          0.0295651],
                                       'buildcoreptquadtree': [-1,
                                                               -1,
                                                               -1,
                                                               -1,
                                                               -1,
                                                               -1,
                                                               -1],
                                       'buildgetnbrkdt': [0.570249,
                                                          0.150117,
                                                          0.0969059,
                                                          0.0541401,
                                                          0.0424151,
                                                          0.0335021,
                                                          0.0331481],
                                       'clustercoretime': [9.04162,
                                                           1.58549,
                                                           0.712519,
                                                           0.364253,
                                                           0.296852,
                                                           0.200466,
                                                           0.192706],
                                       'config-id': '07-07-real2',
                                       'configuration': 'nd-approx/nd-exactbcp/nd-exactquadtree/nd-exactbcpbucketing: '
                                                        'after the kdtree '
                                                        'scanleft change, to '
                                                        'obtain a new result '
                                                        'for household '
                                                        'dataset; jemalloc for '
                                                        'all, bucketing only '
                                                        'for nd-exactquadtree, '
                                                        'array kdt for all, '
                                                        'array quadtree for '
                                                        'any config that '
                                                        'involve a quadtree, '
                                                        'long variable type '
                                                        'for any config that '
                                                        'involve a quadtree, '
                                                        'double datatype, '
                                                        'commit: ',
                                       'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                       'dataset': '7D_HouseHold_2M.pbbs',
                                       'dim': {7.0},
                                       'dimname': '7D_HouseHold_',
                                       'eps': {2000.0},
                                       'machine': 'aws-c5.18x',
                                       'markcoretime': [96.0809,
                                                        24.5732,
                                                        12.5226,
                                                        6.63143,
                                                        4.75128,
                                                        3.50813,
                                                        3.41208],
                                       'minpts': {100.0},
                                       'ndalgo': {'nd'},
                                       'numborder': [108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0],
                                       'numclusterpts': [1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0],
                                       'numclusters': [27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0],
                                       'numcore': [1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0],
                                       'numgrids': [613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0],
                                       'numnoise': [327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0],
                                       'numprocs': {1.0,
                                                    4.0,
                                                    8.0,
                                                    16.0,
                                                    24.0,
                                                    36.0,
                                                    72.0},
                                       'numpts': [2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0],
                                       'numpts_attr': {2049280.0},
                                       'rho': {0.01},
                                       'rounds': {3.0},
                                       'serialalgo': {'parallel'},
                                       'testcount': 7,
                                       'totaltime': [109.709,
                                                     27.5326,
                                                     13.9803,
                                                     7.43488,
                                                     5.3517,
                                                     3.93811,
                                                     3.8327],
                                       'variable': 'numprocs',
                                       'x': [1.0,
                                             4.0,
                                             8.0,
                                             16.0,
                                             24.0,
                                             36.0,
                                             72.0]}},
 'numptsPlots': {}}