plotData = {'epsPlots': {'3D_GeoLife_24M': {'algo': {'approx'},
                                 'assignbordertime': [0.00315785,
                                                      0.00389814,
                                                      0.00434399,
                                                      0.00133181],
                                 'assigngridtime': [0.172427,
                                                    0.175345,
                                                    0.177877,
                                                    0.193391],
                                 'buildcoreptquadtree': [0.37523,
                                                         0.363708,
                                                         0.292721,
                                                         0.307271],
                                 'buildgetnbrkdt': [0.00133014,
                                                    0.001019,
                                                    0.000272036,
                                                    0.000337124],
                                 'clustercoretime': [0.039377,
                                                     0.0304699,
                                                     0.0203021,
                                                     0.0182302],
                                 'config-id': '07-12-real2',
                                 'configuration': 'nd-approx: after the kdtree '
                                                  'scanleft change, using '
                                                  'quadtree markcore for '
                                                  'approx, jemalloc, no '
                                                  'bucketing, array kdt, array '
                                                  'quadtree, long variable '
                                                  'type, double datatype, '
                                                  'commit: ',
                                 'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                 'dataset': '3D_GeoLife_24M.pbbs',
                                 'dim': {3.0},
                                 'dimname': '3D_GeoLife_',
                                 'eps': {40.0, 80.0, 20.0, 160.0},
                                 'machine': 'aws-c5.18x',
                                 'markcoretime': [0.471993,
                                                  0.416444,
                                                  0.352182,
                                                  0.289094],
                                 'minpts': {100.0},
                                 'ndalgo': {'nd'},
                                 'numborder': [7391.0, 3792.0, 3572.0, 990.0],
                                 'numclusterpts': [24846295.0,
                                                   24859769.0,
                                                   24868067.0,
                                                   24873703.0],
                                 'numclusters': [91.0, 63.0, 56.0, 24.0],
                                 'numcore': [24838633.0,
                                             24855826.0,
                                             24864335.0,
                                             24872696.0],
                                 'numgrids': [22919.0, 9684.0, 3612.0, 1694.0],
                                 'numnoise': [30954.0, 17360.0, 9071.0, 3292.0],
                                 'numprocs': {72.0},
                                 'numpts': [24876978.0,
                                            24876978.0,
                                            24876978.0,
                                            24876978.0],
                                 'numpts_attr': {24876978.0},
                                 'rho': {0.01},
                                 'rounds': {3.0},
                                 'serialalgo': {'parallel'},
                                 'testcount': 4,
                                 'totaltime': [1.06494,
                                               0.991081,
                                               0.847969,
                                               0.809833],
                                 'variable': 'eps',
                                 'x': [20.0, 40.0, 80.0, 160.0]},
              '7D_HouseHold_2M': {'algo': {'approx'},
                                  'assignbordertime': [0.142203,
                                                       0.088182,
                                                       0.144813,
                                                       0.210141,
                                                       0.221284,
                                                       0.213575],
                                  'assigngridtime': [0.0435719,
                                                     0.181307,
                                                     0.0358551,
                                                     0.0405719,
                                                     0.036284,
                                                     0.0394599],
                                  'buildcoreptquadtree': [0.0402029,
                                                          0.0518339,
                                                          0.062165,
                                                          0.060133,
                                                          0.061764,
                                                          0.118853],
                                  'buildgetnbrkdt': [0.138434,
                                                     0.105385,
                                                     0.0579641,
                                                     0.029511,
                                                     0.0249939,
                                                     0.032197],
                                  'clustercoretime': [0.208334,
                                                      0.145367,
                                                      0.197115,
                                                      0.431116,
                                                      0.941778,
                                                      2.80896],
                                  'config-id': '07-12-real2',
                                  'configuration': 'nd-approx: after the '
                                                   'kdtree scanleft change, '
                                                   'using quadtree markcore '
                                                   'for approx, jemalloc, no '
                                                   'bucketing, array kdt, '
                                                   'array quadtree, long '
                                                   'variable type, double '
                                                   'datatype, commit: ',
                                  'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                  'dataset': '7D_HouseHold_2M.pbbs',
                                  'dim': {7.0},
                                  'dimname': '7D_HouseHold_',
                                  'eps': {1000.0,
                                          1400.0,
                                          1800.0,
                                          2200.0,
                                          2600.0,
                                          3000.0},
                                  'machine': 'aws-c5.18x',
                                  'markcoretime': [2.33555,
                                                   2.6121,
                                                   2.93214,
                                                   4.03813,
                                                   4.684,
                                                   5.16106],
                                  'minpts': {100.0},
                                  'ndalgo': {'nd'},
                                  'numborder': [123077.0,
                                                148926.0,
                                                121447.0,
                                                97189.0,
                                                76854.0,
                                                64485.0],
                                  'numclusterpts': [1220205.0,
                                                    1507976.0,
                                                    1668837.0,
                                                    1760132.0,
                                                    1815454.0,
                                                    1855854.0],
                                  'numclusters': [55.0,
                                                  30.0,
                                                  27.0,
                                                  30.0,
                                                  38.0,
                                                  48.0],
                                  'numcore': [1096868.0,
                                              1358900.0,
                                              1547291.0,
                                              1662856.0,
                                              1738555.0,
                                              1791293.0],
                                  'numgrids': [987740.0,
                                               796144.0,
                                               664053.0,
                                               570752.0,
                                               498785.0,
                                               442979.0],
                                  'numnoise': [829335.0,
                                               541454.0,
                                               380542.0,
                                               289235.0,
                                               233871.0,
                                               193502.0],
                                  'numprocs': {72.0},
                                  'numpts': [2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0],
                                  'numpts_attr': {2049280.0},
                                  'rho': {0.01},
                                  'rounds': {3.0},
                                  'serialalgo': {'parallel'},
                                  'testcount': 6,
                                  'totaltime': [2.926,
                                                3.2053,
                                                3.4478,
                                                4.86999,
                                                6.00299,
                                                8.42741],
                                  'variable': 'eps',
                                  'x': [1000.0,
                                        1400.0,
                                        1800.0,
                                        2200.0,
                                        2600.0,
                                        3000.0]}},
 'minptsPlots': {'3D_GeoLife_24M': {'algo': {'approx'},
                                    'assignbordertime': [0.00414991,
                                                         0.00389814,
                                                         0.00404787,
                                                         0.00936294,
                                                         0.104917,
                                                         0.189869],
                                    'assigngridtime': [0.174493,
                                                       0.175345,
                                                       0.177536,
                                                       0.172387,
                                                       0.1739,
                                                       0.17104],
                                    'buildcoreptquadtree': [0.315275,
                                                            0.363708,
                                                            0.364796,
                                                            0.343605,
                                                            0.385906,
                                                            0.374589],
                                    'buildgetnbrkdt': [0.000967026,
                                                       0.001019,
                                                       0.0010879,
                                                       0.00103807,
                                                       0.00110412,
                                                       0.00107694],
                                    'clustercoretime': [0.0438242,
                                                        0.0304699,
                                                        0.0381801,
                                                        0.0815771,
                                                        0.034415,
                                                        0.0350981],
                                    'config-id': '07-12-real2',
                                    'configuration': 'nd-approx: after the '
                                                     'kdtree scanleft change, '
                                                     'using quadtree markcore '
                                                     'for approx, jemalloc, no '
                                                     'bucketing, array kdt, '
                                                     'array quadtree, long '
                                                     'variable type, double '
                                                     'datatype, commit: ',
                                    'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                    'dataset': '3D_GeoLife_24M.pbbs',
                                    'dim': {3.0},
                                    'dimname': '3D_GeoLife_',
                                    'eps': {40.0},
                                    'machine': 'aws-c5.18x',
                                    'markcoretime': [0.392917,
                                                     0.416444,
                                                     0.413605,
                                                     0.399887,
                                                     0.544155,
                                                     0.554971],
                                    'minpts': {10.0,
                                               100.0,
                                               500.0,
                                               1000.0,
                                               5000.0,
                                               10000.0},
                                    'ndalgo': {'nd'},
                                    'numborder': [320.0,
                                                  3792.0,
                                                  8875.0,
                                                  17552.0,
                                                  100174.0,
                                                  91834.0],
                                    'numclusterpts': [24875629.0,
                                                      24859769.0,
                                                      24824591.0,
                                                      24795161.0,
                                                      24501620.0,
                                                      24141105.0],
                                    'numclusters': [84.0,
                                                    63.0,
                                                    26.0,
                                                    21.0,
                                                    19.0,
                                                    8.0],
                                    'numcore': [24875293.0,
                                                24855826.0,
                                                24815466.0,
                                                24776370.0,
                                                24399987.0,
                                                24049271.0],
                                    'numgrids': [9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0],
                                    'numnoise': [1365.0,
                                                 17360.0,
                                                 52637.0,
                                                 83056.0,
                                                 376817.0,
                                                 735873.0],
                                    'numprocs': {72.0},
                                    'numpts': [24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0],
                                    'numpts_attr': {24876978.0},
                                    'rho': {0.01},
                                    'rounds': {3.0},
                                    'serialalgo': {'parallel'},
                                    'testcount': 6,
                                    'totaltime': [0.931853,
                                                  0.991081,
                                                  0.99955,
                                                  1.00816,
                                                  1.24474,
                                                  1.32696],
                                    'variable': 'minpts',
                                    'x': [10.0,
                                          100.0,
                                          500.0,
                                          1000.0,
                                          5000.0,
                                          10000.0]},
                 '7D_HouseHold_2M': {'algo': {'approx'},
                                     'assignbordertime': [0.0197949,
                                                          0.140978,
                                                          0.462073,
                                                          0.850389,
                                                          2.40852,
                                                          2.09507],
                                     'assigngridtime': [0.0399129,
                                                        0.0384462,
                                                        0.037725,
                                                        0.047456,
                                                        0.036088,
                                                        0.032361],
                                     'buildcoreptquadtree': [0.0771799,
                                                             0.0590119,
                                                             0.0395429,
                                                             0.035584,
                                                             0.016197,
                                                             0.012073],
                                     'buildgetnbrkdt': [0.0366161,
                                                        0.0334949,
                                                        0.043987,
                                                        0.041554,
                                                        0.0423169,
                                                        0.0418222],
                                     'clustercoretime': [0.395845,
                                                         0.184153,
                                                         0.085814,
                                                         0.0549901,
                                                         0.0104749,
                                                         0.00738192],
                                     'config-id': '07-12-real2',
                                     'configuration': 'nd-approx: after the '
                                                      'kdtree scanleft change, '
                                                      'using quadtree markcore '
                                                      'for approx, jemalloc, '
                                                      'no bucketing, array '
                                                      'kdt, array quadtree, '
                                                      'long variable type, '
                                                      'double datatype, '
                                                      'commit: ',
                                     'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                     'dataset': '7D_HouseHold_2M.pbbs',
                                     'dim': {7.0},
                                     'dimname': '7D_HouseHold_',
                                     'eps': {2000.0},
                                     'machine': 'aws-c5.18x',
                                     'markcoretime': [2.26139,
                                                      2.87249,
                                                      4.41102,
                                                      5.68086,
                                                      10.5393,
                                                      12.8128],
                                     'minpts': {10.0,
                                                100.0,
                                                500.0,
                                                1000.0,
                                                5000.0,
                                                10000.0},
                                     'ndalgo': {'nd'},
                                     'numborder': [42452.0,
                                                   108607.0,
                                                   174591.0,
                                                   209145.0,
                                                   318927.0,
                                                   233088.0],
                                     'numclusterpts': [1910237.0,
                                                       1721856.0,
                                                       1462453.0,
                                                       1318872.0,
                                                       874952.0,
                                                       514765.0],
                                     'numclusters': [595.0,
                                                     27.0,
                                                     13.0,
                                                     12.0,
                                                     8.0,
                                                     4.0],
                                     'numcore': [1867325.0,
                                                 1613187.0,
                                                 1287762.0,
                                                 1109405.0,
                                                 555714.0,
                                                 281677.0],
                                     'numgrids': [613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0],
                                     'numnoise': [139503.0,
                                                  327486.0,
                                                  586927.0,
                                                  730730.0,
                                                  1174639.0,
                                                  1534515.0],
                                     'numprocs': {72.0},
                                     'numpts': [2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0],
                                     'numpts_attr': {2049280.0},
                                     'rho': {0.01},
                                     'rounds': {3.0},
                                     'serialalgo': {'parallel'},
                                     'testcount': 6,
                                     'totaltime': [2.85426,
                                                   3.35677,
                                                   5.1038,
                                                   6.7737,
                                                   13.123,
                                                   15.0748],
                                     'variable': 'minpts',
                                     'x': [10.0,
                                           100.0,
                                           500.0,
                                           1000.0,
                                           5000.0,
                                           10000.0]}},
 'numprocsPlots': {'3D_GeoLife_24M': {'algo': {'approx'},
                                      'assignbordertime': [0.010072,
                                                           0.00503397,
                                                           0.00364184,
                                                           0.00314808,
                                                           0.00283599,
                                                           0.00243497,
                                                           0.00389814],
                                      'assigngridtime': [1.74008,
                                                         0.582586,
                                                         0.367898,
                                                         0.237574,
                                                         0.204587,
                                                         0.190191,
                                                         0.175345],
                                      'buildcoreptquadtree': [7.27684,
                                                              2.47218,
                                                              1.41539,
                                                              0.801072,
                                                              0.580685,
                                                              0.439302,
                                                              0.363708],
                                      'buildgetnbrkdt': [0.000602007,
                                                         0.000649929,
                                                         0.000699043,
                                                         0.000619888,
                                                         0.000642061,
                                                         0.000649929,
                                                         0.001019],
                                      'clustercoretime': [0.236436,
                                                          0.075278,
                                                          0.0556121,
                                                          0.0842609,
                                                          0.0358238,
                                                          0.0342472,
                                                          0.0304699],
                                      'config-id': '07-12-real2',
                                      'configuration': 'nd-approx: after the '
                                                       'kdtree scanleft '
                                                       'change, using quadtree '
                                                       'markcore for approx, '
                                                       'jemalloc, no '
                                                       'bucketing, array kdt, '
                                                       'array quadtree, long '
                                                       'variable type, double '
                                                       'datatype, commit: ',
                                      'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                      'dataset': '3D_GeoLife_24M.pbbs',
                                      'dim': {3.0},
                                      'dimname': '3D_GeoLife_',
                                      'eps': {40.0},
                                      'machine': 'aws-c5.18x',
                                      'markcoretime': [7.74042,
                                                       2.52796,
                                                       1.41475,
                                                       0.820318,
                                                       0.571933,
                                                       0.464808,
                                                       0.416444],
                                      'minpts': {100.0},
                                      'ndalgo': {'nd'},
                                      'numborder': [3792.0,
                                                    3792.0,
                                                    3792.0,
                                                    3792.0,
                                                    3792.0,
                                                    3792.0,
                                                    3792.0],
                                      'numclusterpts': [24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0],
                                      'numclusters': [63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0],
                                      'numcore': [24855826.0,
                                                  24855826.0,
                                                  24855826.0,
                                                  24855826.0,
                                                  24855826.0,
                                                  24855826.0,
                                                  24855826.0],
                                      'numgrids': [9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0],
                                      'numnoise': [17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0],
                                      'numprocs': {1.0,
                                                   4.0,
                                                   8.0,
                                                   16.0,
                                                   24.0,
                                                   36.0,
                                                   72.0},
                                      'numpts': [24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0],
                                      'numpts_attr': {24876978.0},
                                      'rho': {0.01},
                                      'rounds': {3.0},
                                      'serialalgo': {'parallel'},
                                      'testcount': 7,
                                      'totaltime': [17.0048,
                                                    5.66415,
                                                    3.25847,
                                                    1.94717,
                                                    1.39671,
                                                    1.13176,
                                                    0.991081],
                                      'variable': 'numprocs',
                                      'x': [1.0,
                                            4.0,
                                            8.0,
                                            16.0,
                                            24.0,
                                            36.0,
                                            72.0]},
                   '7D_HouseHold_2M': {'algo': {'approx'},
                                       'assignbordertime': [3.31513,
                                                            1.07353,
                                                            0.53492,
                                                            0.299999,
                                                            0.205308,
                                                            0.140315,
                                                            0.140978],
                                       'assigngridtime': [0.79921,
                                                          0.230116,
                                                          0.138242,
                                                          0.070281,
                                                          0.0496869,
                                                          0.057097,
                                                          0.0384462],
                                       'buildcoreptquadtree': [0.785257,
                                                               0.253929,
                                                               0.133495,
                                                               0.0862069,
                                                               0.076375,
                                                               0.0763109,
                                                               0.0590119],
                                       'buildgetnbrkdt': [0.641755,
                                                          0.215726,
                                                          0.095248,
                                                          0.059907,
                                                          0.0441439,
                                                          0.0418091,
                                                          0.0334949],
                                       'clustercoretime': [5.77668,
                                                           1.86324,
                                                           0.706967,
                                                           0.386824,
                                                           0.313643,
                                                           0.217966,
                                                           0.184153],
                                       'config-id': '07-12-real2',
                                       'configuration': 'nd-approx: after the '
                                                        'kdtree scanleft '
                                                        'change, using '
                                                        'quadtree markcore for '
                                                        'approx, jemalloc, no '
                                                        'bucketing, array kdt, '
                                                        'array quadtree, long '
                                                        'variable type, double '
                                                        'datatype, commit: ',
                                       'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                       'dataset': '7D_HouseHold_2M.pbbs',
                                       'dim': {7.0},
                                       'dimname': '7D_HouseHold_',
                                       'eps': {2000.0},
                                       'machine': 'aws-c5.18x',
                                       'markcoretime': [91.837,
                                                        24.5169,
                                                        12.3937,
                                                        6.38721,
                                                        4.50044,
                                                        3.41339,
                                                        2.87249],
                                       'minpts': {100.0},
                                       'ndalgo': {'nd'},
                                       'numborder': [108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0],
                                       'numclusterpts': [1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0],
                                       'numclusters': [27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0],
                                       'numcore': [1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0],
                                       'numgrids': [613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0],
                                       'numnoise': [327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0],
                                       'numprocs': {1.0,
                                                    4.0,
                                                    8.0,
                                                    16.0,
                                                    24.0,
                                                    36.0,
                                                    72.0},
                                       'numpts': [2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0],
                                       'numpts_attr': {2049280.0},
                                       'rho': {0.01},
                                       'rounds': {3.0},
                                       'serialalgo': {'parallel'},
                                       'testcount': 7,
                                       'totaltime': [103.226,
                                                     28.2621,
                                                     14.1299,
                                                     7.34558,
                                                     5.23644,
                                                     3.97543,
                                                     3.35677],
                                       'variable': 'numprocs',
                                       'x': [1.0,
                                             4.0,
                                             8.0,
                                             16.0,
                                             24.0,
                                             36.0,
                                             72.0]}},
 'numptsPlots': {},
 'rhoPlots': {'3D_GeoLife_24M': {'algo': {'approx'},
                                 'assignbordertime': [0.00422215,
                                                      0.00389814,
                                                      0.00406504,
                                                      0.00434494,
                                                      0.00405192],
                                 'assigngridtime': [0.166433,
                                                    0.175345,
                                                    0.179389,
                                                    0.202711,
                                                    0.187837],
                                 'buildcoreptquadtree': [0.518343,
                                                         0.363708,
                                                         0.307105,
                                                         0.237485,
                                                         0.199646],
                                 'buildgetnbrkdt': [0.000993967,
                                                    0.001019,
                                                    0.00106788,
                                                    0.00105095,
                                                    0.00107098],
                                 'clustercoretime': [0.062696,
                                                     0.0304699,
                                                     0.040302,
                                                     0.0230882,
                                                     0.017127],
                                 'config-id': '07-12-real2',
                                 'configuration': 'nd-approx: after the kdtree '
                                                  'scanleft change, using '
                                                  'quadtree markcore for '
                                                  'approx, jemalloc, no '
                                                  'bucketing, array kdt, array '
                                                  'quadtree, long variable '
                                                  'type, double datatype, '
                                                  'commit: ',
                                 'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                 'dataset': '3D_GeoLife_24M.pbbs',
                                 'dim': {3.0},
                                 'dimname': '3D_GeoLife_',
                                 'eps': {40.0},
                                 'machine': 'aws-c5.18x',
                                 'markcoretime': [0.624581,
                                                  0.416444,
                                                  0.330218,
                                                  0.279423,
                                                  0.265721],
                                 'minpts': {100.0},
                                 'ndalgo': {'nd'},
                                 'numborder': [3791.0,
                                               3792.0,
                                               3792.0,
                                               3793.0,
                                               3797.0],
                                 'numclusterpts': [24859769.0,
                                                   24859769.0,
                                                   24859769.0,
                                                   24859761.0,
                                                   24859706.0],
                                 'numclusters': [63.0, 63.0, 63.0, 63.0, 62.0],
                                 'numcore': [24855827.0,
                                             24855826.0,
                                             24855826.0,
                                             24855817.0,
                                             24855792.0],
                                 'numgrids': [9684.0,
                                              9684.0,
                                              9684.0,
                                              9684.0,
                                              9684.0],
                                 'numnoise': [17360.0,
                                              17360.0,
                                              17360.0,
                                              17368.0,
                                              17389.0],
                                 'numprocs': {72.0},
                                 'numpts': [24876978.0,
                                            24876978.0,
                                            24876978.0,
                                            24876978.0,
                                            24876978.0],
                                 'numpts_attr': {24876978.0},
                                 'rho': {0.02, 0.1, 0.01, 0.05, 0.001},
                                 'rounds': {3.0},
                                 'serialalgo': {'parallel'},
                                 'testcount': 5,
                                 'totaltime': [1.37751,
                                               0.991081,
                                               0.862398,
                                               0.748361,
                                               0.675646],
                                 'variable': 'rho',
                                 'x': [0.001, 0.01, 0.02, 0.05, 0.1]},
              '7D_HouseHold_2M': {'algo': {'approx'},
                                  'assignbordertime': [0.142733,
                                                       0.140978,
                                                       0.139689,
                                                       0.134144,
                                                       0.136939],
                                  'assigngridtime': [0.049257,
                                                     0.0384462,
                                                     0.0386319,
                                                     0.0368009,
                                                     0.0421441],
                                  'buildcoreptquadtree': [0.056525,
                                                          0.0590119,
                                                          0.0573609,
                                                          0.066282,
                                                          0.0553572],
                                  'buildgetnbrkdt': [0.0437298,
                                                     0.0334949,
                                                     0.03457,
                                                     0.0449359,
                                                     0.042897],
                                  'clustercoretime': [0.234255,
                                                      0.184153,
                                                      0.222059,
                                                      0.1873,
                                                      0.230985],
                                  'config-id': '07-12-real2',
                                  'configuration': 'nd-approx: after the '
                                                   'kdtree scanleft change, '
                                                   'using quadtree markcore '
                                                   'for approx, jemalloc, no '
                                                   'bucketing, array kdt, '
                                                   'array quadtree, long '
                                                   'variable type, double '
                                                   'datatype, commit: ',
                                  'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                  'dataset': '7D_HouseHold_2M.pbbs',
                                  'dim': {7.0},
                                  'dimname': '7D_HouseHold_',
                                  'eps': {2000.0},
                                  'machine': 'aws-c5.18x',
                                  'markcoretime': [2.88682,
                                                   2.87249,
                                                   2.93658,
                                                   2.99969,
                                                   2.92929],
                                  'minpts': {100.0},
                                  'ndalgo': {'nd'},
                                  'numborder': [108607.0,
                                                108607.0,
                                                108607.0,
                                                108607.0,
                                                108607.0],
                                  'numclusterpts': [1721856.0,
                                                    1721856.0,
                                                    1721856.0,
                                                    1721856.0,
                                                    1721856.0],
                                  'numclusters': [27.0, 27.0, 27.0, 27.0, 27.0],
                                  'numcore': [1613187.0,
                                              1613187.0,
                                              1613187.0,
                                              1613187.0,
                                              1613187.0],
                                  'numgrids': [613546.0,
                                               613546.0,
                                               613546.0,
                                               613546.0,
                                               613546.0],
                                  'numnoise': [327486.0,
                                               327486.0,
                                               327486.0,
                                               327486.0,
                                               327486.0],
                                  'numprocs': {72.0},
                                  'numpts': [2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0],
                                  'numpts_attr': {2049280.0},
                                  'rho': {0.02, 0.1, 0.01, 0.05, 0.001},
                                  'rounds': {3.0},
                                  'serialalgo': {'parallel'},
                                  'testcount': 5,
                                  'totaltime': [3.43382,
                                                3.35677,
                                                3.48565,
                                                3.48836,
                                                3.45787],
                                  'variable': 'rho',
                                  'x': [0.001, 0.01, 0.02, 0.05, 0.1]}}}