plotData = {'epsPlots': {'3D_GeoLife_24M': {'algo': {'approx'},
                                 'assignbordertime': [0.00351,
                                                      0.00452399,
                                                      0.004668,
                                                      0.00152898],
                                 'assigngridtime': [0.169589,
                                                    0.162155,
                                                    0.16077,
                                                    0.167759],
                                 'buildcoreptquadtree': [0.337396,
                                                         0.319085,
                                                         0.300589,
                                                         0.296407],
                                 'buildgetnbrkdt': [0.00156999,
                                                    0.00116491,
                                                    0.000504017,
                                                    0.000417948],
                                 'clustercoretime': [0.0269151,
                                                     0.0171449,
                                                     0.0140021,
                                                     0.0126472],
                                 'config-id': '07-07-real2',
                                 'configuration': 'nd-approx/nd-exactbcp/nd-exactquadtree/nd-exactbcpbucketing: '
                                                  'after the kdtree scanleft '
                                                  'change, to obtain a new '
                                                  'result for household '
                                                  'dataset; jemalloc for all, '
                                                  'bucketing only for '
                                                  'nd-exactquadtree, array kdt '
                                                  'for all, array quadtree for '
                                                  'any config that involve a '
                                                  'quadtree, long variable '
                                                  'type for any config that '
                                                  'involve a quadtree, double '
                                                  'datatype, commit: ',
                                 'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                 'dataset': '3D_GeoLife_24M.pbbs',
                                 'dim': {3.0},
                                 'dimname': '3D_GeoLife_',
                                 'eps': {40.0, 80.0, 20.0, 160.0},
                                 'machine': 'aws-c5.18x',
                                 'markcoretime': [0.0624142,
                                                  0.0200369,
                                                  0.095634,
                                                  0.00853801],
                                 'minpts': {100.0},
                                 'ndalgo': {'nd'},
                                 'numborder': [7391.0, 3791.0, 3572.0, 990.0],
                                 'numclusterpts': [24846295.0,
                                                   24859769.0,
                                                   24868067.0,
                                                   24873703.0],
                                 'numclusters': [91.0, 63.0, 56.0, 24.0],
                                 'numcore': [24838633.0,
                                             24855827.0,
                                             24864335.0,
                                             24872696.0],
                                 'numgrids': [22919.0, 9684.0, 3612.0, 1694.0],
                                 'numnoise': [30954.0, 17360.0, 9071.0, 3292.0],
                                 'numprocs': {72.0},
                                 'numpts': [24876978.0,
                                            24876978.0,
                                            24876978.0,
                                            24876978.0],
                                 'numpts_attr': {24876978.0},
                                 'rho': {0.01},
                                 'rounds': {3.0},
                                 'serialalgo': {'parallel'},
                                 'testcount': 4,
                                 'totaltime': [0.601799,
                                               0.524387,
                                               0.576446,
                                               0.487436],
                                 'variable': 'eps',
                                 'x': [20.0, 40.0, 80.0, 160.0]},
              '7D_HouseHold_2M': {'algo': {'approx'},
                                  'assignbordertime': [0.145239,
                                                       0.0928528,
                                                       0.152701,
                                                       0.224266,
                                                       0.218456,
                                                       0.240635],
                                  'assigngridtime': [0.0451632,
                                                     0.045043,
                                                     0.0349479,
                                                     0.0341291,
                                                     0.0401359,
                                                     0.044379],
                                  'buildcoreptquadtree': [0.043993,
                                                          0.052417,
                                                          0.059598,
                                                          0.066355,
                                                          0.0671949,
                                                          0.0680959],
                                  'buildgetnbrkdt': [0.169591,
                                                     0.0902259,
                                                     0.051079,
                                                     0.0358958,
                                                     0.038779,
                                                     0.0182819],
                                  'clustercoretime': [0.202954,
                                                      0.146414,
                                                      0.186484,
                                                      0.406599,
                                                      0.865558,
                                                      2.46794],
                                  'config-id': '07-07-real2',
                                  'configuration': 'nd-approx/nd-exactbcp/nd-exactquadtree/nd-exactbcpbucketing: '
                                                   'after the kdtree scanleft '
                                                   'change, to obtain a new '
                                                   'result for household '
                                                   'dataset; jemalloc for all, '
                                                   'bucketing only for '
                                                   'nd-exactquadtree, array '
                                                   'kdt for all, array '
                                                   'quadtree for any config '
                                                   'that involve a quadtree, '
                                                   'long variable type for any '
                                                   'config that involve a '
                                                   'quadtree, double datatype, '
                                                   'commit: ',
                                  'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                  'dataset': '7D_HouseHold_2M.pbbs',
                                  'dim': {7.0},
                                  'dimname': '7D_HouseHold_',
                                  'eps': {1000.0,
                                          1400.0,
                                          1800.0,
                                          2200.0,
                                          2600.0,
                                          3000.0},
                                  'machine': 'aws-c5.18x',
                                  'markcoretime': [2.62667,
                                                   2.94248,
                                                   4.14467,
                                                   8.66402,
                                                   9.16683,
                                                   11.0875],
                                  'minpts': {100.0},
                                  'ndalgo': {'nd'},
                                  'numborder': [123077.0,
                                                148926.0,
                                                121447.0,
                                                97189.0,
                                                76854.0,
                                                64485.0],
                                  'numclusterpts': [1220205.0,
                                                    1507976.0,
                                                    1668837.0,
                                                    1760132.0,
                                                    1815454.0,
                                                    1855854.0],
                                  'numclusters': [55.0,
                                                  30.0,
                                                  27.0,
                                                  30.0,
                                                  38.0,
                                                  48.0],
                                  'numcore': [1096868.0,
                                              1358900.0,
                                              1547291.0,
                                              1662856.0,
                                              1738555.0,
                                              1791293.0],
                                  'numgrids': [987740.0,
                                               796144.0,
                                               664053.0,
                                               570752.0,
                                               498785.0,
                                               442979.0],
                                  'numnoise': [829335.0,
                                               541454.0,
                                               380542.0,
                                               289235.0,
                                               233871.0,
                                               193502.0],
                                  'numprocs': {72.0},
                                  'numpts': [2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0],
                                  'numpts_attr': {2049280.0},
                                  'rho': {0.01},
                                  'rounds': {3.0},
                                  'serialalgo': {'parallel'},
                                  'testcount': 6,
                                  'totaltime': [3.27355,
                                                3.3912,
                                                4.66723,
                                                9.49432,
                                                10.423,
                                                14.0247],
                                  'variable': 'eps',
                                  'x': [1000.0,
                                        1400.0,
                                        1800.0,
                                        2200.0,
                                        2600.0,
                                        3000.0]}},
 'minptsPlots': {'3D_GeoLife_24M': {'algo': {'approx'},
                                    'assignbordertime': [0.00438499,
                                                         0.00452399,
                                                         0.0037241,
                                                         0.00894904,
                                                         0.103776,
                                                         0.192047],
                                    'assigngridtime': [0.164481,
                                                       0.162155,
                                                       0.158407,
                                                       0.16532,
                                                       0.163912,
                                                       0.166147],
                                    'buildcoreptquadtree': [0.322117,
                                                            0.319085,
                                                            0.323763,
                                                            0.320176,
                                                            0.323211,
                                                            0.321541],
                                    'buildgetnbrkdt': [0.001297,
                                                       0.00116491,
                                                       0.00127101,
                                                       0.00119305,
                                                       0.00125909,
                                                       0.00127602],
                                    'clustercoretime': [0.019563,
                                                        0.0171449,
                                                        0.021183,
                                                        0.0151439,
                                                        0.0163631,
                                                        0.0149548],
                                    'config-id': '07-07-real2',
                                    'configuration': 'nd-approx/nd-exactbcp/nd-exactquadtree/nd-exactbcpbucketing: '
                                                     'after the kdtree '
                                                     'scanleft change, to '
                                                     'obtain a new result for '
                                                     'household dataset; '
                                                     'jemalloc for all, '
                                                     'bucketing only for '
                                                     'nd-exactquadtree, array '
                                                     'kdt for all, array '
                                                     'quadtree for any config '
                                                     'that involve a quadtree, '
                                                     'long variable type for '
                                                     'any config that involve '
                                                     'a quadtree, double '
                                                     'datatype, commit: ',
                                    'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                    'dataset': '3D_GeoLife_24M.pbbs',
                                    'dim': {3.0},
                                    'dimname': '3D_GeoLife_',
                                    'eps': {40.0},
                                    'machine': 'aws-c5.18x',
                                    'markcoretime': [0.017663,
                                                     0.0200369,
                                                     0.0487261,
                                                     0.125712,
                                                     0.882787,
                                                     2.3305],
                                    'minpts': {10.0,
                                               100.0,
                                               500.0,
                                               1000.0,
                                               5000.0,
                                               10000.0},
                                    'ndalgo': {'nd'},
                                    'numborder': [320.0,
                                                  3791.0,
                                                  8860.0,
                                                  17546.0,
                                                  100090.0,
                                                  91985.0],
                                    'numclusterpts': [24875629.0,
                                                      24859769.0,
                                                      24824591.0,
                                                      24795161.0,
                                                      24501634.0,
                                                      24141423.0],
                                    'numclusters': [84.0,
                                                    63.0,
                                                    26.0,
                                                    21.0,
                                                    19.0,
                                                    8.0],
                                    'numcore': [24875293.0,
                                                24855827.0,
                                                24815481.0,
                                                24776376.0,
                                                24400085.0,
                                                24049438.0],
                                    'numgrids': [9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0],
                                    'numnoise': [1365.0,
                                                 17360.0,
                                                 52637.0,
                                                 83056.0,
                                                 376803.0,
                                                 735555.0],
                                    'numprocs': {72.0},
                                    'numpts': [24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0],
                                    'numpts_attr': {24876978.0},
                                    'rho': {0.01},
                                    'rounds': {3.0},
                                    'serialalgo': {'parallel'},
                                    'testcount': 6,
                                    'totaltime': [0.52976,
                                                  0.524387,
                                                  0.557372,
                                                  0.636848,
                                                  1.49194,
                                                  3.02683],
                                    'variable': 'minpts',
                                    'x': [10.0,
                                          100.0,
                                          500.0,
                                          1000.0,
                                          5000.0,
                                          10000.0]},
                 '7D_HouseHold_2M': {'algo': {'approx'},
                                     'assignbordertime': [0.0187662,
                                                          0.142324,
                                                          0.482421,
                                                          0.891513,
                                                          2.57558,
                                                          2.17737],
                                     'assigngridtime': [0.045054,
                                                        0.0318551,
                                                        0.0479641,
                                                        0.03335,
                                                        0.0332308,
                                                        0.0325599],
                                     'buildcoreptquadtree': [0.076524,
                                                             0.0651731,
                                                             0.0434961,
                                                             0.0344899,
                                                             0.01758,
                                                             0.00985193],
                                     'buildgetnbrkdt': [0.039829,
                                                        0.0370569,
                                                        0.0548019,
                                                        0.0392232,
                                                        0.04146,
                                                        0.0412991],
                                     'clustercoretime': [0.392779,
                                                         0.187967,
                                                         0.0840049,
                                                         0.049108,
                                                         0.00941396,
                                                         0.00437999],
                                     'config-id': '07-07-real2',
                                     'configuration': 'nd-approx/nd-exactbcp/nd-exactquadtree/nd-exactbcpbucketing: '
                                                      'after the kdtree '
                                                      'scanleft change, to '
                                                      'obtain a new result for '
                                                      'household dataset; '
                                                      'jemalloc for all, '
                                                      'bucketing only for '
                                                      'nd-exactquadtree, array '
                                                      'kdt for all, array '
                                                      'quadtree for any config '
                                                      'that involve a '
                                                      'quadtree, long variable '
                                                      'type for any config '
                                                      'that involve a '
                                                      'quadtree, double '
                                                      'datatype, commit: ',
                                     'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                     'dataset': '7D_HouseHold_2M.pbbs',
                                     'dim': {7.0},
                                     'dimname': '7D_HouseHold_',
                                     'eps': {2000.0},
                                     'machine': 'aws-c5.18x',
                                     'markcoretime': [2.88874,
                                                      4.61292,
                                                      6.50945,
                                                      8.01727,
                                                      13.8514,
                                                      17.3621],
                                     'minpts': {10.0,
                                                100.0,
                                                500.0,
                                                1000.0,
                                                5000.0,
                                                10000.0},
                                     'ndalgo': {'nd'},
                                     'numborder': [42452.0,
                                                   108607.0,
                                                   174591.0,
                                                   209145.0,
                                                   318927.0,
                                                   233083.0],
                                     'numclusterpts': [1910237.0,
                                                       1721856.0,
                                                       1462453.0,
                                                       1318872.0,
                                                       874953.0,
                                                       514766.0],
                                     'numclusters': [595.0,
                                                     27.0,
                                                     13.0,
                                                     12.0,
                                                     8.0,
                                                     4.0],
                                     'numcore': [1867325.0,
                                                 1613187.0,
                                                 1287762.0,
                                                 1109405.0,
                                                 555715.0,
                                                 281683.0],
                                     'numgrids': [613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0],
                                     'numnoise': [139503.0,
                                                  327486.0,
                                                  586927.0,
                                                  730730.0,
                                                  1174638.0,
                                                  1534514.0],
                                     'numprocs': {72.0},
                                     'numpts': [2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0],
                                     'numpts_attr': {2049280.0},
                                     'rho': {0.01},
                                     'rounds': {3.0},
                                     'serialalgo': {'parallel'},
                                     'testcount': 6,
                                     'totaltime': [3.52703,
                                                   5.10027,
                                                   7.25782,
                                                   9.1497,
                                                   16.6242,
                                                   19.7128],
                                     'variable': 'minpts',
                                     'x': [10.0,
                                           100.0,
                                           500.0,
                                           1000.0,
                                           5000.0,
                                           10000.0]}},
 'numprocsPlots': {'3D_GeoLife_24M': {'algo': {'approx'},
                                      'assignbordertime': [0.010118,
                                                           0.00498199,
                                                           0.0032959,
                                                           0.00306201,
                                                           0.00256896,
                                                           0.00247192,
                                                           0.00452399],
                                      'assigngridtime': [1.83093,
                                                         0.561776,
                                                         0.31465,
                                                         0.20195,
                                                         0.175288,
                                                         0.160223,
                                                         0.162155],
                                      'buildcoreptquadtree': [7.61862,
                                                              2.61576,
                                                              1.47429,
                                                              0.829968,
                                                              0.590952,
                                                              0.426927,
                                                              0.319085],
                                      'buildgetnbrkdt': [0.000600815,
                                                         0.000967979,
                                                         0.000771046,
                                                         0.000727177,
                                                         0.000712156,
                                                         0.000730038,
                                                         0.00116491],
                                      'clustercoretime': [0.243222,
                                                          0.0774832,
                                                          0.042388,
                                                          0.0253041,
                                                          0.0198491,
                                                          0.0182159,
                                                          0.0171449],
                                      'config-id': '07-07-real2',
                                      'configuration': 'nd-approx/nd-exactbcp/nd-exactquadtree/nd-exactbcpbucketing: '
                                                       'after the kdtree '
                                                       'scanleft change, to '
                                                       'obtain a new result '
                                                       'for household dataset; '
                                                       'jemalloc for all, '
                                                       'bucketing only for '
                                                       'nd-exactquadtree, '
                                                       'array kdt for all, '
                                                       'array quadtree for any '
                                                       'config that involve a '
                                                       'quadtree, long '
                                                       'variable type for any '
                                                       'config that involve a '
                                                       'quadtree, double '
                                                       'datatype, commit: ',
                                      'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                      'dataset': '3D_GeoLife_24M.pbbs',
                                      'dim': {3.0},
                                      'dimname': '3D_GeoLife_',
                                      'eps': {40.0},
                                      'machine': 'aws-c5.18x',
                                      'markcoretime': [0.61686,
                                                       0.162276,
                                                       0.08602,
                                                       0.0457649,
                                                       0.0324709,
                                                       0.023406,
                                                       0.0200369],
                                      'minpts': {100.0},
                                      'ndalgo': {'nd'},
                                      'numborder': [3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0],
                                      'numclusterpts': [24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0],
                                      'numclusters': [63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0],
                                      'numcore': [24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0],
                                      'numgrids': [9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0],
                                      'numnoise': [17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0],
                                      'numprocs': {1.0,
                                                   4.0,
                                                   8.0,
                                                   16.0,
                                                   24.0,
                                                   36.0,
                                                   72.0},
                                      'numpts': [24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0],
                                      'numpts_attr': {24876978.0},
                                      'rho': {0.01},
                                      'rounds': {3.0},
                                      'serialalgo': {'parallel'},
                                      'testcount': 7,
                                      'totaltime': [10.3207,
                                                    3.42369,
                                                    1.92162,
                                                    1.107,
                                                    0.821988,
                                                    0.632117,
                                                    0.524387],
                                      'variable': 'numprocs',
                                      'x': [1.0,
                                            4.0,
                                            8.0,
                                            16.0,
                                            24.0,
                                            36.0,
                                            72.0]},
                   '7D_HouseHold_2M': {'algo': {'approx'},
                                       'assignbordertime': [3.44493,
                                                            0.967913,
                                                            0.527229,
                                                            0.287988,
                                                            0.20747,
                                                            0.147665,
                                                            0.142324],
                                       'assigngridtime': [0.772545,
                                                          0.229434,
                                                          0.13177,
                                                          0.0680089,
                                                          0.0540128,
                                                          0.040257,
                                                          0.0318551],
                                       'buildcoreptquadtree': [0.808158,
                                                               0.237801,
                                                               0.131949,
                                                               0.0923629,
                                                               0.0839889,
                                                               0.0797191,
                                                               0.0651731],
                                       'buildgetnbrkdt': [0.790508,
                                                          0.220996,
                                                          0.103574,
                                                          0.062484,
                                                          0.0462501,
                                                          0.038378,
                                                          0.0370569],
                                       'clustercoretime': [5.61271,
                                                           1.2234,
                                                           0.597826,
                                                           0.363327,
                                                           0.268166,
                                                           0.235877,
                                                           0.187967],
                                       'config-id': '07-07-real2',
                                       'configuration': 'nd-approx/nd-exactbcp/nd-exactquadtree/nd-exactbcpbucketing: '
                                                        'after the kdtree '
                                                        'scanleft change, to '
                                                        'obtain a new result '
                                                        'for household '
                                                        'dataset; jemalloc for '
                                                        'all, bucketing only '
                                                        'for nd-exactquadtree, '
                                                        'array kdt for all, '
                                                        'array quadtree for '
                                                        'any config that '
                                                        'involve a quadtree, '
                                                        'long variable type '
                                                        'for any config that '
                                                        'involve a quadtree, '
                                                        'double datatype, '
                                                        'commit: ',
                                       'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                       'dataset': '7D_HouseHold_2M.pbbs',
                                       'dim': {7.0},
                                       'dimname': '7D_HouseHold_',
                                       'eps': {2000.0},
                                       'machine': 'aws-c5.18x',
                                       'markcoretime': [109.754,
                                                        27.7761,
                                                        14.194,
                                                        7.91099,
                                                        5.87716,
                                                        4.35794,
                                                        4.61292],
                                       'minpts': {100.0},
                                       'ndalgo': {'nd'},
                                       'numborder': [108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0],
                                       'numclusterpts': [1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0],
                                       'numclusters': [27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0],
                                       'numcore': [1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0],
                                       'numgrids': [613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0],
                                       'numnoise': [327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0],
                                       'numprocs': {1.0,
                                                    4.0,
                                                    8.0,
                                                    16.0,
                                                    24.0,
                                                    36.0,
                                                    72.0},
                                       'numpts': [2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0],
                                       'numpts_attr': {2049280.0},
                                       'rho': {0.01},
                                       'rounds': {3.0},
                                       'serialalgo': {'parallel'},
                                       'testcount': 7,
                                       'totaltime': [121.256,
                                                     30.7712,
                                                     15.789,
                                                     8.85009,
                                                     6.59045,
                                                     4.93125,
                                                     5.10027],
                                       'variable': 'numprocs',
                                       'x': [1.0,
                                             4.0,
                                             8.0,
                                             16.0,
                                             24.0,
                                             36.0,
                                             72.0]}},
 'numptsPlots': {}}