plotData = {'epsPlots': {'3D_GeoLife_24M': {'algo': {'approx'},
                                 'assignbordertime': [0.00406504,
                                                      0.00486398,
                                                      0.00463104,
                                                      0.00156689],
                                 'assigngridtime': [0.170189,
                                                    0.1727,
                                                    0.197599,
                                                    0.200202],
                                 'buildcoreptquadtree': [0.378021,
                                                         0.363942,
                                                         0.39137,
                                                         0.299894],
                                 'buildgetnbrkdt': [0.00239611,
                                                    0.00158095,
                                                    0.0032649,
                                                    0.00075388],
                                 'clustercoretime': [0.0363591,
                                                     0.105679,
                                                     0.104325,
                                                     0.018429],
                                 'config-id': '0221-synt4',
                                 'configuration': 'approx-bucketing-qt-real: '
                                                  'kdt scans bothsides, '
                                                  'jemalloc, bucketing on, '
                                                  'array kdt, long variable '
                                                  'type in general, double '
                                                  'datatype',
                                 'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                 'dataset': '3D_GeoLife_24M.pbbs',
                                 'dim': {3.0},
                                 'dimname': '3D_GeoLife_',
                                 'eps': {40.0, 80.0, 20.0, 160.0},
                                 'machine': 'aws-c5.18x',
                                 'markcoretime': [0.44124,
                                                  0.38973,
                                                  0.328255,
                                                  0.280367],
                                 'minpts': {100.0},
                                 'ndalgo': {'nd'},
                                 'numborder': [7391.0, 3792.0, 3572.0, 990.0],
                                 'numclusterpts': [24846295.0,
                                                   24859769.0,
                                                   24868067.0,
                                                   24873703.0],
                                 'numclusters': [91.0, 63.0, 56.0, 24.0],
                                 'numcore': [24838633.0,
                                             24855826.0,
                                             24864335.0,
                                             24872696.0],
                                 'numgrids': [22919.0, 9684.0, 3612.0, 1694.0],
                                 'numnoise': [30954.0, 17360.0, 9071.0, 3292.0],
                                 'numprocs': {72.0},
                                 'numpts': [24876978.0,
                                            24876978.0,
                                            24876978.0,
                                            24876978.0],
                                 'numpts_attr': {24876978.0},
                                 'rho': {0.01},
                                 'rounds': {3.0},
                                 'serialalgo': {'parallel'},
                                 'testcount': 4,
                                 'totaltime': [1.0328,
                                               1.03874,
                                               1.02973,
                                               0.801488],
                                 'variable': 'eps',
                                 'x': [20.0, 40.0, 80.0, 160.0]},
              '7D_HouseHold_2M': {'algo': {'approx'},
                                  'assignbordertime': [0.15263,
                                                       0.0902531,
                                                       0.14649,
                                                       0.191292,
                                                       0.23424,
                                                       0.227428],
                                  'assigngridtime': [0.0482168,
                                                     0.049933,
                                                     0.0371082,
                                                     0.0355771,
                                                     0.0338581,
                                                     0.0746551],
                                  'buildcoreptquadtree': [0.046339,
                                                          0.0531528,
                                                          0.061883,
                                                          0.0661039,
                                                          0.0677552,
                                                          0.0671101],
                                  'buildgetnbrkdt': [0.151266,
                                                     0.0764811,
                                                     0.0551119,
                                                     0.0417449,
                                                     0.0285139,
                                                     0.0220459],
                                  'clustercoretime': [0.23057,
                                                      0.163208,
                                                      0.189394,
                                                      0.480389,
                                                      1.04952,
                                                      3.43235],
                                  'config-id': '0221-synt4',
                                  'configuration': 'approx-bucketing-qt-real: '
                                                   'kdt scans bothsides, '
                                                   'jemalloc, bucketing on, '
                                                   'array kdt, long variable '
                                                   'type in general, double '
                                                   'datatype',
                                  'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                  'dataset': '7D_HouseHold_2M.pbbs',
                                  'dim': {7.0},
                                  'dimname': '7D_HouseHold_',
                                  'eps': {1000.0,
                                          1400.0,
                                          1800.0,
                                          2200.0,
                                          2600.0,
                                          3000.0},
                                  'machine': 'aws-c5.18x',
                                  'markcoretime': [2.27948,
                                                   2.6648,
                                                   3.46844,
                                                   3.94409,
                                                   4.48833,
                                                   4.8963],
                                  'minpts': {100.0},
                                  'ndalgo': {'nd'},
                                  'numborder': [123077.0,
                                                148926.0,
                                                121447.0,
                                                97189.0,
                                                76854.0,
                                                64485.0],
                                  'numclusterpts': [1220205.0,
                                                    1507976.0,
                                                    1668837.0,
                                                    1760132.0,
                                                    1815454.0,
                                                    1855854.0],
                                  'numclusters': [55.0,
                                                  30.0,
                                                  27.0,
                                                  30.0,
                                                  38.0,
                                                  48.0],
                                  'numcore': [1096868.0,
                                              1358900.0,
                                              1547291.0,
                                              1662856.0,
                                              1738555.0,
                                              1791293.0],
                                  'numgrids': [987740.0,
                                               796144.0,
                                               664053.0,
                                               570752.0,
                                               498785.0,
                                               442979.0],
                                  'numnoise': [829335.0,
                                               541454.0,
                                               380542.0,
                                               289235.0,
                                               233871.0,
                                               193502.0],
                                  'numprocs': {72.0},
                                  'numpts': [2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0],
                                  'numpts_attr': {2049280.0},
                                  'rho': {0.01},
                                  'rounds': {3.0},
                                  'serialalgo': {'parallel'},
                                  'testcount': 6,
                                  'totaltime': [2.92363,
                                                3.11725,
                                                3.98198,
                                                4.78675,
                                                5.9487,
                                                8.7771],
                                  'variable': 'eps',
                                  'x': [1000.0,
                                        1400.0,
                                        1800.0,
                                        2200.0,
                                        2600.0,
                                        3000.0]}},
 'minptsPlots': {'3D_GeoLife_24M': {'algo': {'approx'},
                                    'assignbordertime': [0.00441909,
                                                         0.00486398,
                                                         0.00411415,
                                                         0.010112,
                                                         0.111374,
                                                         0.204325],
                                    'assigngridtime': [0.17824,
                                                       0.1727,
                                                       0.179949,
                                                       0.177472,
                                                       0.176712,
                                                       0.180912],
                                    'buildcoreptquadtree': [0.377434,
                                                            0.363942,
                                                            0.364252,
                                                            0.378398,
                                                            0.363335,
                                                            0.36232],
                                    'buildgetnbrkdt': [0.00159907,
                                                       0.00158095,
                                                       0.00172591,
                                                       0.00167203,
                                                       0.0015111,
                                                       0.00160909],
                                    'clustercoretime': [0.0359459,
                                                        0.105679,
                                                        0.0347769,
                                                        0.0393639,
                                                        0.0336611,
                                                        0.0357859],
                                    'config-id': '0221-synt4',
                                    'configuration': 'approx-bucketing-qt-real: '
                                                     'kdt scans bothsides, '
                                                     'jemalloc, bucketing on, '
                                                     'array kdt, long variable '
                                                     'type in general, double '
                                                     'datatype',
                                    'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                    'dataset': '3D_GeoLife_24M.pbbs',
                                    'dim': {3.0},
                                    'dimname': '3D_GeoLife_',
                                    'eps': {40.0},
                                    'machine': 'aws-c5.18x',
                                    'markcoretime': [0.360687,
                                                     0.38973,
                                                     0.415795,
                                                     0.427899,
                                                     0.538199,
                                                     0.54002],
                                    'minpts': {10.0,
                                               100.0,
                                               500.0,
                                               1000.0,
                                               5000.0,
                                               10000.0},
                                    'ndalgo': {'nd'},
                                    'numborder': [320.0,
                                                  3792.0,
                                                  8875.0,
                                                  17552.0,
                                                  100174.0,
                                                  91834.0],
                                    'numclusterpts': [24875629.0,
                                                      24859769.0,
                                                      24824591.0,
                                                      24795161.0,
                                                      24501620.0,
                                                      24141105.0],
                                    'numclusters': [84.0,
                                                    63.0,
                                                    26.0,
                                                    21.0,
                                                    19.0,
                                                    8.0],
                                    'numcore': [24875293.0,
                                                24855826.0,
                                                24815466.0,
                                                24776370.0,
                                                24399987.0,
                                                24049271.0],
                                    'numgrids': [9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0],
                                    'numnoise': [1365.0,
                                                 17360.0,
                                                 52637.0,
                                                 83056.0,
                                                 376817.0,
                                                 735873.0],
                                    'numprocs': {72.0},
                                    'numpts': [24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0],
                                    'numpts_attr': {24876978.0},
                                    'rho': {0.01},
                                    'rounds': {3.0},
                                    'serialalgo': {'parallel'},
                                    'testcount': 6,
                                    'totaltime': [0.95857,
                                                  1.03874,
                                                  1.00185,
                                                  1.03525,
                                                  1.22518,
                                                  1.32534],
                                    'variable': 'minpts',
                                    'x': [10.0,
                                          100.0,
                                          500.0,
                                          1000.0,
                                          5000.0,
                                          10000.0]},
                 '7D_HouseHold_2M': {'algo': {'approx'},
                                     'assignbordertime': [0.018208,
                                                          0.144404,
                                                          0.468666,
                                                          0.845575,
                                                          2.66285,
                                                          2.19065],
                                     'assigngridtime': [0.0393851,
                                                        0.0440729,
                                                        0.0354052,
                                                        0.0442429,
                                                        0.035305,
                                                        0.03897],
                                     'buildcoreptquadtree': [0.0784059,
                                                             0.0674708,
                                                             0.0429771,
                                                             0.0375428,
                                                             0.0176539,
                                                             0.012702],
                                     'buildgetnbrkdt': [0.0442431,
                                                        0.0495341,
                                                        0.043817,
                                                        0.0474691,
                                                        0.0476182,
                                                        0.040585],
                                     'clustercoretime': [0.406904,
                                                         0.203023,
                                                         0.0895319,
                                                         0.0541341,
                                                         0.0201421,
                                                         0.0171762],
                                     'config-id': '0221-synt4',
                                     'configuration': 'approx-bucketing-qt-real: '
                                                      'kdt scans bothsides, '
                                                      'jemalloc, bucketing on, '
                                                      'array kdt, long '
                                                      'variable type in '
                                                      'general, double '
                                                      'datatype',
                                     'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                     'dataset': '7D_HouseHold_2M.pbbs',
                                     'dim': {7.0},
                                     'dimname': '7D_HouseHold_',
                                     'eps': {2000.0},
                                     'machine': 'aws-c5.18x',
                                     'markcoretime': [2.41986,
                                                      3.19576,
                                                      4.56452,
                                                      6.01274,
                                                      11.2057,
                                                      13.7179],
                                     'minpts': {10.0,
                                                100.0,
                                                500.0,
                                                1000.0,
                                                5000.0,
                                                10000.0},
                                     'ndalgo': {'nd'},
                                     'numborder': [42452.0,
                                                   108607.0,
                                                   174591.0,
                                                   209145.0,
                                                   318927.0,
                                                   233088.0],
                                     'numclusterpts': [1910237.0,
                                                       1721856.0,
                                                       1462453.0,
                                                       1318872.0,
                                                       874952.0,
                                                       514765.0],
                                     'numclusters': [595.0,
                                                     27.0,
                                                     13.0,
                                                     12.0,
                                                     8.0,
                                                     4.0],
                                     'numcore': [1867325.0,
                                                 1613187.0,
                                                 1287762.0,
                                                 1109405.0,
                                                 555714.0,
                                                 281677.0],
                                     'numgrids': [613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0],
                                     'numnoise': [139503.0,
                                                  327486.0,
                                                  586927.0,
                                                  730730.0,
                                                  1174639.0,
                                                  1534515.0],
                                     'numprocs': {72.0},
                                     'numpts': [2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0],
                                     'numpts_attr': {2049280.0},
                                     'rho': {0.01},
                                     'rounds': {3.0},
                                     'serialalgo': {'parallel'},
                                     'testcount': 6,
                                     'totaltime': [3.03655,
                                                   3.72409,
                                                   5.27523,
                                                   7.09232,
                                                   14.0522,
                                                   16.0845],
                                     'variable': 'minpts',
                                     'x': [10.0,
                                           100.0,
                                           500.0,
                                           1000.0,
                                           5000.0,
                                           10000.0]}},
 'numprocsPlots': {'3D_GeoLife_24M': {'algo': {'approx'},
                                      'assignbordertime': [0.0107629,
                                                           0.00501704,
                                                           0.00336504,
                                                           0.0029788,
                                                           0.00263405,
                                                           0.00289798,
                                                           0.00486398],
                                      'assigngridtime': [2.25949,
                                                         0.614791,
                                                         0.341631,
                                                         0.24776,
                                                         0.208829,
                                                         0.190707,
                                                         0.1727],
                                      'buildcoreptquadtree': [7.89187,
                                                              2.61368,
                                                              1.47853,
                                                              0.904095,
                                                              0.617172,
                                                              0.461573,
                                                              0.363942],
                                      'buildgetnbrkdt': [0.0023849,
                                                         0.00147104,
                                                         0.00106192,
                                                         0.00104499,
                                                         0.00103712,
                                                         0.00109696,
                                                         0.00158095],
                                      'clustercoretime': [0.220172,
                                                          0.058743,
                                                          0.031682,
                                                          0.073894,
                                                          0.031369,
                                                          0.039072,
                                                          0.105679],
                                      'config-id': '0221-synt4',
                                      'configuration': 'approx-bucketing-qt-real: '
                                                       'kdt scans bothsides, '
                                                       'jemalloc, bucketing '
                                                       'on, array kdt, long '
                                                       'variable type in '
                                                       'general, double '
                                                       'datatype',
                                      'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                      'dataset': '3D_GeoLife_24M.pbbs',
                                      'dim': {3.0},
                                      'dimname': '3D_GeoLife_',
                                      'eps': {40.0},
                                      'machine': 'aws-c5.18x',
                                      'markcoretime': [7.82621,
                                                       2.60028,
                                                       1.44881,
                                                       0.846513,
                                                       0.599925,
                                                       0.481061,
                                                       0.38973],
                                      'minpts': {100.0},
                                      'ndalgo': {'nd'},
                                      'numborder': [3792.0,
                                                    3792.0,
                                                    3792.0,
                                                    3792.0,
                                                    3792.0,
                                                    3792.0,
                                                    3792.0],
                                      'numclusterpts': [24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0],
                                      'numclusters': [63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0],
                                      'numcore': [24855826.0,
                                                  24855826.0,
                                                  24855826.0,
                                                  24855826.0,
                                                  24855826.0,
                                                  24855826.0,
                                                  24855826.0],
                                      'numgrids': [9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0],
                                      'numnoise': [17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0],
                                      'numprocs': {1.0,
                                                   4.0,
                                                   8.0,
                                                   16.0,
                                                   24.0,
                                                   36.0,
                                                   72.0},
                                      'numpts': [24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0],
                                      'numpts_attr': {24876978.0},
                                      'rho': {0.01},
                                      'rounds': {3.0},
                                      'serialalgo': {'parallel'},
                                      'testcount': 7,
                                      'totaltime': [18.2113,
                                                    5.89447,
                                                    3.30544,
                                                    2.07654,
                                                    1.46131,
                                                    1.17663,
                                                    1.03874],
                                      'variable': 'numprocs',
                                      'x': [1.0,
                                            4.0,
                                            8.0,
                                            16.0,
                                            24.0,
                                            36.0,
                                            72.0]},
                   '7D_HouseHold_2M': {'algo': {'approx'},
                                       'assignbordertime': [3.48995,
                                                            1.08332,
                                                            0.548126,
                                                            0.312666,
                                                            0.204655,
                                                            0.144293,
                                                            0.144404],
                                       'assigngridtime': [0.956611,
                                                          0.292532,
                                                          0.128284,
                                                          0.0720298,
                                                          0.062664,
                                                          0.0381129,
                                                          0.0440729],
                                       'buildcoreptquadtree': [0.823813,
                                                               0.269305,
                                                               0.138822,
                                                               0.0982871,
                                                               0.087661,
                                                               0.0815639,
                                                               0.0674708],
                                       'buildgetnbrkdt': [0.808488,
                                                          0.196302,
                                                          0.105097,
                                                          0.057719,
                                                          0.0517728,
                                                          0.0332289,
                                                          0.0495341],
                                       'clustercoretime': [2.81219,
                                                           1.3516,
                                                           0.588324,
                                                           0.389126,
                                                           0.326525,
                                                           0.20079,
                                                           0.203023],
                                       'config-id': '0221-synt4',
                                       'configuration': 'approx-bucketing-qt-real: '
                                                        'kdt scans bothsides, '
                                                        'jemalloc, bucketing '
                                                        'on, array kdt, long '
                                                        'variable type in '
                                                        'general, double '
                                                        'datatype',
                                       'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                       'dataset': '7D_HouseHold_2M.pbbs',
                                       'dim': {7.0},
                                       'dimname': '7D_HouseHold_',
                                       'eps': {2000.0},
                                       'machine': 'aws-c5.18x',
                                       'markcoretime': [98.8129,
                                                        26.0096,
                                                        13.101,
                                                        6.7465,
                                                        4.90625,
                                                        3.411,
                                                        3.19576],
                                       'minpts': {100.0},
                                       'ndalgo': {'nd'},
                                       'numborder': [108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0],
                                       'numclusterpts': [1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0],
                                       'numclusters': [27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0],
                                       'numcore': [1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0],
                                       'numgrids': [613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0],
                                       'numnoise': [327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0],
                                       'numprocs': {1.0,
                                                    4.0,
                                                    8.0,
                                                    16.0,
                                                    24.0,
                                                    36.0,
                                                    72.0},
                                       'numpts': [2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0],
                                       'numpts_attr': {2049280.0},
                                       'rho': {0.01},
                                       'rounds': {3.0},
                                       'serialalgo': {'parallel'},
                                       'testcount': 7,
                                       'totaltime': [107.777,
                                                     29.3452,
                                                     14.7045,
                                                     7.75853,
                                                     5.67459,
                                                     3.9405,
                                                     3.72409],
                                       'variable': 'numprocs',
                                       'x': [1.0,
                                             4.0,
                                             8.0,
                                             16.0,
                                             24.0,
                                             36.0,
                                             72.0]}},
 'numptsPlots': {},
 'rhoPlots': {'3D_GeoLife_24M': {'algo': {'approx'},
                                 'assignbordertime': [0.00486398],
                                 'assigngridtime': [0.1727],
                                 'buildcoreptquadtree': [0.363942],
                                 'buildgetnbrkdt': [0.00158095],
                                 'clustercoretime': [0.105679],
                                 'config-id': '0221-synt4',
                                 'configuration': 'approx-bucketing-qt-real: '
                                                  'kdt scans bothsides, '
                                                  'jemalloc, bucketing on, '
                                                  'array kdt, long variable '
                                                  'type in general, double '
                                                  'datatype',
                                 'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                 'dataset': '3D_GeoLife_24M.pbbs',
                                 'dim': {3.0},
                                 'dimname': '3D_GeoLife_',
                                 'eps': {40.0},
                                 'machine': 'aws-c5.18x',
                                 'markcoretime': [0.38973],
                                 'minpts': {100.0},
                                 'ndalgo': {'nd'},
                                 'numborder': [3792.0],
                                 'numclusterpts': [24859769.0],
                                 'numclusters': [63.0],
                                 'numcore': [24855826.0],
                                 'numgrids': [9684.0],
                                 'numnoise': [17360.0],
                                 'numprocs': {72.0},
                                 'numpts': [24876978.0],
                                 'numpts_attr': {24876978.0},
                                 'rho': {0.01},
                                 'rounds': {3.0},
                                 'serialalgo': {'parallel'},
                                 'testcount': 1,
                                 'totaltime': [1.03874],
                                 'variable': 'rho',
                                 'x': [0.01]},
              '7D_HouseHold_2M': {'algo': {'approx'},
                                  'assignbordertime': [0.144404],
                                  'assigngridtime': [0.0440729],
                                  'buildcoreptquadtree': [0.0674708],
                                  'buildgetnbrkdt': [0.0495341],
                                  'clustercoretime': [0.203023],
                                  'config-id': '0221-synt4',
                                  'configuration': 'approx-bucketing-qt-real: '
                                                   'kdt scans bothsides, '
                                                   'jemalloc, bucketing on, '
                                                   'array kdt, long variable '
                                                   'type in general, double '
                                                   'datatype',
                                  'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                  'dataset': '7D_HouseHold_2M.pbbs',
                                  'dim': {7.0},
                                  'dimname': '7D_HouseHold_',
                                  'eps': {2000.0},
                                  'machine': 'aws-c5.18x',
                                  'markcoretime': [3.19576],
                                  'minpts': {100.0},
                                  'ndalgo': {'nd'},
                                  'numborder': [108607.0],
                                  'numclusterpts': [1721856.0],
                                  'numclusters': [27.0],
                                  'numcore': [1613187.0],
                                  'numgrids': [613546.0],
                                  'numnoise': [327486.0],
                                  'numprocs': {72.0},
                                  'numpts': [2049280.0],
                                  'numpts_attr': {2049280.0},
                                  'rho': {0.01},
                                  'rounds': {3.0},
                                  'serialalgo': {'parallel'},
                                  'testcount': 1,
                                  'totaltime': [3.72409],
                                  'variable': 'rho',
                                  'x': [0.01]}}}