plotData = {'epsPlots': {'3D_GeoLife_24M': {'algo': set(),
                                 'assignbordertime': [],
                                 'assigngridtime': [],
                                 'buildcoreptquadtree': [],
                                 'buildgetnbrkdt': [],
                                 'clustercoretime': [],
                                 'config-id': '07-11-real2',
                                 'configuration': 'pdsdbscan/hpdbscan testing '
                                                  'on small real datasets',
                                 'datafile': set(),
                                 'dataset': '3D_GeoLife_24M.pbbs',
                                 'dim': set(),
                                 'dimname': None,
                                 'eps': set(),
                                 'machine': 'aws-c5.18x',
                                 'markcoretime': [],
                                 'minpts': set(),
                                 'ndalgo': set(),
                                 'numborder': [],
                                 'numclusterpts': [],
                                 'numclusters': [],
                                 'numcore': [],
                                 'numgrids': [],
                                 'numnoise': [],
                                 'numprocs': set(),
                                 'numpts': [],
                                 'numpts_attr': set(),
                                 'rho': set(),
                                 'rounds': set(),
                                 'serialalgo': set(),
                                 'testcount': 0,
                                 'totaltime': [],
                                 'variable': 'eps',
                                 'x': []},
              '7D_HouseHold_2M': {'algo': {'pdsdbscan'},
                                  'assignbordertime': [None,
                                                       None,
                                                       None,
                                                       None,
                                                       None,
                                                       None],
                                  'assigngridtime': [None,
                                                     None,
                                                     None,
                                                     None,
                                                     None,
                                                     None],
                                  'buildcoreptquadtree': [None,
                                                          None,
                                                          None,
                                                          None,
                                                          None,
                                                          None],
                                  'buildgetnbrkdt': [None,
                                                     None,
                                                     None,
                                                     None,
                                                     None,
                                                     None],
                                  'clustercoretime': [None,
                                                      None,
                                                      None,
                                                      None,
                                                      None,
                                                      None],
                                  'config-id': '07-11-real2',
                                  'configuration': 'pdsdbscan/hpdbscan testing '
                                                   'on small real datasets',
                                  'datafile': {'7D_HouseHold_2M'},
                                  'dataset': '7D_HouseHold_2M.pbbs',
                                  'dim': {None},
                                  'dimname': '7D_HouseHold_',
                                  'eps': {1000.0,
                                          1400.0,
                                          1800.0,
                                          2200.0,
                                          2600.0,
                                          3000.0},
                                  'machine': 'aws-c5.18x',
                                  'markcoretime': [None,
                                                   None,
                                                   None,
                                                   None,
                                                   None,
                                                   None],
                                  'minpts': {100.0},
                                  'ndalgo': {'nd'},
                                  'numborder': [None,
                                                None,
                                                None,
                                                None,
                                                None,
                                                None],
                                  'numclusterpts': [None,
                                                    None,
                                                    None,
                                                    None,
                                                    None,
                                                    None],
                                  'numclusters': [None,
                                                  None,
                                                  None,
                                                  None,
                                                  None,
                                                  None],
                                  'numcore': [None,
                                              None,
                                              None,
                                              None,
                                              None,
                                              None],
                                  'numgrids': [None,
                                               None,
                                               None,
                                               None,
                                               None,
                                               None],
                                  'numnoise': [None,
                                               None,
                                               None,
                                               None,
                                               None,
                                               None],
                                  'numprocs': {72.0},
                                  'numpts': [2000000,
                                             2000000,
                                             2000000,
                                             2000000,
                                             2000000,
                                             2000000],
                                  'numpts_attr': {2000000},
                                  'rho': {None},
                                  'rounds': {None},
                                  'serialalgo': {'parallel'},
                                  'testcount': 6,
                                  'totaltime': [13.84735,
                                                26.968099000000002,
                                                46.185112000000004,
                                                70.65986,
                                                105.831635,
                                                146.631156],
                                  'variable': 'eps',
                                  'x': [1000.0,
                                        1400.0,
                                        1800.0,
                                        2200.0,
                                        2600.0,
                                        3000.0]}},
 'minptsPlots': {'3D_GeoLife_24M': {'algo': set(),
                                    'assignbordertime': [],
                                    'assigngridtime': [],
                                    'buildcoreptquadtree': [],
                                    'buildgetnbrkdt': [],
                                    'clustercoretime': [],
                                    'config-id': '07-11-real2',
                                    'configuration': 'pdsdbscan/hpdbscan '
                                                     'testing on small real '
                                                     'datasets',
                                    'datafile': set(),
                                    'dataset': '3D_GeoLife_24M.pbbs',
                                    'dim': set(),
                                    'dimname': None,
                                    'eps': set(),
                                    'machine': 'aws-c5.18x',
                                    'markcoretime': [],
                                    'minpts': set(),
                                    'ndalgo': set(),
                                    'numborder': [],
                                    'numclusterpts': [],
                                    'numclusters': [],
                                    'numcore': [],
                                    'numgrids': [],
                                    'numnoise': [],
                                    'numprocs': set(),
                                    'numpts': [],
                                    'numpts_attr': set(),
                                    'rho': set(),
                                    'rounds': set(),
                                    'serialalgo': set(),
                                    'testcount': 0,
                                    'totaltime': [],
                                    'variable': 'minpts',
                                    'x': []},
                 '7D_HouseHold_2M': {'algo': {'pdsdbscan'},
                                     'assignbordertime': [None,
                                                          None,
                                                          None,
                                                          None,
                                                          None,
                                                          None],
                                     'assigngridtime': [None,
                                                        None,
                                                        None,
                                                        None,
                                                        None,
                                                        None],
                                     'buildcoreptquadtree': [None,
                                                             None,
                                                             None,
                                                             None,
                                                             None,
                                                             None],
                                     'buildgetnbrkdt': [None,
                                                        None,
                                                        None,
                                                        None,
                                                        None,
                                                        None],
                                     'clustercoretime': [None,
                                                         None,
                                                         None,
                                                         None,
                                                         None,
                                                         None],
                                     'config-id': '07-11-real2',
                                     'configuration': 'pdsdbscan/hpdbscan '
                                                      'testing on small real '
                                                      'datasets',
                                     'datafile': {'7D_HouseHold_2M'},
                                     'dataset': '7D_HouseHold_2M.pbbs',
                                     'dim': {None},
                                     'dimname': '7D_HouseHold_',
                                     'eps': {2000.0},
                                     'machine': 'aws-c5.18x',
                                     'markcoretime': [None,
                                                      None,
                                                      None,
                                                      None,
                                                      None,
                                                      None],
                                     'minpts': {10.0,
                                                100.0,
                                                500.0,
                                                1000.0,
                                                5000.0,
                                                10000.0},
                                     'ndalgo': {'nd'},
                                     'numborder': [None,
                                                   None,
                                                   None,
                                                   None,
                                                   None,
                                                   None],
                                     'numclusterpts': [None,
                                                       None,
                                                       None,
                                                       None,
                                                       None,
                                                       None],
                                     'numclusters': [None,
                                                     None,
                                                     None,
                                                     None,
                                                     None,
                                                     None],
                                     'numcore': [None,
                                                 None,
                                                 None,
                                                 None,
                                                 None,
                                                 None],
                                     'numgrids': [None,
                                                  None,
                                                  None,
                                                  None,
                                                  None,
                                                  None],
                                     'numnoise': [None,
                                                  None,
                                                  None,
                                                  None,
                                                  None,
                                                  None],
                                     'numprocs': {72.0},
                                     'numpts': [2000000,
                                                2000000,
                                                2000000,
                                                2000000,
                                                2000000,
                                                2000000],
                                     'numpts_attr': {2000000},
                                     'rho': {None},
                                     'rounds': {None},
                                     'serialalgo': {'parallel'},
                                     'testcount': 6,
                                     'totaltime': [57.091716,
                                                   56.422128,
                                                   56.894437,
                                                   56.549943,
                                                   54.02677,
                                                   53.786347],
                                     'variable': 'minpts',
                                     'x': [10.0,
                                           100.0,
                                           500.0,
                                           1000.0,
                                           5000.0,
                                           10000.0]}},
 'numprocsPlots': {'3D_GeoLife_24M': {'algo': set(),
                                      'assignbordertime': [],
                                      'assigngridtime': [],
                                      'buildcoreptquadtree': [],
                                      'buildgetnbrkdt': [],
                                      'clustercoretime': [],
                                      'config-id': '07-11-real2',
                                      'configuration': 'pdsdbscan/hpdbscan '
                                                       'testing on small real '
                                                       'datasets',
                                      'datafile': set(),
                                      'dataset': '3D_GeoLife_24M.pbbs',
                                      'dim': set(),
                                      'dimname': None,
                                      'eps': set(),
                                      'machine': 'aws-c5.18x',
                                      'markcoretime': [],
                                      'minpts': set(),
                                      'ndalgo': set(),
                                      'numborder': [],
                                      'numclusterpts': [],
                                      'numclusters': [],
                                      'numcore': [],
                                      'numgrids': [],
                                      'numnoise': [],
                                      'numprocs': set(),
                                      'numpts': [],
                                      'numpts_attr': set(),
                                      'rho': set(),
                                      'rounds': set(),
                                      'serialalgo': set(),
                                      'testcount': 0,
                                      'totaltime': [],
                                      'variable': 'numprocs',
                                      'x': []},
                   '7D_HouseHold_2M': {'algo': {'pdsdbscan'},
                                       'assignbordertime': [None,
                                                            None,
                                                            None,
                                                            None,
                                                            None,
                                                            None,
                                                            None],
                                       'assigngridtime': [None,
                                                          None,
                                                          None,
                                                          None,
                                                          None,
                                                          None,
                                                          None],
                                       'buildcoreptquadtree': [None,
                                                               None,
                                                               None,
                                                               None,
                                                               None,
                                                               None,
                                                               None],
                                       'buildgetnbrkdt': [None,
                                                          None,
                                                          None,
                                                          None,
                                                          None,
                                                          None,
                                                          None],
                                       'clustercoretime': [None,
                                                           None,
                                                           None,
                                                           None,
                                                           None,
                                                           None,
                                                           None],
                                       'config-id': '07-11-real2',
                                       'configuration': 'pdsdbscan/hpdbscan '
                                                        'testing on small real '
                                                        'datasets',
                                       'datafile': {'7D_HouseHold_2M'},
                                       'dataset': '7D_HouseHold_2M.pbbs',
                                       'dim': {None},
                                       'dimname': '7D_HouseHold_',
                                       'eps': {2000.0},
                                       'machine': 'aws-c5.18x',
                                       'markcoretime': [None,
                                                        None,
                                                        None,
                                                        None,
                                                        None,
                                                        None,
                                                        None],
                                       'minpts': {100.0},
                                       'ndalgo': {'nd'},
                                       'numborder': [None,
                                                     None,
                                                     None,
                                                     None,
                                                     None,
                                                     None,
                                                     None],
                                       'numclusterpts': [None,
                                                         None,
                                                         None,
                                                         None,
                                                         None,
                                                         None,
                                                         None],
                                       'numclusters': [None,
                                                       None,
                                                       None,
                                                       None,
                                                       None,
                                                       None,
                                                       None],
                                       'numcore': [None,
                                                   None,
                                                   None,
                                                   None,
                                                   None,
                                                   None,
                                                   None],
                                       'numgrids': [None,
                                                    None,
                                                    None,
                                                    None,
                                                    None,
                                                    None,
                                                    None],
                                       'numnoise': [None,
                                                    None,
                                                    None,
                                                    None,
                                                    None,
                                                    None,
                                                    None],
                                       'numprocs': {1.0,
                                                    4.0,
                                                    8.0,
                                                    16.0,
                                                    24.0,
                                                    36.0,
                                                    72.0},
                                       'numpts': [2000000,
                                                  2000000,
                                                  2000000,
                                                  2000000,
                                                  2000000,
                                                  2000000,
                                                  2000000],
                                       'numpts_attr': {2000000},
                                       'rho': {None},
                                       'rounds': {None},
                                       'serialalgo': {'parallel'},
                                       'testcount': 7,
                                       'totaltime': [520.298364,
                                                     301.346695,
                                                     173.757484,
                                                     101.642321,
                                                     108.915999,
                                                     78.370104,
                                                     56.422128],
                                       'variable': 'numprocs',
                                       'x': [1.0,
                                             4.0,
                                             8.0,
                                             16.0,
                                             24.0,
                                             36.0,
                                             72.0]}},
 'numptsPlots': {}}