plotData = {'epsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                 'assignbordertime': [0.0245428,
                                                      0.00401497,
                                                      0.00881386,
                                                      0.0017519],
                                 'assigngridtime': [0.195932,
                                                    0.4195,
                                                    0.189792,
                                                    0.199164],
                                 'buildcoreptquadtree': [0.375248,
                                                         0.363031,
                                                         0.342466,
                                                         0.35306],
                                 'buildgetnbrkdt': [0.00251412,
                                                    0.00417399,
                                                    0.000972033,
                                                    0.000929832],
                                 'clustercoretime': [0.11496,
                                                     0.0202491,
                                                     0.165313,
                                                     0.16247],
                                 'config-id': '1113-real4',
                                 'configuration': 'scanmc_quadtreebcp: kdt '
                                                  'scans bothsides, jemalloc, '
                                                  'no bucketing, array kdt, '
                                                  'long variable type for real '
                                                  'datasets, double datatype, '
                                                  'commit:',
                                 'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                 'dataset': '3D_GeoLife_24M.pbbs',
                                 'dim': {3.0},
                                 'dimname': '3D_GeoLife_',
                                 'eps': {40.0, 80.0, 20.0, 160.0},
                                 'machine': 'aws-c5.18x',
                                 'markcoretime': [0.0243208,
                                                  0.015384,
                                                  0.091373,
                                                  0.00837803],
                                 'minpts': {100.0},
                                 'ndalgo': {'nd'},
                                 'numborder': [7391.0, 3791.0, 3572.0, 990.0],
                                 'numclusterpts': [24846295.0,
                                                   24859769.0,
                                                   24868067.0,
                                                   24873703.0],
                                 'numclusters': [91.0, 63.0, 56.0, 24.0],
                                 'numcore': [24838633.0,
                                             24855827.0,
                                             24864335.0,
                                             24872696.0],
                                 'numgrids': [22919.0, 9684.0, 3612.0, 1694.0],
                                 'numnoise': [30954.0, 17360.0, 9071.0, 3292.0],
                                 'numprocs': {72.0},
                                 'numpts': [24876978.0,
                                            24876978.0,
                                            24876978.0,
                                            24876978.0],
                                 'numpts_attr': {24876978.0},
                                 'rho': {0.01},
                                 'rounds': {3.0},
                                 'serialalgo': {'parallel'},
                                 'testcount': 4,
                                 'totaltime': [0.738152,
                                               0.826598,
                                               0.798997,
                                               0.72606],
                                 'variable': 'eps',
                                 'x': [20.0, 40.0, 80.0, 160.0]},
              '7D_HouseHold_2M': {'algo': {'exact'},
                                  'assignbordertime': [0.14888,
                                                       0.0906401,
                                                       0.138425,
                                                       0.207471,
                                                       0.226828,
                                                       0.249228],
                                  'assigngridtime': [0.0412121,
                                                     0.037535,
                                                     0.0420818,
                                                     0.033886,
                                                     0.05688,
                                                     0.032553],
                                  'buildcoreptquadtree': [0.041995,
                                                          0.0464439,
                                                          0.051553,
                                                          0.046387,
                                                          0.034761,
                                                          0.044107],
                                  'buildgetnbrkdt': [0.154342,
                                                     0.0794649,
                                                     0.0466301,
                                                     0.043025,
                                                     0.0239682,
                                                     0.0219221],
                                  'clustercoretime': [0.23795,
                                                      0.17542,
                                                      0.215896,
                                                      0.655304,
                                                      1.05644,
                                                      4.59922],
                                  'config-id': '1113-real4',
                                  'configuration': 'scanmc_quadtreebcp: kdt '
                                                   'scans bothsides, jemalloc, '
                                                   'no bucketing, array kdt, '
                                                   'long variable type for '
                                                   'real datasets, double '
                                                   'datatype, commit:',
                                  'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                  'dataset': '7D_HouseHold_2M.pbbs',
                                  'dim': {7.0},
                                  'dimname': '7D_HouseHold_',
                                  'eps': {1000.0,
                                          1400.0,
                                          1800.0,
                                          2200.0,
                                          2600.0,
                                          3000.0},
                                  'machine': 'aws-c5.18x',
                                  'markcoretime': [2.4133,
                                                   2.91876,
                                                   4.15873,
                                                   8.32149,
                                                   9.15096,
                                                   9.95864],
                                  'minpts': {100.0},
                                  'ndalgo': {'nd'},
                                  'numborder': [123077.0,
                                                148926.0,
                                                121447.0,
                                                97189.0,
                                                76854.0,
                                                64485.0],
                                  'numclusterpts': [1220205.0,
                                                    1507976.0,
                                                    1668837.0,
                                                    1760132.0,
                                                    1815454.0,
                                                    1855854.0],
                                  'numclusters': [55.0,
                                                  30.0,
                                                  27.0,
                                                  30.0,
                                                  38.0,
                                                  48.0],
                                  'numcore': [1096868.0,
                                              1358900.0,
                                              1547291.0,
                                              1662856.0,
                                              1738555.0,
                                              1791293.0],
                                  'numgrids': [987740.0,
                                               796144.0,
                                               664053.0,
                                               570752.0,
                                               498785.0,
                                               442979.0],
                                  'numnoise': [829335.0,
                                               541454.0,
                                               380542.0,
                                               289235.0,
                                               233871.0,
                                               193502.0],
                                  'numprocs': {72.0},
                                  'numpts': [2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0],
                                  'numpts_attr': {2049280.0},
                                  'rho': {0.01},
                                  'rounds': {3.0},
                                  'serialalgo': {'parallel'},
                                  'testcount': 6,
                                  'totaltime': [3.05169,
                                                3.36357,
                                                4.70048,
                                                9.39899,
                                                10.6093,
                                                14.9909],
                                  'variable': 'eps',
                                  'x': [1000.0,
                                        1400.0,
                                        1800.0,
                                        2200.0,
                                        2600.0,
                                        3000.0]}},
 'minptsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                    'assignbordertime': [0.0629702,
                                                         0.00401497,
                                                         0.00400209,
                                                         0.00925493,
                                                         0.107626,
                                                         0.196326],
                                    'assigngridtime': [0.193578,
                                                       0.4195,
                                                       0.199738,
                                                       0.371162,
                                                       0.172085,
                                                       0.177548],
                                    'buildcoreptquadtree': [0.36526,
                                                            0.363031,
                                                            0.371352,
                                                            0.376012,
                                                            0.412966,
                                                            0.310499],
                                    'buildgetnbrkdt': [0.00179315,
                                                       0.00417399,
                                                       0.00167394,
                                                       0.00160503,
                                                       0.00205708,
                                                       0.00168681],
                                    'clustercoretime': [0.218596,
                                                        0.0202491,
                                                        0.06428,
                                                        0.061805,
                                                        0.0323608,
                                                        0.0680912],
                                    'config-id': '1113-real4',
                                    'configuration': 'scanmc_quadtreebcp: kdt '
                                                     'scans bothsides, '
                                                     'jemalloc, no bucketing, '
                                                     'array kdt, long variable '
                                                     'type for real datasets, '
                                                     'double datatype, commit:',
                                    'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                    'dataset': '3D_GeoLife_24M.pbbs',
                                    'dim': {3.0},
                                    'dimname': '3D_GeoLife_',
                                    'eps': {40.0},
                                    'machine': 'aws-c5.18x',
                                    'markcoretime': [0.013195,
                                                     0.015384,
                                                     0.042064,
                                                     0.118416,
                                                     0.871638,
                                                     2.44943],
                                    'minpts': {10.0,
                                               100.0,
                                               500.0,
                                               1000.0,
                                               5000.0,
                                               10000.0},
                                    'ndalgo': {'nd'},
                                    'numborder': [320.0,
                                                  3791.0,
                                                  8860.0,
                                                  17546.0,
                                                  100090.0,
                                                  91985.0],
                                    'numclusterpts': [24875629.0,
                                                      24859769.0,
                                                      24824591.0,
                                                      24795161.0,
                                                      24501634.0,
                                                      24141423.0],
                                    'numclusters': [84.0,
                                                    63.0,
                                                    26.0,
                                                    21.0,
                                                    19.0,
                                                    8.0],
                                    'numcore': [24875293.0,
                                                24855827.0,
                                                24815481.0,
                                                24776376.0,
                                                24400085.0,
                                                24049438.0],
                                    'numgrids': [9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0],
                                    'numnoise': [1365.0,
                                                 17360.0,
                                                 52637.0,
                                                 83056.0,
                                                 376803.0,
                                                 735555.0],
                                    'numprocs': {72.0},
                                    'numpts': [24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0],
                                    'numpts_attr': {24876978.0},
                                    'rho': {0.01},
                                    'rounds': {3.0},
                                    'serialalgo': {'parallel'},
                                    'testcount': 6,
                                    'totaltime': [0.855763,
                                                  0.826598,
                                                  0.683396,
                                                  0.938588,
                                                  1.59909,
                                                  3.20382],
                                    'variable': 'minpts',
                                    'x': [10.0,
                                          100.0,
                                          500.0,
                                          1000.0,
                                          5000.0,
                                          10000.0]},
                 '7D_HouseHold_2M': {'algo': {'exact'},
                                     'assignbordertime': [0.0194671,
                                                          0.138813,
                                                          0.463562,
                                                          0.806701,
                                                          2.52986,
                                                          2.06505],
                                     'assigngridtime': [0.040704,
                                                        0.0553391,
                                                        0.0431039,
                                                        0.0338449,
                                                        0.0347121,
                                                        0.0362401],
                                     'buildcoreptquadtree': [0.0423951,
                                                             0.0405049,
                                                             0.0437799,
                                                             0.0245581,
                                                             0.01403,
                                                             0.012989],
                                     'buildgetnbrkdt': [0.0360291,
                                                        0.0417531,
                                                        0.0454891,
                                                        0.037096,
                                                        0.037014,
                                                        0.041847],
                                     'clustercoretime': [0.446846,
                                                         0.213051,
                                                         0.091743,
                                                         0.0629799,
                                                         0.0151999,
                                                         0.0359221],
                                     'config-id': '1113-real4',
                                     'configuration': 'scanmc_quadtreebcp: kdt '
                                                      'scans bothsides, '
                                                      'jemalloc, no bucketing, '
                                                      'array kdt, long '
                                                      'variable type for real '
                                                      'datasets, double '
                                                      'datatype, commit:',
                                     'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                     'dataset': '7D_HouseHold_2M.pbbs',
                                     'dim': {7.0},
                                     'dimname': '7D_HouseHold_',
                                     'eps': {2000.0},
                                     'machine': 'aws-c5.18x',
                                     'markcoretime': [2.50947,
                                                      3.71088,
                                                      6.23694,
                                                      7.3643,
                                                      13.5138,
                                                      15.434],
                                     'minpts': {10.0,
                                                100.0,
                                                500.0,
                                                1000.0,
                                                5000.0,
                                                10000.0},
                                     'ndalgo': {'nd'},
                                     'numborder': [42452.0,
                                                   108607.0,
                                                   174591.0,
                                                   209145.0,
                                                   318927.0,
                                                   233083.0],
                                     'numclusterpts': [1910253.0,
                                                       1721856.0,
                                                       1462453.0,
                                                       1319491.0,
                                                       874953.0,
                                                       514766.0],
                                     'numclusters': [599.0,
                                                     27.0,
                                                     13.0,
                                                     13.0,
                                                     8.0,
                                                     4.0],
                                     'numcore': [1867325.0,
                                                 1613187.0,
                                                 1287762.0,
                                                 1109405.0,
                                                 555715.0,
                                                 281683.0],
                                     'numgrids': [613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0],
                                     'numnoise': [139503.0,
                                                  327486.0,
                                                  586927.0,
                                                  730730.0,
                                                  1174638.0,
                                                  1534514.0],
                                     'numprocs': {72.0},
                                     'numpts': [2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0],
                                     'numpts_attr': {2049280.0},
                                     'rho': {0.01},
                                     'rounds': {3.0},
                                     'serialalgo': {'parallel'},
                                     'testcount': 6,
                                     'totaltime': [3.11289,
                                                   4.22365,
                                                   6.95998,
                                                   8.38779,
                                                   16.2047,
                                                   17.7096],
                                     'variable': 'minpts',
                                     'x': [10.0,
                                           100.0,
                                           500.0,
                                           1000.0,
                                           5000.0,
                                           10000.0]}},
 'numprocsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                      'assignbordertime': [0.0101731,
                                                           0.00506496,
                                                           0.0049479,
                                                           0.00294399,
                                                           0.00253487,
                                                           0.00281978,
                                                           0.00401497],
                                      'assigngridtime': [1.63253,
                                                         0.600383,
                                                         0.291141,
                                                         0.196673,
                                                         0.378475,
                                                         0.349796,
                                                         0.4195],
                                      'buildcoreptquadtree': [7.01639,
                                                              2.56795,
                                                              1.51371,
                                                              0.821596,
                                                              0.629992,
                                                              0.45844,
                                                              0.363031],
                                      'buildgetnbrkdt': [0.00230885,
                                                         0.00128007,
                                                         0.00116587,
                                                         0.0010798,
                                                         0.00140905,
                                                         0.00450897,
                                                         0.00417399],
                                      'clustercoretime': [0.174908,
                                                          0.070869,
                                                          0.060374,
                                                          0.0426698,
                                                          0.01985,
                                                          0.019232,
                                                          0.0202491],
                                      'config-id': '1113-real4',
                                      'configuration': 'scanmc_quadtreebcp: '
                                                       'kdt scans bothsides, '
                                                       'jemalloc, no '
                                                       'bucketing, array kdt, '
                                                       'long variable type for '
                                                       'real datasets, double '
                                                       'datatype, commit:',
                                      'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                      'dataset': '3D_GeoLife_24M.pbbs',
                                      'dim': {3.0},
                                      'dimname': '3D_GeoLife_',
                                      'eps': {40.0},
                                      'machine': 'aws-c5.18x',
                                      'markcoretime': [0.25752,
                                                       0.0739601,
                                                       0.0380132,
                                                       0.0209401,
                                                       0.0154121,
                                                       0.0142779,
                                                       0.015384],
                                      'minpts': {100.0},
                                      'ndalgo': {'nd'},
                                      'numborder': [3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0],
                                      'numclusterpts': [24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0],
                                      'numclusters': [63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0],
                                      'numcore': [24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0],
                                      'numgrids': [9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0],
                                      'numnoise': [17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0],
                                      'numprocs': {1.0,
                                                   4.0,
                                                   8.0,
                                                   16.0,
                                                   24.0,
                                                   36.0,
                                                   72.0},
                                      'numpts': [24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0],
                                      'numpts_attr': {24876978.0},
                                      'rho': {0.01},
                                      'rounds': {3.0},
                                      'serialalgo': {'parallel'},
                                      'testcount': 7,
                                      'totaltime': [9.09421,
                                                    3.31992,
                                                    1.90987,
                                                    1.08626,
                                                    1.04785,
                                                    0.849325,
                                                    0.826598],
                                      'variable': 'numprocs',
                                      'x': [1.0,
                                            4.0,
                                            8.0,
                                            16.0,
                                            24.0,
                                            36.0,
                                            72.0]},
                   '7D_HouseHold_2M': {'algo': {'exact'},
                                       'assignbordertime': [3.3265,
                                                            1.19108,
                                                            0.5342,
                                                            0.292739,
                                                            0.210366,
                                                            0.148589,
                                                            0.138813],
                                       'assigngridtime': [0.830173,
                                                          0.264133,
                                                          0.130087,
                                                          0.0741889,
                                                          0.0534751,
                                                          0.0419331,
                                                          0.0553391],
                                       'buildcoreptquadtree': [0.544511,
                                                               0.360016,
                                                               0.126689,
                                                               0.064595,
                                                               0.0503888,
                                                               0.047343,
                                                               0.0405049],
                                       'buildgetnbrkdt': [0.703175,
                                                          0.224099,
                                                          0.102777,
                                                          0.059212,
                                                          0.04774,
                                                          0.034158,
                                                          0.0417531],
                                       'clustercoretime': [5.83561,
                                                           1.86433,
                                                           0.638879,
                                                           0.365945,
                                                           0.328543,
                                                           0.233909,
                                                           0.213051],
                                       'config-id': '1113-real4',
                                       'configuration': 'scanmc_quadtreebcp: '
                                                        'kdt scans bothsides, '
                                                        'jemalloc, no '
                                                        'bucketing, array kdt, '
                                                        'long variable type '
                                                        'for real datasets, '
                                                        'double datatype, '
                                                        'commit:',
                                       'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                       'dataset': '7D_HouseHold_2M.pbbs',
                                       'dim': {7.0},
                                       'dimname': '7D_HouseHold_',
                                       'eps': {2000.0},
                                       'machine': 'aws-c5.18x',
                                       'markcoretime': [102.334,
                                                        26.05,
                                                        13.3938,
                                                        7.33302,
                                                        5.5594,
                                                        4.10125,
                                                        3.71088],
                                       'minpts': {100.0},
                                       'ndalgo': {'nd'},
                                       'numborder': [108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0],
                                       'numclusterpts': [1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0],
                                       'numclusters': [27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0],
                                       'numcore': [1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0],
                                       'numgrids': [613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0],
                                       'numnoise': [327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0],
                                       'numprocs': {1.0,
                                                    4.0,
                                                    8.0,
                                                    16.0,
                                                    24.0,
                                                    36.0,
                                                    72.0},
                                       'numpts': [2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0],
                                       'numpts_attr': {2049280.0},
                                       'rho': {0.01},
                                       'rounds': {3.0},
                                       'serialalgo': {'parallel'},
                                       'testcount': 7,
                                       'totaltime': [113.645,
                                                     30.0961,
                                                     15.0193,
                                                     8.24329,
                                                     6.2926,
                                                     4.63799,
                                                     4.22365],
                                       'variable': 'numprocs',
                                       'x': [1.0,
                                             4.0,
                                             8.0,
                                             16.0,
                                             24.0,
                                             36.0,
                                             72.0]}},
 'numptsPlots': {},
 'rhoPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                 'assignbordertime': [0.00401497],
                                 'assigngridtime': [0.4195],
                                 'buildcoreptquadtree': [0.363031],
                                 'buildgetnbrkdt': [0.00417399],
                                 'clustercoretime': [0.0202491],
                                 'config-id': '1113-real4',
                                 'configuration': 'scanmc_quadtreebcp: kdt '
                                                  'scans bothsides, jemalloc, '
                                                  'no bucketing, array kdt, '
                                                  'long variable type for real '
                                                  'datasets, double datatype, '
                                                  'commit:',
                                 'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                 'dataset': '3D_GeoLife_24M.pbbs',
                                 'dim': {3.0},
                                 'dimname': '3D_GeoLife_',
                                 'eps': {40.0},
                                 'machine': 'aws-c5.18x',
                                 'markcoretime': [0.015384],
                                 'minpts': {100.0},
                                 'ndalgo': {'nd'},
                                 'numborder': [3791.0],
                                 'numclusterpts': [24859769.0],
                                 'numclusters': [63.0],
                                 'numcore': [24855827.0],
                                 'numgrids': [9684.0],
                                 'numnoise': [17360.0],
                                 'numprocs': {72.0},
                                 'numpts': [24876978.0],
                                 'numpts_attr': {24876978.0},
                                 'rho': {0.01},
                                 'rounds': {3.0},
                                 'serialalgo': {'parallel'},
                                 'testcount': 1,
                                 'totaltime': [0.826598],
                                 'variable': 'rho',
                                 'x': [0.01]},
              '7D_HouseHold_2M': {'algo': {'exact'},
                                  'assignbordertime': [0.138813],
                                  'assigngridtime': [0.0553391],
                                  'buildcoreptquadtree': [0.0405049],
                                  'buildgetnbrkdt': [0.0417531],
                                  'clustercoretime': [0.213051],
                                  'config-id': '1113-real4',
                                  'configuration': 'scanmc_quadtreebcp: kdt '
                                                   'scans bothsides, jemalloc, '
                                                   'no bucketing, array kdt, '
                                                   'long variable type for '
                                                   'real datasets, double '
                                                   'datatype, commit:',
                                  'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                  'dataset': '7D_HouseHold_2M.pbbs',
                                  'dim': {7.0},
                                  'dimname': '7D_HouseHold_',
                                  'eps': {2000.0},
                                  'machine': 'aws-c5.18x',
                                  'markcoretime': [3.71088],
                                  'minpts': {100.0},
                                  'ndalgo': {'nd'},
                                  'numborder': [108607.0],
                                  'numclusterpts': [1721856.0],
                                  'numclusters': [27.0],
                                  'numcore': [1613187.0],
                                  'numgrids': [613546.0],
                                  'numnoise': [327486.0],
                                  'numprocs': {72.0},
                                  'numpts': [2049280.0],
                                  'numpts_attr': {2049280.0},
                                  'rho': {0.01},
                                  'rounds': {3.0},
                                  'serialalgo': {'parallel'},
                                  'testcount': 1,
                                  'totaltime': [4.22365],
                                  'variable': 'rho',
                                  'x': [0.01]}}}