plotData = {'epsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                 'assignbordertime': [0.00329995,
                                                      0.00460386,
                                                      0.00514102,
                                                      0.0307701],
                                 'assigngridtime': [0.200358,
                                                    0.189061,
                                                    0.250104,
                                                    0.141781],
                                 'buildcoreptquadtree': [-1, -1, -1, -1],
                                 'buildgetnbrkdt': [0.00183296,
                                                    0.00132799,
                                                    0.000440836,
                                                    0.000455141],
                                 'clustercoretime': [0.343492,
                                                     0.469333,
                                                     51.5703,
                                                     0.333049],
                                 'config-id': '07-04-real1-exactbcp-bucketing',
                                 'configuration': 'nd-exact-bcp: jemalloc, use '
                                                  'bucketing, array kdt, long '
                                                  'variable type, double '
                                                  'datatype, commit: '
                                                  'd5bc6b16a36be719eb8671b4ab10f51bdf1276f1',
                                 'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                 'dataset': '3D_GeoLife_24M.pbbs',
                                 'dim': {3.0},
                                 'dimname': '3D_GeoLife_',
                                 'eps': {40.0, 80.0, 20.0, 160.0},
                                 'machine': 'aws-c5.18x',
                                 'markcoretime': [0.0663381,
                                                  0.023962,
                                                  0.0969961,
                                                  0.00767803],
                                 'minpts': {100.0},
                                 'ndalgo': {'nd'},
                                 'numborder': [7391.0, 3791.0, 3572.0, 990.0],
                                 'numclusterpts': [24846295.0,
                                                   24859769.0,
                                                   24868067.0,
                                                   24873703.0],
                                 'numclusters': [91.0, 63.0, 56.0, 24.0],
                                 'numcore': [24838633.0,
                                             24855827.0,
                                             24864335.0,
                                             24872696.0],
                                 'numgrids': [22919.0, 9684.0, 3612.0, 1694.0],
                                 'numnoise': [30954.0, 17360.0, 9071.0, 3292.0],
                                 'numprocs': {72.0},
                                 'numpts': [24876978.0,
                                            24876978.0,
                                            24876978.0,
                                            24876978.0],
                                 'numpts_attr': {24876978.0},
                                 'rho': {0.01},
                                 'rounds': {3.0},
                                 'serialalgo': {'parallel'},
                                 'testcount': 4,
                                 'totaltime': [0.615796,
                                               0.688614,
                                               51.925,
                                               0.514155],
                                 'variable': 'eps',
                                 'x': [20.0, 40.0, 80.0, 160.0]},
              '7D_HouseHold_2M': {'algo': {'exact'},
                                  'assignbordertime': [4.69685e-05,
                                                       5.4121e-05,
                                                       1.3113e-05,
                                                       6.19888e-05,
                                                       5.00679e-05,
                                                       5.10216e-05],
                                  'assigngridtime': [0.022444,
                                                     0.0219619,
                                                     0.02161,
                                                     0.0217969,
                                                     0.0222292,
                                                     0.0221069],
                                  'buildcoreptquadtree': [-1,
                                                          -1,
                                                          -1,
                                                          -1,
                                                          -1,
                                                          -1],
                                  'buildgetnbrkdt': [0.000130892,
                                                     0.000130177,
                                                     3.91006e-05,
                                                     0.000132084,
                                                     0.000129938,
                                                     0.000120163],
                                  'clustercoretime': [0.000675201,
                                                      0.000644922,
                                                      0.000570774,
                                                      0.000686884,
                                                      0.000659943,
                                                      0.000751972],
                                  'config-id': '07-04-real1-exactbcp-bucketing',
                                  'configuration': 'nd-exact-bcp: jemalloc, '
                                                   'use bucketing, array kdt, '
                                                   'long variable type, double '
                                                   'datatype, commit: '
                                                   'd5bc6b16a36be719eb8671b4ab10f51bdf1276f1',
                                  'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                  'dataset': '7D_HouseHold_2M.pbbs',
                                  'dim': {7.0},
                                  'dimname': '7D_HouseHold_',
                                  'eps': {1000.0,
                                          1400.0,
                                          1800.0,
                                          2200.0,
                                          2600.0,
                                          3000.0},
                                  'machine': 'aws-c5.18x',
                                  'markcoretime': [0.000633001,
                                                   0.000568867,
                                                   0.0006001,
                                                   0.000598907,
                                                   0.000622034,
                                                   0.000568867],
                                  'minpts': {100.0},
                                  'ndalgo': {'nd'},
                                  'numborder': [1e-10,
                                                1e-10,
                                                1e-10,
                                                1e-10,
                                                1e-10,
                                                1e-10],
                                  'numclusterpts': [2049280.0,
                                                    2049280.0,
                                                    2049280.0,
                                                    2049280.0,
                                                    2049280.0,
                                                    2049280.0],
                                  'numclusters': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                                  'numcore': [2049280.0,
                                              2049280.0,
                                              2049280.0,
                                              2049280.0,
                                              2049280.0,
                                              2049280.0],
                                  'numgrids': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                                  'numnoise': [1e-10,
                                               1e-10,
                                               1e-10,
                                               1e-10,
                                               1e-10,
                                               1e-10],
                                  'numprocs': {72.0},
                                  'numpts': [2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0],
                                  'numpts_attr': {2049280.0},
                                  'rho': {0.01},
                                  'rounds': {3.0},
                                  'serialalgo': {'parallel'},
                                  'testcount': 6,
                                  'totaltime': [0.0239699,
                                                0.0234001,
                                                0.022856,
                                                0.0233011,
                                                0.023762,
                                                0.0236211],
                                  'variable': 'eps',
                                  'x': [1000.0,
                                        1400.0,
                                        1800.0,
                                        2200.0,
                                        2600.0,
                                        3000.0]}},
 'minptsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                    'assignbordertime': [0.00392008,
                                                         0.00460386,
                                                         0.00571299,
                                                         0.00914001,
                                                         0.115738,
                                                         0.194133],
                                    'assigngridtime': [0.141955,
                                                       0.189061,
                                                       0.150022,
                                                       0.143694,
                                                       0.19015,
                                                       0.189144],
                                    'buildcoreptquadtree': [-1,
                                                            -1,
                                                            -1,
                                                            -1,
                                                            -1,
                                                            -1],
                                    'buildgetnbrkdt': [0.00244021,
                                                       0.00132799,
                                                       0.00363803,
                                                       0.003263,
                                                       0.00129986,
                                                       0.00159287],
                                    'clustercoretime': [0.489192,
                                                        0.469333,
                                                        1.24492,
                                                        1.28664,
                                                        0.701532,
                                                        0.458039],
                                    'config-id': '07-04-real1-exactbcp-bucketing',
                                    'configuration': 'nd-exact-bcp: jemalloc, '
                                                     'use bucketing, array '
                                                     'kdt, long variable type, '
                                                     'double datatype, commit: '
                                                     'd5bc6b16a36be719eb8671b4ab10f51bdf1276f1',
                                    'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                    'dataset': '3D_GeoLife_24M.pbbs',
                                    'dim': {3.0},
                                    'dimname': '3D_GeoLife_',
                                    'eps': {40.0},
                                    'machine': 'aws-c5.18x',
                                    'markcoretime': [0.0150468,
                                                     0.023962,
                                                     0.051116,
                                                     0.126195,
                                                     0.969673,
                                                     2.39589],
                                    'minpts': {10.0,
                                               100.0,
                                               500.0,
                                               1000.0,
                                               5000.0,
                                               10000.0},
                                    'ndalgo': {'nd'},
                                    'numborder': [320.0,
                                                  3791.0,
                                                  8860.0,
                                                  17546.0,
                                                  100090.0,
                                                  91985.0],
                                    'numclusterpts': [24875629.0,
                                                      24859769.0,
                                                      24824591.0,
                                                      24795161.0,
                                                      24501634.0,
                                                      24141423.0],
                                    'numclusters': [84.0,
                                                    63.0,
                                                    26.0,
                                                    21.0,
                                                    19.0,
                                                    8.0],
                                    'numcore': [24875293.0,
                                                24855827.0,
                                                24815481.0,
                                                24776376.0,
                                                24400085.0,
                                                24049438.0],
                                    'numgrids': [9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0],
                                    'numnoise': [1365.0,
                                                 17360.0,
                                                 52637.0,
                                                 83056.0,
                                                 376803.0,
                                                 735555.0],
                                    'numprocs': {72.0},
                                    'numpts': [24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0],
                                    'numpts_attr': {24876978.0},
                                    'rho': {0.01},
                                    'rounds': {3.0},
                                    'serialalgo': {'parallel'},
                                    'testcount': 6,
                                    'totaltime': [0.653464,
                                                  0.688614,
                                                  1.45568,
                                                  1.56932,
                                                  1.97876,
                                                  3.23942],
                                    'variable': 'minpts',
                                    'x': [10.0,
                                          100.0,
                                          500.0,
                                          1000.0,
                                          5000.0,
                                          10000.0]},
                 '7D_HouseHold_2M': {'algo': {'exact'},
                                     'assignbordertime': [5.10216e-05,
                                                          1.21593e-05,
                                                          4.88758e-05,
                                                          5.19753e-05,
                                                          5.88894e-05,
                                                          1.78814e-05],
                                     'assigngridtime': [0.0221109,
                                                        0.0218658,
                                                        0.0222611,
                                                        0.0219438,
                                                        0.022012,
                                                        0.021734],
                                     'buildcoreptquadtree': [-1,
                                                             -1,
                                                             -1,
                                                             -1,
                                                             -1,
                                                             -1],
                                     'buildgetnbrkdt': [0.000123978,
                                                        0.000126123,
                                                        0.000198841,
                                                        0.000141144,
                                                        0.000128031,
                                                        0.000148058],
                                     'clustercoretime': [0.000619888,
                                                         0.000557899,
                                                         0.00071311,
                                                         0.000658989,
                                                         0.000736952,
                                                         0.000669956],
                                     'config-id': '07-04-real1-exactbcp-bucketing',
                                     'configuration': 'nd-exact-bcp: jemalloc, '
                                                      'use bucketing, array '
                                                      'kdt, long variable '
                                                      'type, double datatype, '
                                                      'commit: '
                                                      'd5bc6b16a36be719eb8671b4ab10f51bdf1276f1',
                                     'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                     'dataset': '7D_HouseHold_2M.pbbs',
                                     'dim': {7.0},
                                     'dimname': '7D_HouseHold_',
                                     'eps': {2000.0},
                                     'machine': 'aws-c5.18x',
                                     'markcoretime': [0.000589132,
                                                      0.000617981,
                                                      0.000643015,
                                                      0.000597,
                                                      0.000648975,
                                                      0.000569105],
                                     'minpts': {10.0,
                                                100.0,
                                                500.0,
                                                1000.0,
                                                5000.0,
                                                10000.0},
                                     'ndalgo': {'nd'},
                                     'numborder': [1e-10,
                                                   1e-10,
                                                   1e-10,
                                                   1e-10,
                                                   1e-10,
                                                   1e-10],
                                     'numclusterpts': [2049280.0,
                                                       2049280.0,
                                                       2049280.0,
                                                       2049280.0,
                                                       2049280.0,
                                                       2049280.0],
                                     'numclusters': [1.0,
                                                     1.0,
                                                     1.0,
                                                     1.0,
                                                     1.0,
                                                     1.0],
                                     'numcore': [2049280.0,
                                                 2049280.0,
                                                 2049280.0,
                                                 2049280.0,
                                                 2049280.0,
                                                 2049280.0],
                                     'numgrids': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                                     'numnoise': [1e-10,
                                                  1e-10,
                                                  1e-10,
                                                  1e-10,
                                                  1e-10,
                                                  1e-10],
                                     'numprocs': {72.0},
                                     'numpts': [2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0],
                                     'numpts_attr': {2049280.0},
                                     'rho': {0.01},
                                     'rounds': {3.0},
                                     'serialalgo': {'parallel'},
                                     'testcount': 6,
                                     'totaltime': [0.0235429,
                                                   0.023205,
                                                   0.023917,
                                                   0.023438,
                                                   0.0236111,
                                                   0.0231662],
                                     'variable': 'minpts',
                                     'x': [10.0,
                                           100.0,
                                           500.0,
                                           1000.0,
                                           5000.0,
                                           10000.0]}},
 'numprocsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                      'assignbordertime': [0.010195,
                                                           0.004951,
                                                           0.00363207,
                                                           0.0187931,
                                                           0.00234103,
                                                           0.002527,
                                                           0.00460386],
                                      'assigngridtime': [1.67598,
                                                         0.618182,
                                                         0.354313,
                                                         0.265845,
                                                         0.221226,
                                                         0.139187,
                                                         0.189061],
                                      'buildcoreptquadtree': [-1,
                                                              -1,
                                                              -1,
                                                              -1,
                                                              -1,
                                                              -1,
                                                              -1],
                                      'buildgetnbrkdt': [0.000620842,
                                                         0.00112009,
                                                         0.000918865,
                                                         0.000730991,
                                                         0.000787973,
                                                         0.00289106,
                                                         0.00132799],
                                      'clustercoretime': [1.32138,
                                                          0.672129,
                                                          0.556451,
                                                          0.380957,
                                                          0.222292,
                                                          0.27321,
                                                          0.469333],
                                      'config-id': '07-04-real1-exactbcp-bucketing',
                                      'configuration': 'nd-exact-bcp: '
                                                       'jemalloc, use '
                                                       'bucketing, array kdt, '
                                                       'long variable type, '
                                                       'double datatype, '
                                                       'commit: '
                                                       'd5bc6b16a36be719eb8671b4ab10f51bdf1276f1',
                                      'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                      'dataset': '3D_GeoLife_24M.pbbs',
                                      'dim': {3.0},
                                      'dimname': '3D_GeoLife_',
                                      'eps': {40.0},
                                      'machine': 'aws-c5.18x',
                                      'markcoretime': [0.617468,
                                                       0.167518,
                                                       0.083673,
                                                       0.0438721,
                                                       0.0326741,
                                                       0.024581,
                                                       0.023962],
                                      'minpts': {100.0},
                                      'ndalgo': {'nd'},
                                      'numborder': [3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0],
                                      'numclusterpts': [24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0],
                                      'numclusters': [63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0],
                                      'numcore': [24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0],
                                      'numgrids': [9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0],
                                      'numnoise': [17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0],
                                      'numprocs': {1.0,
                                                   4.0,
                                                   8.0,
                                                   16.0,
                                                   24.0,
                                                   36.0,
                                                   72.0},
                                      'numpts': [24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0],
                                      'numpts_attr': {24876978.0},
                                      'rho': {0.01},
                                      'rounds': {3.0},
                                      'serialalgo': {'parallel'},
                                      'testcount': 7,
                                      'totaltime': [3.62603,
                                                    1.46432,
                                                    0.999564,
                                                    0.710423,
                                                    0.479494,
                                                    0.442759,
                                                    0.688614],
                                      'variable': 'numprocs',
                                      'x': [1.0,
                                            4.0,
                                            8.0,
                                            16.0,
                                            24.0,
                                            36.0,
                                            72.0]},
                   '7D_HouseHold_2M': {'algo': {'exact'},
                                       'assignbordertime': [1.50204e-05,
                                                            9.05991e-06,
                                                            1.38283e-05,
                                                            1.3113e-05,
                                                            7.15256e-06,
                                                            8.10623e-06,
                                                            1.21593e-05],
                                       'assigngridtime': [0.129402,
                                                          0.0478902,
                                                          0.029144,
                                                          0.0211129,
                                                          0.02033,
                                                          0.0209749,
                                                          0.0218658],
                                       'buildcoreptquadtree': [-1,
                                                               -1,
                                                               -1,
                                                               -1,
                                                               -1,
                                                               -1,
                                                               -1],
                                       'buildgetnbrkdt': [2.28882e-05,
                                                          2.47955e-05,
                                                          2.59876e-05,
                                                          2.71797e-05,
                                                          3.50475e-05,
                                                          2.81334e-05,
                                                          0.000126123],
                                       'clustercoretime': [0.00531411,
                                                           0.00187302,
                                                           0.00111699,
                                                           0.000671864,
                                                           0.000584841,
                                                           0.000490904,
                                                           0.000557899],
                                       'config-id': '07-04-real1-exactbcp-bucketing',
                                       'configuration': 'nd-exact-bcp: '
                                                        'jemalloc, use '
                                                        'bucketing, array kdt, '
                                                        'long variable type, '
                                                        'double datatype, '
                                                        'commit: '
                                                        'd5bc6b16a36be719eb8671b4ab10f51bdf1276f1',
                                       'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                       'dataset': '7D_HouseHold_2M.pbbs',
                                       'dim': {7.0},
                                       'dimname': '7D_HouseHold_',
                                       'eps': {2000.0},
                                       'machine': 'aws-c5.18x',
                                       'markcoretime': [0.00451207,
                                                        0.00164413,
                                                        0.000858068,
                                                        0.000602007,
                                                        0.000564098,
                                                        0.000494003,
                                                        0.000617981],
                                       'minpts': {100.0},
                                       'ndalgo': {'nd'},
                                       'numborder': [1e-10,
                                                     1e-10,
                                                     1e-10,
                                                     1e-10,
                                                     1e-10,
                                                     1e-10,
                                                     1e-10],
                                       'numclusterpts': [2049280.0,
                                                         2049280.0,
                                                         2049280.0,
                                                         2049280.0,
                                                         2049280.0,
                                                         2049280.0,
                                                         2049280.0],
                                       'numclusters': [1.0,
                                                       1.0,
                                                       1.0,
                                                       1.0,
                                                       1.0,
                                                       1.0,
                                                       1.0],
                                       'numcore': [2049280.0,
                                                   2049280.0,
                                                   2049280.0,
                                                   2049280.0,
                                                   2049280.0,
                                                   2049280.0,
                                                   2049280.0],
                                       'numgrids': [1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0],
                                       'numnoise': [1e-10,
                                                    1e-10,
                                                    1e-10,
                                                    1e-10,
                                                    1e-10,
                                                    1e-10,
                                                    1e-10],
                                       'numprocs': {1.0,
                                                    4.0,
                                                    8.0,
                                                    16.0,
                                                    24.0,
                                                    36.0,
                                                    72.0},
                                       'numpts': [2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0],
                                       'numpts_attr': {2049280.0},
                                       'rho': {0.01},
                                       'rounds': {3.0},
                                       'serialalgo': {'parallel'},
                                       'testcount': 7,
                                       'totaltime': [0.139282,
                                                     0.0514598,
                                                     0.0311799,
                                                     0.0224469,
                                                     0.0215409,
                                                     0.0220149,
                                                     0.023205],
                                       'variable': 'numprocs',
                                       'x': [1.0,
                                             4.0,
                                             8.0,
                                             16.0,
                                             24.0,
                                             36.0,
                                             72.0]}},
 'numptsPlots': {}}