plotData = {'epsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                 'assignbordertime': [0.00400901,
                                                      0.00427413,
                                                      0.00444722,
                                                      0.00142097],
                                 'assigngridtime': [0.157705,
                                                    0.379087,
                                                    0.399835,
                                                    0.195679],
                                 'buildcoreptquadtree': [-1, -1, -1, -1],
                                 'buildgetnbrkdt': [0.00219798,
                                                    0.00158,
                                                    0.000947952,
                                                    0.000813007],
                                 'clustercoretime': [0.845098,
                                                     0.468047,
                                                     0.355392,
                                                     0.278462],
                                 'config-id': '1118-real4',
                                 'configuration': 'quadtreemc-quadraticbcp-bucketing: '
                                                  'kdt scans bothsides, '
                                                  'jemalloc, serial bucketing '
                                                  'for GeoLife, parallel '
                                                  'bucketing for HouseHold, '
                                                  'array kdt, long variable '
                                                  'type, double datatype, '
                                                  'commit:',
                                 'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                 'dataset': '3D_GeoLife_24M.pbbs',
                                 'dim': {3.0},
                                 'dimname': '3D_GeoLife_',
                                 'eps': {40.0, 80.0, 20.0, 160.0},
                                 'machine': 'aws-c5.18x',
                                 'markcoretime': [0.509847,
                                                  0.488455,
                                                  0.397484,
                                                  0.345357],
                                 'minpts': {100.0},
                                 'ndalgo': {'nd'},
                                 'numborder': [7391.0, 3792.0, 3572.0, 990.0],
                                 'numclusterpts': [24846295.0,
                                                   24859769.0,
                                                   24868067.0,
                                                   24873703.0],
                                 'numclusters': [91.0, 63.0, 56.0, 24.0],
                                 'numcore': [24838633.0,
                                             24855826.0,
                                             24864335.0,
                                             24872696.0],
                                 'numgrids': [22919.0, 9684.0, 3612.0, 1694.0],
                                 'numnoise': [30954.0, 17360.0, 9071.0, 3292.0],
                                 'numprocs': {72.0},
                                 'numpts': [24876978.0,
                                            24876978.0,
                                            24876978.0,
                                            24876978.0],
                                 'numpts_attr': {24876978.0},
                                 'rho': {0.01},
                                 'rounds': {3.0},
                                 'serialalgo': {'parallel'},
                                 'testcount': 4,
                                 'totaltime': [1.5209,
                                               1.34264,
                                               1.15842,
                                               0.821986],
                                 'variable': 'eps',
                                 'x': [20.0, 40.0, 80.0, 160.0]},
              '7D_HouseHold_2M': {'algo': {'exact'},
                                  'assignbordertime': [0.146682,
                                                       0.0938132,
                                                       0.143627,
                                                       0.209945,
                                                       0.228578,
                                                       0.254399],
                                  'assigngridtime': [0.038991,
                                                     0.046401,
                                                     0.0356228,
                                                     0.0444319,
                                                     0.0336919,
                                                     0.0378649],
                                  'buildcoreptquadtree': [-1,
                                                          -1,
                                                          -1,
                                                          -1,
                                                          -1,
                                                          -1],
                                  'buildgetnbrkdt': [0.139467,
                                                     0.0737629,
                                                     0.05144,
                                                     0.032227,
                                                     0.0244009,
                                                     0.0191381],
                                  'clustercoretime': [0.287623,
                                                      0.160117,
                                                      0.211616,
                                                      1.25978,
                                                      1.88437,
                                                      4.97913],
                                  'config-id': '1118-real4',
                                  'configuration': 'quadtreemc-quadraticbcp-bucketing: '
                                                   'kdt scans bothsides, '
                                                   'jemalloc, serial bucketing '
                                                   'for GeoLife, parallel '
                                                   'bucketing for HouseHold, '
                                                   'array kdt, long variable '
                                                   'type, double datatype, '
                                                   'commit:',
                                  'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                  'dataset': '7D_HouseHold_2M.pbbs',
                                  'dim': {7.0},
                                  'dimname': '7D_HouseHold_',
                                  'eps': {1000.0,
                                          1400.0,
                                          1800.0,
                                          2200.0,
                                          2600.0,
                                          3000.0},
                                  'machine': 'aws-c5.18x',
                                  'markcoretime': [2.50238,
                                                   2.62629,
                                                   3.16579,
                                                   3.86332,
                                                   4.43804,
                                                   5.0385],
                                  'minpts': {100.0},
                                  'ndalgo': {'nd'},
                                  'numborder': [123077.0,
                                                148926.0,
                                                121447.0,
                                                97189.0,
                                                76854.0,
                                                64485.0],
                                  'numclusterpts': [1220205.0,
                                                    1507976.0,
                                                    1668837.0,
                                                    1760132.0,
                                                    1815454.0,
                                                    1855854.0],
                                  'numclusters': [55.0,
                                                  30.0,
                                                  27.0,
                                                  30.0,
                                                  38.0,
                                                  48.0],
                                  'numcore': [1096868.0,
                                              1358900.0,
                                              1547291.0,
                                              1662856.0,
                                              1738555.0,
                                              1791293.0],
                                  'numgrids': [987740.0,
                                               796144.0,
                                               664053.0,
                                               570752.0,
                                               498785.0,
                                               442979.0],
                                  'numnoise': [829335.0,
                                               541454.0,
                                               380542.0,
                                               289235.0,
                                               233871.0,
                                               193502.0],
                                  'numprocs': {72.0},
                                  'numpts': [2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0],
                                  'numpts_attr': {2049280.0},
                                  'rho': {0.01},
                                  'rounds': {3.0},
                                  'serialalgo': {'parallel'},
                                  'testcount': 6,
                                  'totaltime': [3.14026,
                                                3.02025,
                                                3.62578,
                                                5.45316,
                                                6.65964,
                                                10.4169],
                                  'variable': 'eps',
                                  'x': [1000.0,
                                        1400.0,
                                        1800.0,
                                        2200.0,
                                        2600.0,
                                        3000.0]}},
 'minptsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                    'assignbordertime': [0.0653489,
                                                         0.00427413,
                                                         0.00415611,
                                                         0.00981903,
                                                         0.109312,
                                                         0.194936],
                                    'assigngridtime': [0.194469,
                                                       0.379087,
                                                       0.284218,
                                                       0.156539,
                                                       0.157788,
                                                       0.15564],
                                    'buildcoreptquadtree': [-1,
                                                            -1,
                                                            -1,
                                                            -1,
                                                            -1,
                                                            -1],
                                    'buildgetnbrkdt': [0.00150704,
                                                       0.00158,
                                                       0.00153685,
                                                       0.00155711,
                                                       0.00234294,
                                                       0.00184298],
                                    'clustercoretime': [0.557259,
                                                        0.468047,
                                                        0.541841,
                                                        0.605237,
                                                        0.559222,
                                                        0.549322],
                                    'config-id': '1118-real4',
                                    'configuration': 'quadtreemc-quadraticbcp-bucketing: '
                                                     'kdt scans bothsides, '
                                                     'jemalloc, serial '
                                                     'bucketing for GeoLife, '
                                                     'parallel bucketing for '
                                                     'HouseHold, array kdt, '
                                                     'long variable type, '
                                                     'double datatype, commit:',
                                    'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                    'dataset': '3D_GeoLife_24M.pbbs',
                                    'dim': {3.0},
                                    'dimname': '3D_GeoLife_',
                                    'eps': {40.0},
                                    'machine': 'aws-c5.18x',
                                    'markcoretime': [0.407448,
                                                     0.488455,
                                                     0.518851,
                                                     0.53342,
                                                     0.657287,
                                                     0.773497],
                                    'minpts': {10.0,
                                               100.0,
                                               500.0,
                                               1000.0,
                                               5000.0,
                                               10000.0},
                                    'ndalgo': {'nd'},
                                    'numborder': [320.0,
                                                  3792.0,
                                                  8875.0,
                                                  17552.0,
                                                  100174.0,
                                                  91834.0],
                                    'numclusterpts': [24875629.0,
                                                      24859769.0,
                                                      24824591.0,
                                                      24795161.0,
                                                      24501620.0,
                                                      24141105.0],
                                    'numclusters': [84.0,
                                                    63.0,
                                                    26.0,
                                                    21.0,
                                                    19.0,
                                                    8.0],
                                    'numcore': [24875293.0,
                                                24855826.0,
                                                24815466.0,
                                                24776370.0,
                                                24399987.0,
                                                24049271.0],
                                    'numgrids': [9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0],
                                    'numnoise': [1365.0,
                                                 17360.0,
                                                 52637.0,
                                                 83056.0,
                                                 376817.0,
                                                 735873.0],
                                    'numprocs': {72.0},
                                    'numpts': [24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0],
                                    'numpts_attr': {24876978.0},
                                    'rho': {0.01},
                                    'rounds': {3.0},
                                    'serialalgo': {'parallel'},
                                    'testcount': 6,
                                    'totaltime': [1.22647,
                                                  1.34264,
                                                  1.35231,
                                                  1.30761,
                                                  1.48641,
                                                  1.67578],
                                    'variable': 'minpts',
                                    'x': [10.0,
                                          100.0,
                                          500.0,
                                          1000.0,
                                          5000.0,
                                          10000.0]},
                 '7D_HouseHold_2M': {'algo': {'exact'},
                                     'assignbordertime': [0.0176928,
                                                          0.142191,
                                                          0.469742,
                                                          0.841457,
                                                          2.53079,
                                                          2.02029],
                                     'assigngridtime': [0.0400779,
                                                        0.039433,
                                                        0.0367332,
                                                        0.037982,
                                                        0.036484,
                                                        0.0359211],
                                     'buildcoreptquadtree': [-1,
                                                             -1,
                                                             -1,
                                                             -1,
                                                             -1,
                                                             -1],
                                     'buildgetnbrkdt': [0.0346649,
                                                        0.032521,
                                                        0.041173,
                                                        0.04637,
                                                        0.045229,
                                                        0.0429711],
                                     'clustercoretime': [0.40252,
                                                         0.210472,
                                                         0.105763,
                                                         0.0722699,
                                                         0.0186501,
                                                         0.021013],
                                     'config-id': '1118-real4',
                                     'configuration': 'quadtreemc-quadraticbcp-bucketing: '
                                                      'kdt scans bothsides, '
                                                      'jemalloc, serial '
                                                      'bucketing for GeoLife, '
                                                      'parallel bucketing for '
                                                      'HouseHold, array kdt, '
                                                      'long variable type, '
                                                      'double datatype, '
                                                      'commit:',
                                     'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                     'dataset': '7D_HouseHold_2M.pbbs',
                                     'dim': {7.0},
                                     'dimname': '7D_HouseHold_',
                                     'eps': {2000.0},
                                     'machine': 'aws-c5.18x',
                                     'markcoretime': [2.1728,
                                                      2.99614,
                                                      4.57352,
                                                      5.73623,
                                                      11.0331,
                                                      13.4004],
                                     'minpts': {10.0,
                                                100.0,
                                                500.0,
                                                1000.0,
                                                5000.0,
                                                10000.0},
                                     'ndalgo': {'nd'},
                                     'numborder': [42452.0,
                                                   108607.0,
                                                   174591.0,
                                                   209145.0,
                                                   318927.0,
                                                   233088.0],
                                     'numclusterpts': [1910253.0,
                                                       1721856.0,
                                                       1462453.0,
                                                       1319491.0,
                                                       874952.0,
                                                       514765.0],
                                     'numclusters': [599.0,
                                                     27.0,
                                                     13.0,
                                                     13.0,
                                                     8.0,
                                                     4.0],
                                     'numcore': [1867325.0,
                                                 1613187.0,
                                                 1287762.0,
                                                 1109405.0,
                                                 555714.0,
                                                 281677.0],
                                     'numgrids': [613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0],
                                     'numnoise': [139503.0,
                                                  327486.0,
                                                  586927.0,
                                                  730730.0,
                                                  1174639.0,
                                                  1534515.0],
                                     'numprocs': {72.0},
                                     'numpts': [2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0],
                                     'numpts_attr': {2049280.0},
                                     'rho': {0.01},
                                     'rounds': {3.0},
                                     'serialalgo': {'parallel'},
                                     'testcount': 6,
                                     'totaltime': [2.68735,
                                                   3.46421,
                                                   5.25446,
                                                   6.77325,
                                                   13.7473,
                                                   15.591],
                                     'variable': 'minpts',
                                     'x': [10.0,
                                           100.0,
                                           500.0,
                                           1000.0,
                                           5000.0,
                                           10000.0]}},
 'numprocsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                      'assignbordertime': [0.010314,
                                                           0.00471592,
                                                           0.00336695,
                                                           0.00285316,
                                                           0.00226498,
                                                           0.00223303,
                                                           0.00427413],
                                      'assigngridtime': [1.62175,
                                                         0.588386,
                                                         0.280972,
                                                         0.187263,
                                                         0.154557,
                                                         0.220436,
                                                         0.379087],
                                      'buildcoreptquadtree': [-1,
                                                              -1,
                                                              -1,
                                                              -1,
                                                              -1,
                                                              -1,
                                                              -1],
                                      'buildgetnbrkdt': [0.00231814,
                                                         0.00127792,
                                                         0.00122309,
                                                         0.00111699,
                                                         0.00101781,
                                                         0.00104594,
                                                         0.00158],
                                      'clustercoretime': [1.23942,
                                                          0.649098,
                                                          0.574957,
                                                          0.483529,
                                                          0.480873,
                                                          0.43368,
                                                          0.468047],
                                      'config-id': '1118-real4',
                                      'configuration': 'quadtreemc-quadraticbcp-bucketing: '
                                                       'kdt scans bothsides, '
                                                       'jemalloc, serial '
                                                       'bucketing for GeoLife, '
                                                       'parallel bucketing for '
                                                       'HouseHold, array kdt, '
                                                       'long variable type, '
                                                       'double datatype, '
                                                       'commit:',
                                      'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                      'dataset': '3D_GeoLife_24M.pbbs',
                                      'dim': {3.0},
                                      'dimname': '3D_GeoLife_',
                                      'eps': {40.0},
                                      'machine': 'aws-c5.18x',
                                      'markcoretime': [7.09817,
                                                       2.47177,
                                                       1.40734,
                                                       0.994575,
                                                       0.600226,
                                                       0.526415,
                                                       0.488455],
                                      'minpts': {100.0},
                                      'ndalgo': {'nd'},
                                      'numborder': [3792.0,
                                                    3792.0,
                                                    3792.0,
                                                    3792.0,
                                                    3792.0,
                                                    3792.0,
                                                    3792.0],
                                      'numclusterpts': [24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0],
                                      'numclusters': [63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0],
                                      'numcore': [24855826.0,
                                                  24855826.0,
                                                  24855826.0,
                                                  24855826.0,
                                                  24855826.0,
                                                  24855826.0,
                                                  24855826.0],
                                      'numgrids': [9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0],
                                      'numnoise': [17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0],
                                      'numprocs': {1.0,
                                                   4.0,
                                                   8.0,
                                                   16.0,
                                                   24.0,
                                                   36.0,
                                                   72.0},
                                      'numpts': [24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0],
                                      'numpts_attr': {24876978.0},
                                      'rho': {0.01},
                                      'rounds': {3.0},
                                      'serialalgo': {'parallel'},
                                      'testcount': 7,
                                      'totaltime': [9.97236,
                                                    3.71571,
                                                    2.26838,
                                                    1.66987,
                                                    1.23947,
                                                    1.18446,
                                                    1.34264],
                                      'variable': 'numprocs',
                                      'x': [1.0,
                                            4.0,
                                            8.0,
                                            16.0,
                                            24.0,
                                            36.0,
                                            72.0]},
                   '7D_HouseHold_2M': {'algo': {'exact'},
                                       'assignbordertime': [3.35726,
                                                            0.968416,
                                                            0.543442,
                                                            0.278273,
                                                            0.198715,
                                                            0.163901,
                                                            0.142191],
                                       'assigngridtime': [0.843017,
                                                          0.257963,
                                                          0.133986,
                                                          0.07919,
                                                          0.0556252,
                                                          0.0419459,
                                                          0.039433],
                                       'buildcoreptquadtree': [-1,
                                                               -1,
                                                               -1,
                                                               -1,
                                                               -1,
                                                               -1,
                                                               -1],
                                       'buildgetnbrkdt': [0.651889,
                                                          0.172872,
                                                          0.102469,
                                                          0.0574899,
                                                          0.0413561,
                                                          0.029532,
                                                          0.032521],
                                       'clustercoretime': [3.39059,
                                                           1.25161,
                                                           0.586357,
                                                           0.320589,
                                                           0.342252,
                                                           0.225798,
                                                           0.210472],
                                       'config-id': '1118-real4',
                                       'configuration': 'quadtreemc-quadraticbcp-bucketing: '
                                                        'kdt scans bothsides, '
                                                        'jemalloc, serial '
                                                        'bucketing for '
                                                        'GeoLife, parallel '
                                                        'bucketing for '
                                                        'HouseHold, array kdt, '
                                                        'long variable type, '
                                                        'double datatype, '
                                                        'commit:',
                                       'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                       'dataset': '7D_HouseHold_2M.pbbs',
                                       'dim': {7.0},
                                       'dimname': '7D_HouseHold_',
                                       'eps': {2000.0},
                                       'machine': 'aws-c5.18x',
                                       'markcoretime': [98.5842,
                                                        25.8328,
                                                        13.1861,
                                                        6.69509,
                                                        4.69301,
                                                        3.38431,
                                                        2.99614],
                                       'minpts': {100.0},
                                       'ndalgo': {'nd'},
                                       'numborder': [108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0],
                                       'numclusterpts': [1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0],
                                       'numclusters': [27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0],
                                       'numcore': [1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0],
                                       'numgrids': [613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0],
                                       'numnoise': [327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0],
                                       'numprocs': {1.0,
                                                    4.0,
                                                    8.0,
                                                    16.0,
                                                    24.0,
                                                    36.0,
                                                    72.0},
                                       'numpts': [2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0],
                                       'numpts_attr': {2049280.0},
                                       'rho': {0.01},
                                       'rounds': {3.0},
                                       'serialalgo': {'parallel'},
                                       'testcount': 7,
                                       'totaltime': [106.899,
                                                     28.5476,
                                                     14.6083,
                                                     7.4905,
                                                     5.35678,
                                                     3.87183,
                                                     3.46421],
                                       'variable': 'numprocs',
                                       'x': [1.0,
                                             4.0,
                                             8.0,
                                             16.0,
                                             24.0,
                                             36.0,
                                             72.0]}},
 'numptsPlots': {},
 'rhoPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                 'assignbordertime': [0.00427413],
                                 'assigngridtime': [0.379087],
                                 'buildcoreptquadtree': [-1],
                                 'buildgetnbrkdt': [0.00158],
                                 'clustercoretime': [0.468047],
                                 'config-id': '1118-real4',
                                 'configuration': 'quadtreemc-quadraticbcp-bucketing: '
                                                  'kdt scans bothsides, '
                                                  'jemalloc, serial bucketing '
                                                  'for GeoLife, parallel '
                                                  'bucketing for HouseHold, '
                                                  'array kdt, long variable '
                                                  'type, double datatype, '
                                                  'commit:',
                                 'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                 'dataset': '3D_GeoLife_24M.pbbs',
                                 'dim': {3.0},
                                 'dimname': '3D_GeoLife_',
                                 'eps': {40.0},
                                 'machine': 'aws-c5.18x',
                                 'markcoretime': [0.488455],
                                 'minpts': {100.0},
                                 'ndalgo': {'nd'},
                                 'numborder': [3792.0],
                                 'numclusterpts': [24859769.0],
                                 'numclusters': [63.0],
                                 'numcore': [24855826.0],
                                 'numgrids': [9684.0],
                                 'numnoise': [17360.0],
                                 'numprocs': {72.0},
                                 'numpts': [24876978.0],
                                 'numpts_attr': {24876978.0},
                                 'rho': {0.01},
                                 'rounds': {3.0},
                                 'serialalgo': {'parallel'},
                                 'testcount': 1,
                                 'totaltime': [1.34264],
                                 'variable': 'rho',
                                 'x': [0.01]},
              '7D_HouseHold_2M': {'algo': {'exact'},
                                  'assignbordertime': [0.142191],
                                  'assigngridtime': [0.039433],
                                  'buildcoreptquadtree': [-1],
                                  'buildgetnbrkdt': [0.032521],
                                  'clustercoretime': [0.210472],
                                  'config-id': '1118-real4',
                                  'configuration': 'quadtreemc-quadraticbcp-bucketing: '
                                                   'kdt scans bothsides, '
                                                   'jemalloc, serial bucketing '
                                                   'for GeoLife, parallel '
                                                   'bucketing for HouseHold, '
                                                   'array kdt, long variable '
                                                   'type, double datatype, '
                                                   'commit:',
                                  'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                  'dataset': '7D_HouseHold_2M.pbbs',
                                  'dim': {7.0},
                                  'dimname': '7D_HouseHold_',
                                  'eps': {2000.0},
                                  'machine': 'aws-c5.18x',
                                  'markcoretime': [2.99614],
                                  'minpts': {100.0},
                                  'ndalgo': {'nd'},
                                  'numborder': [108607.0],
                                  'numclusterpts': [1721856.0],
                                  'numclusters': [27.0],
                                  'numcore': [1613187.0],
                                  'numgrids': [613546.0],
                                  'numnoise': [327486.0],
                                  'numprocs': {72.0},
                                  'numpts': [2049280.0],
                                  'numpts_attr': {2049280.0},
                                  'rho': {0.01},
                                  'rounds': {3.0},
                                  'serialalgo': {'parallel'},
                                  'testcount': 1,
                                  'totaltime': [3.46421],
                                  'variable': 'rho',
                                  'x': [0.01]}}}