plotData = {'epsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                 'assignbordertime': [0.00353503,
                                                      0.0111911,
                                                      0.0128338,
                                                      0.00117397],
                                 'assigngridtime': [0.214196,
                                                    0.199891,
                                                    0.458981,
                                                    0.220628],
                                 'buildcoreptquadtree': [-1, -1, -1, -1],
                                 'buildgetnbrkdt': [0.00258803,
                                                    0.00179791,
                                                    0.00601602,
                                                    0.000824928],
                                 'clustercoretime': [0.358076,
                                                     0.496259,
                                                     51.0719,
                                                     0.356613],
                                 'config-id': '1118-real4',
                                 'configuration': 'our-exact-bucketing '
                                                  '(re-test for 3dgeolife '
                                                  'eps=80 timing): kdt scans '
                                                  'bothsides, jemalloc, '
                                                  'bucketing, array kdt, long '
                                                  'variable type, double '
                                                  'datatype, commit:',
                                 'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                 'dataset': '3D_GeoLife_24M.pbbs',
                                 'dim': {3.0},
                                 'dimname': '3D_GeoLife_',
                                 'eps': {40.0, 80.0, 20.0, 160.0},
                                 'machine': 'aws-c5.18x',
                                 'markcoretime': [0.022877,
                                                  0.0138681,
                                                  0.101436,
                                                  0.00825214],
                                 'minpts': {100.0},
                                 'ndalgo': {'nd'},
                                 'numborder': [7391.0, 3791.0, 3572.0, 990.0],
                                 'numclusterpts': [24846295.0,
                                                   24859769.0,
                                                   24868067.0,
                                                   24873703.0],
                                 'numclusters': [91.0, 63.0, 56.0, 24.0],
                                 'numcore': [24838633.0,
                                             24855827.0,
                                             24864335.0,
                                             24872696.0],
                                 'numgrids': [22919.0, 9684.0, 3612.0, 1694.0],
                                 'numnoise': [30954.0, 17360.0, 9071.0, 3292.0],
                                 'numprocs': {72.0},
                                 'numpts': [24876978.0,
                                            24876978.0,
                                            24876978.0,
                                            24876978.0],
                                 'numpts_attr': {24876978.0},
                                 'rho': {0.01},
                                 'rounds': {3.0},
                                 'serialalgo': {'parallel'},
                                 'testcount': 4,
                                 'totaltime': [0.602193,
                                               0.723352,
                                               51.6518,
                                               0.587735],
                                 'variable': 'eps',
                                 'x': [20.0, 40.0, 80.0, 160.0]},
              '7D_HouseHold_2M': {'algo': {'exact'},
                                  'assignbordertime': [0.165753,
                                                       0.101207,
                                                       0.144637,
                                                       0.252999,
                                                       0.246133,
                                                       0.239871],
                                  'assigngridtime': [0.0445421,
                                                     0.04515,
                                                     0.0440922,
                                                     0.040591,
                                                     0.0413022,
                                                     0.0388689],
                                  'buildcoreptquadtree': [-1,
                                                          -1,
                                                          -1,
                                                          -1,
                                                          -1,
                                                          -1],
                                  'buildgetnbrkdt': [0.168244,
                                                     0.087322,
                                                     0.05601,
                                                     0.04301,
                                                     0.0438159,
                                                     0.0224979],
                                  'clustercoretime': [0.310743,
                                                      0.186997,
                                                      0.189631,
                                                      1.38702,
                                                      1.88489,
                                                      5.11132],
                                  'config-id': '1118-real4',
                                  'configuration': 'our-exact-bucketing '
                                                   '(re-test for 3dgeolife '
                                                   'eps=80 timing): kdt scans '
                                                   'bothsides, jemalloc, '
                                                   'bucketing, array kdt, long '
                                                   'variable type, double '
                                                   'datatype, commit:',
                                  'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                  'dataset': '7D_HouseHold_2M.pbbs',
                                  'dim': {7.0},
                                  'dimname': '7D_HouseHold_',
                                  'eps': {1000.0,
                                          1400.0,
                                          1800.0,
                                          2200.0,
                                          2600.0,
                                          3000.0},
                                  'machine': 'aws-c5.18x',
                                  'markcoretime': [2.54608,
                                                   3.12396,
                                                   4.31881,
                                                   9.39019,
                                                   10.1913,
                                                   10.7799],
                                  'minpts': {100.0},
                                  'ndalgo': {'nd'},
                                  'numborder': [123077.0,
                                                148926.0,
                                                121447.0,
                                                97189.0,
                                                76854.0,
                                                64485.0],
                                  'numclusterpts': [1220205.0,
                                                    1507976.0,
                                                    1668837.0,
                                                    1760132.0,
                                                    1815454.0,
                                                    1855854.0],
                                  'numclusters': [55.0,
                                                  30.0,
                                                  27.0,
                                                  30.0,
                                                  38.0,
                                                  48.0],
                                  'numcore': [1096868.0,
                                              1358900.0,
                                              1547291.0,
                                              1662856.0,
                                              1738555.0,
                                              1791293.0],
                                  'numgrids': [987740.0,
                                               796144.0,
                                               664053.0,
                                               570752.0,
                                               498785.0,
                                               442979.0],
                                  'numnoise': [829335.0,
                                               541454.0,
                                               380542.0,
                                               289235.0,
                                               233871.0,
                                               193502.0],
                                  'numprocs': {72.0},
                                  'numpts': [2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0],
                                  'numpts_attr': {2049280.0},
                                  'rho': {0.01},
                                  'rounds': {3.0},
                                  'serialalgo': {'parallel'},
                                  'testcount': 6,
                                  'totaltime': [3.25595,
                                                3.56169,
                                                4.79646,
                                                11.1692,
                                                12.4367,
                                                16.2435],
                                  'variable': 'eps',
                                  'x': [1000.0,
                                        1400.0,
                                        1800.0,
                                        2200.0,
                                        2600.0,
                                        3000.0]}},
 'minptsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                    'assignbordertime': [0.00836706,
                                                         0.0111911,
                                                         0.00397015,
                                                         0.010905,
                                                         0.111475,
                                                         0.203964],
                                    'assigngridtime': [0.207252,
                                                       0.199891,
                                                       0.582691,
                                                       0.158872,
                                                       0.172344,
                                                       0.175981],
                                    'buildcoreptquadtree': [-1,
                                                            -1,
                                                            -1,
                                                            -1,
                                                            -1,
                                                            -1],
                                    'buildgetnbrkdt': [0.00186491,
                                                       0.00179791,
                                                       0.028446,
                                                       0.033077,
                                                       0.00199986,
                                                       0.00189996],
                                    'clustercoretime': [0.543057,
                                                        0.496259,
                                                        0.50437,
                                                        1.345,
                                                        0.490741,
                                                        0.508099],
                                    'config-id': '1118-real4',
                                    'configuration': 'our-exact-bucketing '
                                                     '(re-test for 3dgeolife '
                                                     'eps=80 timing): kdt '
                                                     'scans bothsides, '
                                                     'jemalloc, bucketing, '
                                                     'array kdt, long variable '
                                                     'type, double datatype, '
                                                     'commit:',
                                    'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                    'dataset': '3D_GeoLife_24M.pbbs',
                                    'dim': {3.0},
                                    'dimname': '3D_GeoLife_',
                                    'eps': {40.0},
                                    'machine': 'aws-c5.18x',
                                    'markcoretime': [0.013418,
                                                     0.0138681,
                                                     0.042644,
                                                     0.121967,
                                                     0.882555,
                                                     2.57195],
                                    'minpts': {10.0,
                                               100.0,
                                               500.0,
                                               1000.0,
                                               5000.0,
                                               10000.0},
                                    'ndalgo': {'nd'},
                                    'numborder': [320.0,
                                                  3791.0,
                                                  8860.0,
                                                  17546.0,
                                                  100090.0,
                                                  91985.0],
                                    'numclusterpts': [24875629.0,
                                                      24859769.0,
                                                      24824591.0,
                                                      24795161.0,
                                                      24501634.0,
                                                      24141423.0],
                                    'numclusters': [84.0,
                                                    63.0,
                                                    26.0,
                                                    21.0,
                                                    19.0,
                                                    8.0],
                                    'numcore': [24875293.0,
                                                24855827.0,
                                                24815481.0,
                                                24776376.0,
                                                24400085.0,
                                                24049438.0],
                                    'numgrids': [9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0],
                                    'numnoise': [1365.0,
                                                 17360.0,
                                                 52637.0,
                                                 83056.0,
                                                 376803.0,
                                                 735555.0],
                                    'numprocs': {72.0},
                                    'numpts': [24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0],
                                    'numpts_attr': {24876978.0},
                                    'rho': {0.01},
                                    'rounds': {3.0},
                                    'serialalgo': {'parallel'},
                                    'testcount': 6,
                                    'totaltime': [0.774241,
                                                  0.723352,
                                                  1.16379,
                                                  1.6702,
                                                  1.65958,
                                                  3.46342],
                                    'variable': 'minpts',
                                    'x': [10.0,
                                          100.0,
                                          500.0,
                                          1000.0,
                                          5000.0,
                                          10000.0]},
                 '7D_HouseHold_2M': {'algo': {'exact'},
                                     'assignbordertime': [0.019299,
                                                          0.151297,
                                                          0.513514,
                                                          0.836942,
                                                          2.67606,
                                                          2.28031],
                                     'assigngridtime': [0.0855289,
                                                        0.0581121,
                                                        0.042856,
                                                        0.035234,
                                                        0.0493441,
                                                        0.042731],
                                     'buildcoreptquadtree': [-1,
                                                             -1,
                                                             -1,
                                                             -1,
                                                             -1,
                                                             -1],
                                     'buildgetnbrkdt': [0.0436101,
                                                        0.0467339,
                                                        0.058229,
                                                        0.043875,
                                                        0.041708,
                                                        0.060092],
                                     'clustercoretime': [0.482441,
                                                         0.220161,
                                                         0.115712,
                                                         0.0586851,
                                                         0.0235021,
                                                         0.023787],
                                     'config-id': '1118-real4',
                                     'configuration': 'our-exact-bucketing '
                                                      '(re-test for 3dgeolife '
                                                      'eps=80 timing): kdt '
                                                      'scans bothsides, '
                                                      'jemalloc, bucketing, '
                                                      'array kdt, long '
                                                      'variable type, double '
                                                      'datatype, commit:',
                                     'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                     'dataset': '7D_HouseHold_2M.pbbs',
                                     'dim': {7.0},
                                     'dimname': '7D_HouseHold_',
                                     'eps': {2000.0},
                                     'machine': 'aws-c5.18x',
                                     'markcoretime': [2.71121,
                                                      4.57081,
                                                      6.31527,
                                                      7.75281,
                                                      14.5203,
                                                      16.5259],
                                     'minpts': {10.0,
                                                100.0,
                                                500.0,
                                                1000.0,
                                                5000.0,
                                                10000.0},
                                     'ndalgo': {'nd'},
                                     'numborder': [42452.0,
                                                   108607.0,
                                                   174591.0,
                                                   209145.0,
                                                   318927.0,
                                                   233083.0],
                                     'numclusterpts': [1910253.0,
                                                       1721856.0,
                                                       1462453.0,
                                                       1319491.0,
                                                       874953.0,
                                                       514766.0],
                                     'numclusters': [599.0,
                                                     27.0,
                                                     13.0,
                                                     13.0,
                                                     8.0,
                                                     4.0],
                                     'numcore': [1867325.0,
                                                 1613187.0,
                                                 1287762.0,
                                                 1109405.0,
                                                 555715.0,
                                                 281683.0],
                                     'numgrids': [613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0],
                                     'numnoise': [139503.0,
                                                  327486.0,
                                                  586927.0,
                                                  730730.0,
                                                  1174638.0,
                                                  1534514.0],
                                     'numprocs': {72.0},
                                     'numpts': [2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0],
                                     'numpts_attr': {2049280.0},
                                     'rho': {0.01},
                                     'rounds': {3.0},
                                     'serialalgo': {'parallel'},
                                     'testcount': 6,
                                     'totaltime': [3.38171,
                                                   5.09749,
                                                   7.06173,
                                                   8.82733,
                                                   17.3892,
                                                   18.9613],
                                     'variable': 'minpts',
                                     'x': [10.0,
                                           100.0,
                                           500.0,
                                           1000.0,
                                           5000.0,
                                           10000.0]}},
 'numprocsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                      'assignbordertime': [0.0102079,
                                                           0.00543499,
                                                           0.0030148,
                                                           0.00291991,
                                                           0.00272417,
                                                           0.0285649,
                                                           0.0111911],
                                      'assigngridtime': [1.72717,
                                                         0.53946,
                                                         0.306873,
                                                         0.282533,
                                                         0.22948,
                                                         0.22745,
                                                         0.199891],
                                      'buildcoreptquadtree': [-1,
                                                              -1,
                                                              -1,
                                                              -1,
                                                              -1,
                                                              -1,
                                                              -1],
                                      'buildgetnbrkdt': [0.0024929,
                                                         0.00163388,
                                                         0.00251889,
                                                         0.00310898,
                                                         0.0029099,
                                                         0.00131202,
                                                         0.00179791],
                                      'clustercoretime': [1.26515,
                                                          0.841823,
                                                          0.554854,
                                                          0.33524,
                                                          0.422479,
                                                          0.46864,
                                                          0.496259],
                                      'config-id': '1118-real4',
                                      'configuration': 'our-exact-bucketing '
                                                       '(re-test for 3dgeolife '
                                                       'eps=80 timing): kdt '
                                                       'scans bothsides, '
                                                       'jemalloc, bucketing, '
                                                       'array kdt, long '
                                                       'variable type, double '
                                                       'datatype, commit:',
                                      'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                      'dataset': '3D_GeoLife_24M.pbbs',
                                      'dim': {3.0},
                                      'dimname': '3D_GeoLife_',
                                      'eps': {40.0},
                                      'machine': 'aws-c5.18x',
                                      'markcoretime': [0.26078,
                                                       0.0756919,
                                                       0.039716,
                                                       0.0215468,
                                                       0.0156131,
                                                       0.0142071,
                                                       0.0138681],
                                      'minpts': {100.0},
                                      'ndalgo': {'nd'},
                                      'numborder': [3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0],
                                      'numclusterpts': [24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0],
                                      'numclusters': [63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0],
                                      'numcore': [24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0],
                                      'numgrids': [9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0],
                                      'numnoise': [17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0],
                                      'numprocs': {1.0,
                                                   4.0,
                                                   8.0,
                                                   16.0,
                                                   24.0,
                                                   36.0,
                                                   72.0},
                                      'numpts': [24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0],
                                      'numpts_attr': {24876978.0},
                                      'rho': {0.01},
                                      'rounds': {3.0},
                                      'serialalgo': {'parallel'},
                                      'testcount': 7,
                                      'totaltime': [3.26622,
                                                    1.46452,
                                                    0.907438,
                                                    0.646033,
                                                    0.673477,
                                                    0.740465,
                                                    0.723352],
                                      'variable': 'numprocs',
                                      'x': [1.0,
                                            4.0,
                                            8.0,
                                            16.0,
                                            24.0,
                                            36.0,
                                            72.0]},
                   '7D_HouseHold_2M': {'algo': {'exact'},
                                       'assignbordertime': [3.42106,
                                                            1.02774,
                                                            0.5849,
                                                            0.296569,
                                                            0.239913,
                                                            0.151868,
                                                            0.151297],
                                       'assigngridtime': [0.86245,
                                                          0.300344,
                                                          0.141874,
                                                          0.0859449,
                                                          0.0662911,
                                                          0.0464289,
                                                          0.0581121],
                                       'buildcoreptquadtree': [-1,
                                                               -1,
                                                               -1,
                                                               -1,
                                                               -1,
                                                               -1,
                                                               -1],
                                       'buildgetnbrkdt': [0.79189,
                                                          0.213453,
                                                          0.114978,
                                                          0.0694592,
                                                          0.0636699,
                                                          0.0418091,
                                                          0.0467339],
                                       'clustercoretime': [3.43945,
                                                           1.11844,
                                                           0.674244,
                                                           0.356548,
                                                           0.356978,
                                                           0.207794,
                                                           0.220161],
                                       'config-id': '1118-real4',
                                       'configuration': 'our-exact-bucketing '
                                                        '(re-test for '
                                                        '3dgeolife eps=80 '
                                                        'timing): kdt scans '
                                                        'bothsides, jemalloc, '
                                                        'bucketing, array kdt, '
                                                        'long variable type, '
                                                        'double datatype, '
                                                        'commit:',
                                       'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                       'dataset': '7D_HouseHold_2M.pbbs',
                                       'dim': {7.0},
                                       'dimname': '7D_HouseHold_',
                                       'eps': {2000.0},
                                       'machine': 'aws-c5.18x',
                                       'markcoretime': [105.305,
                                                        27.6084,
                                                        14.2869,
                                                        7.71438,
                                                        5.6329,
                                                        4.48112,
                                                        4.57081],
                                       'minpts': {100.0},
                                       'ndalgo': {'nd'},
                                       'numborder': [108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0],
                                       'numclusterpts': [1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0],
                                       'numclusters': [27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0],
                                       'numcore': [1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0],
                                       'numgrids': [613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0],
                                       'numnoise': [327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0],
                                       'numprocs': {1.0,
                                                    4.0,
                                                    8.0,
                                                    16.0,
                                                    24.0,
                                                    36.0,
                                                    72.0},
                                       'numpts': [2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0],
                                       'numpts_attr': {2049280.0},
                                       'rho': {0.01},
                                       'rounds': {3.0},
                                       'serialalgo': {'parallel'},
                                       'testcount': 7,
                                       'totaltime': [113.893,
                                                     30.4703,
                                                     15.9149,
                                                     8.60786,
                                                     6.40745,
                                                     4.96195,
                                                     5.09749],
                                       'variable': 'numprocs',
                                       'x': [1.0,
                                             4.0,
                                             8.0,
                                             16.0,
                                             24.0,
                                             36.0,
                                             72.0]}},
 'numptsPlots': {},
 'rhoPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                 'assignbordertime': [0.0111911],
                                 'assigngridtime': [0.199891],
                                 'buildcoreptquadtree': [-1],
                                 'buildgetnbrkdt': [0.00179791],
                                 'clustercoretime': [0.496259],
                                 'config-id': '1118-real4',
                                 'configuration': 'our-exact-bucketing '
                                                  '(re-test for 3dgeolife '
                                                  'eps=80 timing): kdt scans '
                                                  'bothsides, jemalloc, '
                                                  'bucketing, array kdt, long '
                                                  'variable type, double '
                                                  'datatype, commit:',
                                 'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                 'dataset': '3D_GeoLife_24M.pbbs',
                                 'dim': {3.0},
                                 'dimname': '3D_GeoLife_',
                                 'eps': {40.0},
                                 'machine': 'aws-c5.18x',
                                 'markcoretime': [0.0138681],
                                 'minpts': {100.0},
                                 'ndalgo': {'nd'},
                                 'numborder': [3791.0],
                                 'numclusterpts': [24859769.0],
                                 'numclusters': [63.0],
                                 'numcore': [24855827.0],
                                 'numgrids': [9684.0],
                                 'numnoise': [17360.0],
                                 'numprocs': {72.0},
                                 'numpts': [24876978.0],
                                 'numpts_attr': {24876978.0},
                                 'rho': {0.01},
                                 'rounds': {3.0},
                                 'serialalgo': {'parallel'},
                                 'testcount': 1,
                                 'totaltime': [0.723352],
                                 'variable': 'rho',
                                 'x': [0.01]},
              '7D_HouseHold_2M': {'algo': {'exact'},
                                  'assignbordertime': [0.151297],
                                  'assigngridtime': [0.0581121],
                                  'buildcoreptquadtree': [-1],
                                  'buildgetnbrkdt': [0.0467339],
                                  'clustercoretime': [0.220161],
                                  'config-id': '1118-real4',
                                  'configuration': 'our-exact-bucketing '
                                                   '(re-test for 3dgeolife '
                                                   'eps=80 timing): kdt scans '
                                                   'bothsides, jemalloc, '
                                                   'bucketing, array kdt, long '
                                                   'variable type, double '
                                                   'datatype, commit:',
                                  'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                  'dataset': '7D_HouseHold_2M.pbbs',
                                  'dim': {7.0},
                                  'dimname': '7D_HouseHold_',
                                  'eps': {2000.0},
                                  'machine': 'aws-c5.18x',
                                  'markcoretime': [4.57081],
                                  'minpts': {100.0},
                                  'ndalgo': {'nd'},
                                  'numborder': [108607.0],
                                  'numclusterpts': [1721856.0],
                                  'numclusters': [27.0],
                                  'numcore': [1613187.0],
                                  'numgrids': [613546.0],
                                  'numnoise': [327486.0],
                                  'numprocs': {72.0},
                                  'numpts': [2049280.0],
                                  'numpts_attr': {2049280.0},
                                  'rho': {0.01},
                                  'rounds': {3.0},
                                  'serialalgo': {'parallel'},
                                  'testcount': 1,
                                  'totaltime': [5.09749],
                                  'variable': 'rho',
                                  'x': [0.01]}}}