plotData = {'epsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                 'assignbordertime': [0.00338888,
                                                      0.065299,
                                                      0.00644016,
                                                      0.00124884],
                                 'assigngridtime': [0.422251,
                                                    0.201209,
                                                    0.224703,
                                                    0.172968],
                                 'buildcoreptquadtree': [-1, -1, -1, -1],
                                 'buildgetnbrkdt': [0.0133021,
                                                    0.00159597,
                                                    0.000895977,
                                                    0.000774145],
                                 'clustercoretime': [0.30401,
                                                     0.657792,
                                                     33.4827,
                                                     0.823562],
                                 'config-id': '1113-real4',
                                 'configuration': 'quadtreemc_quadraticbcp: '
                                                  'kdt scans bothsides, '
                                                  'jemalloc, no bucketing, '
                                                  'array kdt, long variable '
                                                  'type for real datasets, '
                                                  'double datatype, commit:',
                                 'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                 'dataset': '3D_GeoLife_24M.pbbs',
                                 'dim': {3.0},
                                 'dimname': '3D_GeoLife_',
                                 'eps': {40.0, 80.0, 20.0, 160.0},
                                 'machine': 'aws-c5.18x',
                                 'markcoretime': [0.030349,
                                                  0.013716,
                                                  0.010359,
                                                  0.00844002],
                                 'minpts': {100.0},
                                 'ndalgo': {'nd'},
                                 'numborder': [7391.0, 3792.0, 3572.0, 990.0],
                                 'numclusterpts': [24846295.0,
                                                   24859769.0,
                                                   24868067.0,
                                                   24873703.0],
                                 'numclusters': [91.0, 63.0, 56.0, 24.0],
                                 'numcore': [24838633.0,
                                             24855826.0,
                                             24864335.0,
                                             24872696.0],
                                 'numgrids': [22919.0, 9684.0, 3612.0, 1694.0],
                                 'numnoise': [30954.0, 17360.0, 9071.0, 3292.0],
                                 'numprocs': {72.0},
                                 'numpts': [24876978.0,
                                            24876978.0,
                                            24876978.0,
                                            24876978.0],
                                 'numpts_attr': {24876978.0},
                                 'rho': {0.01},
                                 'rounds': {3.0},
                                 'serialalgo': {'parallel'},
                                 'testcount': 4,
                                 'totaltime': [1.35042,
                                               1.33667,
                                               34.0742,
                                               1.30856],
                                 'variable': 'eps',
                                 'x': [20.0, 40.0, 80.0, 160.0]},
              '7D_HouseHold_2M': {'algo': {'exact'},
                                  'assignbordertime': [0.148039,
                                                       0.0910571,
                                                       0.148993,
                                                       0.21216,
                                                       0.253563,
                                                       0.233984],
                                  'assigngridtime': [0.0401719,
                                                     0.0396159,
                                                     0.043282,
                                                     0.0410759,
                                                     0.0620749,
                                                     0.063906],
                                  'buildcoreptquadtree': [-1,
                                                          -1,
                                                          -1,
                                                          -1,
                                                          -1,
                                                          -1],
                                  'buildgetnbrkdt': [0.147555,
                                                     0.0697529,
                                                     0.0449169,
                                                     0.0356281,
                                                     0.028044,
                                                     0.019855],
                                  'clustercoretime': [0.268075,
                                                      0.152338,
                                                      0.20257,
                                                      1.12657,
                                                      1.66688,
                                                      3.61915],
                                  'config-id': '1113-real4',
                                  'configuration': 'quadtreemc_quadraticbcp: '
                                                   'kdt scans bothsides, '
                                                   'jemalloc, no bucketing, '
                                                   'array kdt, long variable '
                                                   'type for real datasets, '
                                                   'double datatype, commit:',
                                  'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                  'dataset': '7D_HouseHold_2M.pbbs',
                                  'dim': {7.0},
                                  'dimname': '7D_HouseHold_',
                                  'eps': {1000.0,
                                          1400.0,
                                          1800.0,
                                          2200.0,
                                          2600.0,
                                          3000.0},
                                  'machine': 'aws-c5.18x',
                                  'markcoretime': [2.5931,
                                                   2.56014,
                                                   2.86543,
                                                   3.85522,
                                                   4.62995,
                                                   4.76298],
                                  'minpts': {100.0},
                                  'ndalgo': {'nd'},
                                  'numborder': [123077.0,
                                                148926.0,
                                                121447.0,
                                                97189.0,
                                                76854.0,
                                                64485.0],
                                  'numclusterpts': [1220205.0,
                                                    1507976.0,
                                                    1668837.0,
                                                    1760132.0,
                                                    1815454.0,
                                                    1855854.0],
                                  'numclusters': [55.0,
                                                  30.0,
                                                  27.0,
                                                  30.0,
                                                  38.0,
                                                  48.0],
                                  'numcore': [1096868.0,
                                              1358900.0,
                                              1547291.0,
                                              1662856.0,
                                              1738555.0,
                                              1791293.0],
                                  'numgrids': [987740.0,
                                               796144.0,
                                               664053.0,
                                               570752.0,
                                               498785.0,
                                               442979.0],
                                  'numnoise': [829335.0,
                                               541454.0,
                                               380542.0,
                                               289235.0,
                                               233871.0,
                                               193502.0],
                                  'numprocs': {72.0},
                                  'numpts': [2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0],
                                  'numpts_attr': {2049280.0},
                                  'rho': {0.01},
                                  'rounds': {3.0},
                                  'serialalgo': {'parallel'},
                                  'testcount': 6,
                                  'totaltime': [3.13761,
                                                2.91543,
                                                3.38424,
                                                5.37846,
                                                6.70043,
                                                8.85552],
                                  'variable': 'eps',
                                  'x': [1000.0,
                                        1400.0,
                                        1800.0,
                                        2200.0,
                                        2600.0,
                                        3000.0]}},
 'minptsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                    'assignbordertime': [0.00442696,
                                                         0.065299,
                                                         0.00429583,
                                                         0.009197,
                                                         0.106772,
                                                         0.195661],
                                    'assigngridtime': [0.604188,
                                                       0.201209,
                                                       0.594534,
                                                       0.159351,
                                                       0.185384,
                                                       0.542054],
                                    'buildcoreptquadtree': [-1,
                                                            -1,
                                                            -1,
                                                            -1,
                                                            -1,
                                                            -1],
                                    'buildgetnbrkdt': [0.00151801,
                                                       0.00159597,
                                                       0.0015769,
                                                       0.00166512,
                                                       0.00159192,
                                                       0.00158906],
                                    'clustercoretime': [0.461767,
                                                        0.657792,
                                                        0.413477,
                                                        1.06189,
                                                        0.562688,
                                                        0.475032],
                                    'config-id': '1113-real4',
                                    'configuration': 'quadtreemc_quadraticbcp: '
                                                     'kdt scans bothsides, '
                                                     'jemalloc, no bucketing, '
                                                     'array kdt, long variable '
                                                     'type for real datasets, '
                                                     'double datatype, commit:',
                                    'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                    'dataset': '3D_GeoLife_24M.pbbs',
                                    'dim': {3.0},
                                    'dimname': '3D_GeoLife_',
                                    'eps': {40.0},
                                    'machine': 'aws-c5.18x',
                                    'markcoretime': [0.0297172,
                                                     0.013716,
                                                     0.0203578,
                                                     0.088532,
                                                     0.124368,
                                                     0.203129],
                                    'minpts': {10.0,
                                               100.0,
                                               500.0,
                                               1000.0,
                                               5000.0,
                                               10000.0},
                                    'ndalgo': {'nd'},
                                    'numborder': [320.0,
                                                  3792.0,
                                                  8875.0,
                                                  17552.0,
                                                  100174.0,
                                                  91834.0],
                                    'numclusterpts': [24875629.0,
                                                      24859769.0,
                                                      24824591.0,
                                                      24795161.0,
                                                      24501620.0,
                                                      24141105.0],
                                    'numclusters': [84.0,
                                                    63.0,
                                                    26.0,
                                                    21.0,
                                                    19.0,
                                                    8.0],
                                    'numcore': [24875293.0,
                                                24855826.0,
                                                24815466.0,
                                                24776370.0,
                                                24399987.0,
                                                24049271.0],
                                    'numgrids': [9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0],
                                    'numnoise': [1365.0,
                                                 17360.0,
                                                 52637.0,
                                                 83056.0,
                                                 376817.0,
                                                 735873.0],
                                    'numprocs': {72.0},
                                    'numpts': [24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0],
                                    'numpts_attr': {24876978.0},
                                    'rho': {0.01},
                                    'rounds': {3.0},
                                    'serialalgo': {'parallel'},
                                    'testcount': 6,
                                    'totaltime': [1.63546,
                                                  1.33667,
                                                  1.60584,
                                                  1.79893,
                                                  1.51961,
                                                  1.96448],
                                    'variable': 'minpts',
                                    'x': [10.0,
                                          100.0,
                                          500.0,
                                          1000.0,
                                          5000.0,
                                          10000.0]},
                 '7D_HouseHold_2M': {'algo': {'exact'},
                                     'assignbordertime': [0.0168571,
                                                          0.136475,
                                                          0.456927,
                                                          0.797039,
                                                          2.47388,
                                                          2.0137],
                                     'assigngridtime': [0.040524,
                                                        0.041472,
                                                        0.0372751,
                                                        0.0437801,
                                                        0.039541,
                                                        0.0374739],
                                     'buildcoreptquadtree': [-1,
                                                             -1,
                                                             -1,
                                                             -1,
                                                             -1,
                                                             -1],
                                     'buildgetnbrkdt': [0.0390661,
                                                        0.0421371,
                                                        0.0417528,
                                                        0.041785,
                                                        0.0429869,
                                                        0.040797],
                                     'clustercoretime': [0.420405,
                                                         0.203306,
                                                         0.0957181,
                                                         0.0660119,
                                                         0.0114889,
                                                         0.012634],
                                     'config-id': '1113-real4',
                                     'configuration': 'quadtreemc_quadraticbcp: '
                                                      'kdt scans bothsides, '
                                                      'jemalloc, no bucketing, '
                                                      'array kdt, long '
                                                      'variable type for real '
                                                      'datasets, double '
                                                      'datatype, commit:',
                                     'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                     'dataset': '7D_HouseHold_2M.pbbs',
                                     'dim': {7.0},
                                     'dimname': '7D_HouseHold_',
                                     'eps': {2000.0},
                                     'machine': 'aws-c5.18x',
                                     'markcoretime': [2.25472,
                                                      3.1383,
                                                      4.40254,
                                                      5.61902,
                                                      11.0451,
                                                      13.1158],
                                     'minpts': {10.0,
                                                100.0,
                                                500.0,
                                                1000.0,
                                                5000.0,
                                                10000.0},
                                     'ndalgo': {'nd'},
                                     'numborder': [42452.0,
                                                   108607.0,
                                                   174591.0,
                                                   209145.0,
                                                   318927.0,
                                                   233088.0],
                                     'numclusterpts': [1910253.0,
                                                       1721856.0,
                                                       1462453.0,
                                                       1319491.0,
                                                       874952.0,
                                                       514765.0],
                                     'numclusters': [599.0,
                                                     27.0,
                                                     13.0,
                                                     13.0,
                                                     8.0,
                                                     4.0],
                                     'numcore': [1867325.0,
                                                 1613187.0,
                                                 1287762.0,
                                                 1109405.0,
                                                 555714.0,
                                                 281677.0],
                                     'numgrids': [613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0],
                                     'numnoise': [139503.0,
                                                  327486.0,
                                                  586927.0,
                                                  730730.0,
                                                  1174639.0,
                                                  1534515.0],
                                     'numprocs': {72.0},
                                     'numpts': [2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0],
                                     'numpts_attr': {2049280.0},
                                     'rho': {0.01},
                                     'rounds': {3.0},
                                     'serialalgo': {'parallel'},
                                     'testcount': 6,
                                     'totaltime': [2.80057,
                                                   3.65518,
                                                   5.15493,
                                                   6.68568,
                                                   13.7358,
                                                   15.3654],
                                     'variable': 'minpts',
                                     'x': [10.0,
                                           100.0,
                                           500.0,
                                           1000.0,
                                           5000.0,
                                           10000.0]}},
 'numprocsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                      'assignbordertime': [0.0103629,
                                                           0.00520086,
                                                           0.00299788,
                                                           0.00269485,
                                                           0.00249815,
                                                           0.00265408,
                                                           0.065299],
                                      'assigngridtime': [1.60104,
                                                         0.52017,
                                                         0.279635,
                                                         0.44307,
                                                         0.211551,
                                                         0.145136,
                                                         0.201209],
                                      'buildcoreptquadtree': [-1,
                                                              -1,
                                                              -1,
                                                              -1,
                                                              -1,
                                                              -1,
                                                              -1],
                                      'buildgetnbrkdt': [0.00234604,
                                                         0.00123405,
                                                         0.000989914,
                                                         0.000963926,
                                                         0.00303888,
                                                         0.000995874,
                                                         0.00159597],
                                      'clustercoretime': [1.8849,
                                                          1.00534,
                                                          0.857124,
                                                          0.421123,
                                                          0.45234,
                                                          0.811675,
                                                          0.657792],
                                      'config-id': '1113-real4',
                                      'configuration': 'quadtreemc_quadraticbcp: '
                                                       'kdt scans bothsides, '
                                                       'jemalloc, no '
                                                       'bucketing, array kdt, '
                                                       'long variable type for '
                                                       'real datasets, double '
                                                       'datatype, commit:',
                                      'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                      'dataset': '3D_GeoLife_24M.pbbs',
                                      'dim': {3.0},
                                      'dimname': '3D_GeoLife_',
                                      'eps': {40.0},
                                      'machine': 'aws-c5.18x',
                                      'markcoretime': [0.179789,
                                                       0.105351,
                                                       0.041888,
                                                       0.03125,
                                                       0.048213,
                                                       0.029681,
                                                       0.013716],
                                      'minpts': {100.0},
                                      'ndalgo': {'nd'},
                                      'numborder': [3792.0,
                                                    3792.0,
                                                    3792.0,
                                                    3792.0,
                                                    3792.0,
                                                    3792.0,
                                                    3792.0],
                                      'numclusterpts': [24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0],
                                      'numclusters': [63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0],
                                      'numcore': [24855826.0,
                                                  24855826.0,
                                                  24855826.0,
                                                  24855826.0,
                                                  24855826.0,
                                                  24855826.0,
                                                  24855826.0],
                                      'numgrids': [9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0],
                                      'numnoise': [17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0],
                                      'numprocs': {1.0,
                                                   4.0,
                                                   8.0,
                                                   16.0,
                                                   24.0,
                                                   36.0,
                                                   72.0},
                                      'numpts': [24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0],
                                      'numpts_attr': {24876978.0},
                                      'rho': {0.01},
                                      'rounds': {3.0},
                                      'serialalgo': {'parallel'},
                                      'testcount': 7,
                                      'totaltime': [10.5506,
                                                    4.20707,
                                                    2.55327,
                                                    1.9164,
                                                    1.52013,
                                                    1.51992,
                                                    1.33667],
                                      'variable': 'numprocs',
                                      'x': [1.0,
                                            4.0,
                                            8.0,
                                            16.0,
                                            24.0,
                                            36.0,
                                            72.0]},
                   '7D_HouseHold_2M': {'algo': {'exact'},
                                       'assignbordertime': [3.31221,
                                                            1.13292,
                                                            0.558958,
                                                            0.289232,
                                                            0.213208,
                                                            0.143078,
                                                            0.136475],
                                       'assigngridtime': [0.924425,
                                                          0.254902,
                                                          0.12591,
                                                          0.077518,
                                                          0.0532651,
                                                          0.0407259,
                                                          0.041472],
                                       'buildcoreptquadtree': [-1,
                                                               -1,
                                                               -1,
                                                               -1,
                                                               -1,
                                                               -1,
                                                               -1],
                                       'buildgetnbrkdt': [0.736017,
                                                          0.196975,
                                                          0.103206,
                                                          0.058187,
                                                          0.0428021,
                                                          0.0355542,
                                                          0.0421371],
                                       'clustercoretime': [9.34455,
                                                           2.08118,
                                                           0.904783,
                                                           0.432182,
                                                           0.378224,
                                                           0.23063,
                                                           0.203306],
                                       'config-id': '1113-real4',
                                       'configuration': 'quadtreemc_quadraticbcp: '
                                                        'kdt scans bothsides, '
                                                        'jemalloc, no '
                                                        'bucketing, array kdt, '
                                                        'long variable type '
                                                        'for real datasets, '
                                                        'double datatype, '
                                                        'commit:',
                                       'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                       'dataset': '7D_HouseHold_2M.pbbs',
                                       'dim': {7.0},
                                       'dimname': '7D_HouseHold_',
                                       'eps': {2000.0},
                                       'machine': 'aws-c5.18x',
                                       'markcoretime': [93.9183,
                                                        25.5101,
                                                        12.4118,
                                                        6.49466,
                                                        4.65686,
                                                        3.29534,
                                                        3.1383],
                                       'minpts': {100.0},
                                       'ndalgo': {'nd'},
                                       'numborder': [108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0],
                                       'numclusterpts': [1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0],
                                       'numclusters': [27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0],
                                       'numcore': [1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0],
                                       'numgrids': [613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0],
                                       'numnoise': [327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0],
                                       'numprocs': {1.0,
                                                    4.0,
                                                    8.0,
                                                    16.0,
                                                    24.0,
                                                    36.0,
                                                    72.0},
                                       'numpts': [2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0],
                                       'numpts_attr': {2049280.0},
                                       'rho': {0.01},
                                       'rounds': {3.0},
                                       'serialalgo': {'parallel'},
                                       'testcount': 7,
                                       'totaltime': [108.566,
                                                     29.3488,
                                                     14.2592,
                                                     7.49432,
                                                     5.47401,
                                                     3.87406,
                                                     3.65518],
                                       'variable': 'numprocs',
                                       'x': [1.0,
                                             4.0,
                                             8.0,
                                             16.0,
                                             24.0,
                                             36.0,
                                             72.0]}},
 'numptsPlots': {},
 'rhoPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                 'assignbordertime': [0.065299],
                                 'assigngridtime': [0.201209],
                                 'buildcoreptquadtree': [-1],
                                 'buildgetnbrkdt': [0.00159597],
                                 'clustercoretime': [0.657792],
                                 'config-id': '1113-real4',
                                 'configuration': 'quadtreemc_quadraticbcp: '
                                                  'kdt scans bothsides, '
                                                  'jemalloc, no bucketing, '
                                                  'array kdt, long variable '
                                                  'type for real datasets, '
                                                  'double datatype, commit:',
                                 'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                 'dataset': '3D_GeoLife_24M.pbbs',
                                 'dim': {3.0},
                                 'dimname': '3D_GeoLife_',
                                 'eps': {40.0},
                                 'machine': 'aws-c5.18x',
                                 'markcoretime': [0.013716],
                                 'minpts': {100.0},
                                 'ndalgo': {'nd'},
                                 'numborder': [3792.0],
                                 'numclusterpts': [24859769.0],
                                 'numclusters': [63.0],
                                 'numcore': [24855826.0],
                                 'numgrids': [9684.0],
                                 'numnoise': [17360.0],
                                 'numprocs': {72.0},
                                 'numpts': [24876978.0],
                                 'numpts_attr': {24876978.0},
                                 'rho': {0.01},
                                 'rounds': {3.0},
                                 'serialalgo': {'parallel'},
                                 'testcount': 1,
                                 'totaltime': [1.33667],
                                 'variable': 'rho',
                                 'x': [0.01]},
              '7D_HouseHold_2M': {'algo': {'exact'},
                                  'assignbordertime': [0.136475],
                                  'assigngridtime': [0.041472],
                                  'buildcoreptquadtree': [-1],
                                  'buildgetnbrkdt': [0.0421371],
                                  'clustercoretime': [0.203306],
                                  'config-id': '1113-real4',
                                  'configuration': 'quadtreemc_quadraticbcp: '
                                                   'kdt scans bothsides, '
                                                   'jemalloc, no bucketing, '
                                                   'array kdt, long variable '
                                                   'type for real datasets, '
                                                   'double datatype, commit:',
                                  'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                  'dataset': '7D_HouseHold_2M.pbbs',
                                  'dim': {7.0},
                                  'dimname': '7D_HouseHold_',
                                  'eps': {2000.0},
                                  'machine': 'aws-c5.18x',
                                  'markcoretime': [3.1383],
                                  'minpts': {100.0},
                                  'ndalgo': {'nd'},
                                  'numborder': [108607.0],
                                  'numclusterpts': [1721856.0],
                                  'numclusters': [27.0],
                                  'numcore': [1613187.0],
                                  'numgrids': [613546.0],
                                  'numnoise': [327486.0],
                                  'numprocs': {72.0},
                                  'numpts': [2049280.0],
                                  'numpts_attr': {2049280.0},
                                  'rho': {0.01},
                                  'rounds': {3.0},
                                  'serialalgo': {'parallel'},
                                  'testcount': 1,
                                  'totaltime': [3.65518],
                                  'variable': 'rho',
                                  'x': [0.01]}}}