plotData = {'epsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                 'assignbordertime': [0.00294089,
                                                      0.00392008,
                                                      0.00416207,
                                                      0.00164008],
                                 'assigngridtime': [0.156777,
                                                    0.150802,
                                                    0.146995,
                                                    0.149466],
                                 'buildcoreptquadtree': [0.301932,
                                                         0.293648,
                                                         0.282462,
                                                         0.272509],
                                 'buildgetnbrkdt': [0.00134397,
                                                    0.00106382,
                                                    0.000372171,
                                                    0.000360012],
                                 'clustercoretime': [0.0307171,
                                                     0.0228119,
                                                     0.140764,
                                                     0.136695],
                                 'config-id': '07-07-real2',
                                 'configuration': 'nd-approx/nd-exactbcp/nd-exactquadtree/nd-exactbcpbucketing: '
                                                  'after the kdtree scanleft '
                                                  'change, to obtain a new '
                                                  'result for household '
                                                  'dataset; jemalloc for all, '
                                                  'bucketing only for '
                                                  'nd-exactquadtree, array kdt '
                                                  'for all, array quadtree for '
                                                  'any config that involve a '
                                                  'quadtree, long variable '
                                                  'type for any config that '
                                                  'involve a quadtree, double '
                                                  'datatype, commit: ',
                                 'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                 'dataset': '3D_GeoLife_24M.pbbs',
                                 'dim': {3.0},
                                 'dimname': '3D_GeoLife_',
                                 'eps': {40.0, 80.0, 20.0, 160.0},
                                 'machine': 'aws-c5.18x',
                                 'markcoretime': [0.410522,
                                                  0.34599,
                                                  0.311707,
                                                  0.28629],
                                 'minpts': {100.0},
                                 'ndalgo': {'nd'},
                                 'numborder': [7391.0, 3792.0, 3572.0, 990.0],
                                 'numclusterpts': [24846295.0,
                                                   24859769.0,
                                                   24868067.0,
                                                   24873703.0],
                                 'numclusters': [91.0, 63.0, 56.0, 24.0],
                                 'numcore': [24838633.0,
                                             24855826.0,
                                             24864335.0,
                                             24872696.0],
                                 'numgrids': [22919.0, 9684.0, 3612.0, 1694.0],
                                 'numnoise': [30954.0, 17360.0, 9071.0, 3292.0],
                                 'numprocs': {72.0},
                                 'numpts': [24876978.0,
                                            24876978.0,
                                            24876978.0,
                                            24876978.0],
                                 'numpts_attr': {24876978.0},
                                 'rho': {0.01},
                                 'rounds': {3.0},
                                 'serialalgo': {'parallel'},
                                 'testcount': 4,
                                 'totaltime': [0.904739,
                                               0.818496,
                                               0.886663,
                                               0.847234],
                                 'variable': 'eps',
                                 'x': [20.0, 40.0, 80.0, 160.0]},
              '7D_HouseHold_2M': {'algo': {'exact'},
                                  'assignbordertime': [0.148632,
                                                       0.092881,
                                                       0.150005,
                                                       0.219883,
                                                       0.247575,
                                                       0.223614],
                                  'assigngridtime': [0.0356691,
                                                     0.0356691,
                                                     0.0339541,
                                                     0.035598,
                                                     0.0316939,
                                                     0.063673],
                                  'buildcoreptquadtree': [0.00923896,
                                                          0.010792,
                                                          0.0599329,
                                                          0.015718,
                                                          0.0679629,
                                                          0.037014],
                                  'buildgetnbrkdt': [0.16885,
                                                     0.0746219,
                                                     0.0582819,
                                                     0.041682,
                                                     0.0257449,
                                                     0.0174739],
                                  'clustercoretime': [0.228638,
                                                      0.155715,
                                                      0.212464,
                                                      0.532681,
                                                      1.0226,
                                                      3.9561],
                                  'config-id': '07-07-real2',
                                  'configuration': 'nd-approx/nd-exactbcp/nd-exactquadtree/nd-exactbcpbucketing: '
                                                   'after the kdtree scanleft '
                                                   'change, to obtain a new '
                                                   'result for household '
                                                   'dataset; jemalloc for all, '
                                                   'bucketing only for '
                                                   'nd-exactquadtree, array '
                                                   'kdt for all, array '
                                                   'quadtree for any config '
                                                   'that involve a quadtree, '
                                                   'long variable type for any '
                                                   'config that involve a '
                                                   'quadtree, double datatype, '
                                                   'commit: ',
                                  'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                  'dataset': '7D_HouseHold_2M.pbbs',
                                  'dim': {7.0},
                                  'dimname': '7D_HouseHold_',
                                  'eps': {1000.0,
                                          1400.0,
                                          1800.0,
                                          2200.0,
                                          2600.0,
                                          3000.0},
                                  'machine': 'aws-c5.18x',
                                  'markcoretime': [2.6616,
                                                   2.71193,
                                                   3.13148,
                                                   4.31202,
                                                   4.91987,
                                                   5.2973],
                                  'minpts': {100.0},
                                  'ndalgo': {'nd'},
                                  'numborder': [123077.0,
                                                148926.0,
                                                121447.0,
                                                97189.0,
                                                76854.0,
                                                64485.0],
                                  'numclusterpts': [1220205.0,
                                                    1507976.0,
                                                    1668837.0,
                                                    1760132.0,
                                                    1815454.0,
                                                    1855854.0],
                                  'numclusters': [55.0,
                                                  30.0,
                                                  27.0,
                                                  30.0,
                                                  38.0,
                                                  48.0],
                                  'numcore': [1096868.0,
                                              1358900.0,
                                              1547291.0,
                                              1662856.0,
                                              1738555.0,
                                              1791293.0],
                                  'numgrids': [987740.0,
                                               796144.0,
                                               664053.0,
                                               570752.0,
                                               498785.0,
                                               442979.0],
                                  'numnoise': [829335.0,
                                               541454.0,
                                               380542.0,
                                               289235.0,
                                               233871.0,
                                               193502.0],
                                  'numprocs': {72.0},
                                  'numpts': [2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0],
                                  'numpts_attr': {2049280.0},
                                  'rho': {0.01},
                                  'rounds': {3.0},
                                  'serialalgo': {'parallel'},
                                  'testcount': 6,
                                  'totaltime': [3.27126,
                                                3.11759,
                                                3.66534,
                                                5.19728,
                                                6.3551,
                                                9.683],
                                  'variable': 'eps',
                                  'x': [1000.0,
                                        1400.0,
                                        1800.0,
                                        2200.0,
                                        2600.0,
                                        3000.0]}},
 'minptsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                    'assignbordertime': [0.00386786,
                                                         0.00392008,
                                                         0.003685,
                                                         0.00886798,
                                                         0.101306,
                                                         0.185506],
                                    'assigngridtime': [0.152509,
                                                       0.150802,
                                                       0.149299,
                                                       0.148213,
                                                       0.152209,
                                                       0.149541],
                                    'buildcoreptquadtree': [0.290312,
                                                            0.293648,
                                                            0.291183,
                                                            0.291452,
                                                            0.289931,
                                                            0.293166],
                                    'buildgetnbrkdt': [0.00102806,
                                                       0.00106382,
                                                       0.000974178,
                                                       0.00109005,
                                                       0.00102186,
                                                       0.00107408],
                                    'clustercoretime': [0.0257151,
                                                        0.0228119,
                                                        0.0194402,
                                                        0.0170121,
                                                        0.0171471,
                                                        0.0176859],
                                    'config-id': '07-07-real2',
                                    'configuration': 'nd-approx/nd-exactbcp/nd-exactquadtree/nd-exactbcpbucketing: '
                                                     'after the kdtree '
                                                     'scanleft change, to '
                                                     'obtain a new result for '
                                                     'household dataset; '
                                                     'jemalloc for all, '
                                                     'bucketing only for '
                                                     'nd-exactquadtree, array '
                                                     'kdt for all, array '
                                                     'quadtree for any config '
                                                     'that involve a quadtree, '
                                                     'long variable type for '
                                                     'any config that involve '
                                                     'a quadtree, double '
                                                     'datatype, commit: ',
                                    'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                    'dataset': '3D_GeoLife_24M.pbbs',
                                    'dim': {3.0},
                                    'dimname': '3D_GeoLife_',
                                    'eps': {40.0},
                                    'machine': 'aws-c5.18x',
                                    'markcoretime': [0.343217,
                                                     0.34599,
                                                     0.349756,
                                                     0.371402,
                                                     0.460865,
                                                     0.523065],
                                    'minpts': {10.0,
                                               100.0,
                                               500.0,
                                               1000.0,
                                               5000.0,
                                               10000.0},
                                    'ndalgo': {'nd'},
                                    'numborder': [320.0,
                                                  3792.0,
                                                  8875.0,
                                                  17552.0,
                                                  100174.0,
                                                  91834.0],
                                    'numclusterpts': [24875629.0,
                                                      24859769.0,
                                                      24824591.0,
                                                      24795161.0,
                                                      24501620.0,
                                                      24141105.0],
                                    'numclusters': [84.0,
                                                    63.0,
                                                    26.0,
                                                    21.0,
                                                    19.0,
                                                    8.0],
                                    'numcore': [24875293.0,
                                                24855826.0,
                                                24815466.0,
                                                24776370.0,
                                                24399987.0,
                                                24049271.0],
                                    'numgrids': [9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0],
                                    'numnoise': [1365.0,
                                                 17360.0,
                                                 52637.0,
                                                 83056.0,
                                                 376817.0,
                                                 735873.0],
                                    'numprocs': {72.0},
                                    'numpts': [24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0],
                                    'numpts_attr': {24876978.0},
                                    'rho': {0.01},
                                    'rounds': {3.0},
                                    'serialalgo': {'parallel'},
                                    'testcount': 6,
                                    'totaltime': [0.816826,
                                                  0.818496,
                                                  0.814666,
                                                  0.83824,
                                                  1.02276,
                                                  1.17037],
                                    'variable': 'minpts',
                                    'x': [10.0,
                                          100.0,
                                          500.0,
                                          1000.0,
                                          5000.0,
                                          10000.0]},
                 '7D_HouseHold_2M': {'algo': {'exact'},
                                     'assignbordertime': [0.0198741,
                                                          0.144128,
                                                          0.470986,
                                                          0.85321,
                                                          2.65052,
                                                          2.24601],
                                     'assigngridtime': [0.056752,
                                                        0.033298,
                                                        0.0336769,
                                                        0.032079,
                                                        0.031961,
                                                        0.033469],
                                     'buildcoreptquadtree': [0.0143449,
                                                             0.06056,
                                                             0.0430741,
                                                             0.034265,
                                                             0.017627,
                                                             0.0100081],
                                     'buildgetnbrkdt': [0.0489659,
                                                        0.0480249,
                                                        0.0451519,
                                                        0.0428989,
                                                        0.060535,
                                                        0.0430601],
                                     'clustercoretime': [0.467231,
                                                         0.192426,
                                                         0.092366,
                                                         0.066581,
                                                         0.0153301,
                                                         0.00829887],
                                     'config-id': '07-07-real2',
                                     'configuration': 'nd-approx/nd-exactbcp/nd-exactquadtree/nd-exactbcpbucketing: '
                                                      'after the kdtree '
                                                      'scanleft change, to '
                                                      'obtain a new result for '
                                                      'household dataset; '
                                                      'jemalloc for all, '
                                                      'bucketing only for '
                                                      'nd-exactquadtree, array '
                                                      'kdt for all, array '
                                                      'quadtree for any config '
                                                      'that involve a '
                                                      'quadtree, long variable '
                                                      'type for any config '
                                                      'that involve a '
                                                      'quadtree, double '
                                                      'datatype, commit: ',
                                     'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                     'dataset': '7D_HouseHold_2M.pbbs',
                                     'dim': {7.0},
                                     'dimname': '7D_HouseHold_',
                                     'eps': {2000.0},
                                     'machine': 'aws-c5.18x',
                                     'markcoretime': [2.29845,
                                                      3.38911,
                                                      4.75684,
                                                      5.73927,
                                                      11.1774,
                                                      13.1737],
                                     'minpts': {10.0,
                                                100.0,
                                                500.0,
                                                1000.0,
                                                5000.0,
                                                10000.0},
                                     'ndalgo': {'nd'},
                                     'numborder': [42452.0,
                                                   108607.0,
                                                   174591.0,
                                                   209145.0,
                                                   318927.0,
                                                   233088.0],
                                     'numclusterpts': [1910253.0,
                                                       1721856.0,
                                                       1462453.0,
                                                       1319491.0,
                                                       874952.0,
                                                       514765.0],
                                     'numclusters': [599.0,
                                                     27.0,
                                                     13.0,
                                                     13.0,
                                                     8.0,
                                                     4.0],
                                     'numcore': [1867325.0,
                                                 1613187.0,
                                                 1287762.0,
                                                 1109405.0,
                                                 555714.0,
                                                 281677.0],
                                     'numgrids': [613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0],
                                     'numnoise': [139503.0,
                                                  327486.0,
                                                  586927.0,
                                                  730730.0,
                                                  1174639.0,
                                                  1534515.0],
                                     'numprocs': {72.0},
                                     'numpts': [2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0],
                                     'numpts_attr': {2049280.0},
                                     'rho': {0.01},
                                     'rounds': {3.0},
                                     'serialalgo': {'parallel'},
                                     'testcount': 6,
                                     'totaltime': [2.93975,
                                                   3.89742,
                                                   5.49368,
                                                   6.84169,
                                                   14.0368,
                                                   15.6226],
                                     'variable': 'minpts',
                                     'x': [10.0,
                                           100.0,
                                           500.0,
                                           1000.0,
                                           5000.0,
                                           10000.0]}},
 'numprocsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                      'assignbordertime': [0.0100172,
                                                           0.00485802,
                                                           0.00271893,
                                                           0.00269604,
                                                           0.00232792,
                                                           0.00220609,
                                                           0.00392008],
                                      'assigngridtime': [1.57178,
                                                         0.478957,
                                                         0.278114,
                                                         0.17533,
                                                         0.153867,
                                                         0.141767,
                                                         0.150802],
                                      'buildcoreptquadtree': [6.77441,
                                                              2.37414,
                                                              1.35545,
                                                              0.763843,
                                                              0.539706,
                                                              0.38802,
                                                              0.293648],
                                      'buildgetnbrkdt': [0.000604868,
                                                         0.000666857,
                                                         0.000623941,
                                                         0.000668049,
                                                         0.000616789,
                                                         0.000637054,
                                                         0.00106382],
                                      'clustercoretime': [0.245316,
                                                          0.087009,
                                                          0.0473289,
                                                          0.028806,
                                                          0.0250452,
                                                          0.022639,
                                                          0.0228119],
                                      'config-id': '07-07-real2',
                                      'configuration': 'nd-approx/nd-exactbcp/nd-exactquadtree/nd-exactbcpbucketing: '
                                                       'after the kdtree '
                                                       'scanleft change, to '
                                                       'obtain a new result '
                                                       'for household dataset; '
                                                       'jemalloc for all, '
                                                       'bucketing only for '
                                                       'nd-exactquadtree, '
                                                       'array kdt for all, '
                                                       'array quadtree for any '
                                                       'config that involve a '
                                                       'quadtree, long '
                                                       'variable type for any '
                                                       'config that involve a '
                                                       'quadtree, double '
                                                       'datatype, commit: ',
                                      'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                      'dataset': '3D_GeoLife_24M.pbbs',
                                      'dim': {3.0},
                                      'dimname': '3D_GeoLife_',
                                      'eps': {40.0},
                                      'machine': 'aws-c5.18x',
                                      'markcoretime': [7.19777,
                                                       2.43568,
                                                       1.3494,
                                                       0.792504,
                                                       0.559924,
                                                       0.428968,
                                                       0.34599],
                                      'minpts': {100.0},
                                      'ndalgo': {'nd'},
                                      'numborder': [3792.0,
                                                    3792.0,
                                                    3792.0,
                                                    3792.0,
                                                    3792.0,
                                                    3792.0,
                                                    3792.0],
                                      'numclusterpts': [24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0],
                                      'numclusters': [63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0],
                                      'numcore': [24855826.0,
                                                  24855826.0,
                                                  24855826.0,
                                                  24855826.0,
                                                  24855826.0,
                                                  24855826.0,
                                                  24855826.0],
                                      'numgrids': [9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0],
                                      'numnoise': [17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0],
                                      'numprocs': {1.0,
                                                   4.0,
                                                   8.0,
                                                   16.0,
                                                   24.0,
                                                   36.0,
                                                   72.0},
                                      'numpts': [24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0],
                                      'numpts_attr': {24876978.0},
                                      'rho': {0.01},
                                      'rounds': {3.0},
                                      'serialalgo': {'parallel'},
                                      'testcount': 7,
                                      'totaltime': [15.8003,
                                                    5.38179,
                                                    3.03415,
                                                    1.76407,
                                                    1.2818,
                                                    0.984383,
                                                    0.818496],
                                      'variable': 'numprocs',
                                      'x': [1.0,
                                            4.0,
                                            8.0,
                                            16.0,
                                            24.0,
                                            36.0,
                                            72.0]},
                   '7D_HouseHold_2M': {'algo': {'exact'},
                                       'assignbordertime': [3.41657,
                                                            0.979501,
                                                            0.528991,
                                                            0.293083,
                                                            0.207364,
                                                            0.148814,
                                                            0.144128],
                                       'assigngridtime': [0.78302,
                                                          0.241041,
                                                          0.128206,
                                                          0.064532,
                                                          0.0476241,
                                                          0.0359259,
                                                          0.033298],
                                       'buildcoreptquadtree': [0.807635,
                                                               0.242948,
                                                               0.132939,
                                                               0.094764,
                                                               0.0812209,
                                                               0.07811,
                                                               0.06056],
                                       'buildgetnbrkdt': [0.762002,
                                                          0.214372,
                                                          0.111531,
                                                          0.0610361,
                                                          0.0463409,
                                                          0.0366809,
                                                          0.0480249],
                                       'clustercoretime': [5.85793,
                                                           1.27885,
                                                           0.588841,
                                                           0.342169,
                                                           0.294182,
                                                           0.241765,
                                                           0.192426],
                                       'config-id': '07-07-real2',
                                       'configuration': 'nd-approx/nd-exactbcp/nd-exactquadtree/nd-exactbcpbucketing: '
                                                        'after the kdtree '
                                                        'scanleft change, to '
                                                        'obtain a new result '
                                                        'for household '
                                                        'dataset; jemalloc for '
                                                        'all, bucketing only '
                                                        'for nd-exactquadtree, '
                                                        'array kdt for all, '
                                                        'array quadtree for '
                                                        'any config that '
                                                        'involve a quadtree, '
                                                        'long variable type '
                                                        'for any config that '
                                                        'involve a quadtree, '
                                                        'double datatype, '
                                                        'commit: ',
                                       'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                       'dataset': '7D_HouseHold_2M.pbbs',
                                       'dim': {7.0},
                                       'dimname': '7D_HouseHold_',
                                       'eps': {2000.0},
                                       'machine': 'aws-c5.18x',
                                       'markcoretime': [98.2399,
                                                        25.4386,
                                                        13.0921,
                                                        6.77396,
                                                        4.77909,
                                                        3.48973,
                                                        3.38911],
                                       'minpts': {100.0},
                                       'ndalgo': {'nd'},
                                       'numborder': [108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0],
                                       'numclusterpts': [1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0],
                                       'numclusters': [27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0],
                                       'numcore': [1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0],
                                       'numgrids': [613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0],
                                       'numnoise': [327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0],
                                       'numprocs': {1.0,
                                                    4.0,
                                                    8.0,
                                                    16.0,
                                                    24.0,
                                                    36.0,
                                                    72.0},
                                       'numpts': [2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0],
                                       'numpts_attr': {2049280.0},
                                       'rho': {0.01},
                                       'rounds': {3.0},
                                       'serialalgo': {'parallel'},
                                       'testcount': 7,
                                       'totaltime': [109.94,
                                                     28.5267,
                                                     14.6787,
                                                     7.70548,
                                                     5.50751,
                                                     4.06032,
                                                     3.89742],
                                       'variable': 'numprocs',
                                       'x': [1.0,
                                             4.0,
                                             8.0,
                                             16.0,
                                             24.0,
                                             36.0,
                                             72.0]}},
 'numptsPlots': {}}