plotData = {'epsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                 'assignbordertime': [0.00293112,
                                                      0.00398993,
                                                      0.00430584,
                                                      0.00135016],
                                 'assigngridtime': [0.153948,
                                                    0.15243,
                                                    0.149395,
                                                    0.156043],
                                 'buildcoreptquadtree': [-1, -1, -1, -1],
                                 'buildgetnbrkdt': [0.00171304,
                                                    0.00125694,
                                                    0.000435829,
                                                    0.000396013],
                                 'clustercoretime': [0.320908,
                                                     0.440317,
                                                     0.287188,
                                                     0.315126],
                                 'config-id': '07-07-real2',
                                 'configuration': 'nd-approx/nd-exactbcp/nd-exactquadtree/nd-exactbcpbucketing: '
                                                  'after the kdtree scanleft '
                                                  'change, to obtain a new '
                                                  'result for household '
                                                  'dataset; jemalloc for all, '
                                                  'bucketing only for '
                                                  'nd-exactquadtree, array kdt '
                                                  'for all, array quadtree for '
                                                  'any config that involve a '
                                                  'quadtree, long variable '
                                                  'type for any config that '
                                                  'involve a quadtree, double '
                                                  'datatype, commit: ',
                                 'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                 'dataset': '3D_GeoLife_24M.pbbs',
                                 'dim': {3.0},
                                 'dimname': '3D_GeoLife_',
                                 'eps': {40.0, 80.0, 20.0, 160.0},
                                 'machine': 'aws-c5.18x',
                                 'markcoretime': [0.0615351,
                                                  0.018616,
                                                  0.0930982,
                                                  0.00901794],
                                 'minpts': {100.0},
                                 'ndalgo': {'nd'},
                                 'numborder': [7391.0, 3791.0, 3572.0, 990.0],
                                 'numclusterpts': [24846295.0,
                                                   24859769.0,
                                                   24868067.0,
                                                   24873703.0],
                                 'numclusters': [91.0, 63.0, 56.0, 24.0],
                                 'numcore': [24838633.0,
                                             24855827.0,
                                             24864335.0,
                                             24872696.0],
                                 'numgrids': [22919.0, 9684.0, 3612.0, 1694.0],
                                 'numnoise': [30954.0, 17360.0, 9071.0, 3292.0],
                                 'numprocs': {72.0},
                                 'numpts': [24876978.0,
                                            24876978.0,
                                            24876978.0,
                                            24876978.0],
                                 'numpts_attr': {24876978.0},
                                 'rho': {0.01},
                                 'rounds': {3.0},
                                 'serialalgo': {'parallel'},
                                 'testcount': 4,
                                 'totaltime': [0.541319,
                                               0.616913,
                                               0.53463,
                                               0.482111],
                                 'variable': 'eps',
                                 'x': [20.0, 40.0, 80.0, 160.0]},
              '7D_HouseHold_2M': {'algo': {'exact'},
                                  'assignbordertime': [0.1366,
                                                       0.0837259,
                                                       0.135306,
                                                       0.195245,
                                                       0.218418,
                                                       0.208793],
                                  'assigngridtime': [0.0326819,
                                                     0.029943,
                                                     0.027303,
                                                     0.034637,
                                                     0.0427878,
                                                     0.0311768],
                                  'buildcoreptquadtree': [-1,
                                                          -1,
                                                          -1,
                                                          -1,
                                                          -1,
                                                          -1],
                                  'buildgetnbrkdt': [0.106126,
                                                     0.0581069,
                                                     0.0404899,
                                                     0.035984,
                                                     0.0192351,
                                                     0.017364],
                                  'clustercoretime': [0.271531,
                                                      0.144801,
                                                      0.178328,
                                                      1.19839,
                                                      1.79478,
                                                      5.11817],
                                  'config-id': '07-07-real2',
                                  'configuration': 'nd-approx/nd-exactbcp/nd-exactquadtree/nd-exactbcpbucketing: '
                                                   'after the kdtree scanleft '
                                                   'change, to obtain a new '
                                                   'result for household '
                                                   'dataset; jemalloc for all, '
                                                   'bucketing only for '
                                                   'nd-exactquadtree, array '
                                                   'kdt for all, array '
                                                   'quadtree for any config '
                                                   'that involve a quadtree, '
                                                   'long variable type for any '
                                                   'config that involve a '
                                                   'quadtree, double datatype, '
                                                   'commit: ',
                                  'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                  'dataset': '7D_HouseHold_2M.pbbs',
                                  'dim': {7.0},
                                  'dimname': '7D_HouseHold_',
                                  'eps': {1000.0,
                                          1400.0,
                                          1800.0,
                                          2200.0,
                                          2600.0,
                                          3000.0},
                                  'machine': 'aws-c5.18x',
                                  'markcoretime': [2.018,
                                                   2.30863,
                                                   3.23291,
                                                   7.44666,
                                                   8.16633,
                                                   8.87556],
                                  'minpts': {100.0},
                                  'ndalgo': {'nd'},
                                  'numborder': [123077.0,
                                                148926.0,
                                                121447.0,
                                                97189.0,
                                                76854.0,
                                                64485.0],
                                  'numclusterpts': [1220205.0,
                                                    1507976.0,
                                                    1668837.0,
                                                    1760132.0,
                                                    1815454.0,
                                                    1855854.0],
                                  'numclusters': [55.0,
                                                  30.0,
                                                  27.0,
                                                  30.0,
                                                  38.0,
                                                  48.0],
                                  'numcore': [1096868.0,
                                              1358900.0,
                                              1547291.0,
                                              1662856.0,
                                              1738555.0,
                                              1791293.0],
                                  'numgrids': [987740.0,
                                               796144.0,
                                               664053.0,
                                               570752.0,
                                               498785.0,
                                               442979.0],
                                  'numnoise': [829335.0,
                                               541454.0,
                                               380542.0,
                                               289235.0,
                                               233871.0,
                                               193502.0],
                                  'numprocs': {72.0},
                                  'numpts': [2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0],
                                  'numpts_attr': {2049280.0},
                                  'rho': {0.01},
                                  'rounds': {3.0},
                                  'serialalgo': {'parallel'},
                                  'testcount': 6,
                                  'totaltime': [2.57568,
                                                2.63796,
                                                3.63495,
                                                8.93084,
                                                10.3305,
                                                14.2716],
                                  'variable': 'eps',
                                  'x': [1000.0,
                                        1400.0,
                                        1800.0,
                                        2200.0,
                                        2600.0,
                                        3000.0]}},
 'minptsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                    'assignbordertime': [0.00384498,
                                                         0.00398993,
                                                         0.00371814,
                                                         0.00867796,
                                                         0.101666,
                                                         0.18765],
                                    'assigngridtime': [0.151662,
                                                       0.15243,
                                                       0.152789,
                                                       0.150715,
                                                       0.156025,
                                                       0.15118],
                                    'buildcoreptquadtree': [-1,
                                                            -1,
                                                            -1,
                                                            -1,
                                                            -1,
                                                            -1],
                                    'buildgetnbrkdt': [0.00129509,
                                                       0.00125694,
                                                       0.00122499,
                                                       0.0012238,
                                                       0.00128603,
                                                       0.00122499],
                                    'clustercoretime': [0.443972,
                                                        0.440317,
                                                        0.44647,
                                                        0.44065,
                                                        0.428105,
                                                        0.423834],
                                    'config-id': '07-07-real2',
                                    'configuration': 'nd-approx/nd-exactbcp/nd-exactquadtree/nd-exactbcpbucketing: '
                                                     'after the kdtree '
                                                     'scanleft change, to '
                                                     'obtain a new result for '
                                                     'household dataset; '
                                                     'jemalloc for all, '
                                                     'bucketing only for '
                                                     'nd-exactquadtree, array '
                                                     'kdt for all, array '
                                                     'quadtree for any config '
                                                     'that involve a quadtree, '
                                                     'long variable type for '
                                                     'any config that involve '
                                                     'a quadtree, double '
                                                     'datatype, commit: ',
                                    'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                    'dataset': '3D_GeoLife_24M.pbbs',
                                    'dim': {3.0},
                                    'dimname': '3D_GeoLife_',
                                    'eps': {40.0},
                                    'machine': 'aws-c5.18x',
                                    'markcoretime': [0.0159781,
                                                     0.018616,
                                                     0.0486028,
                                                     0.123454,
                                                     0.867408,
                                                     2.32605],
                                    'minpts': {10.0,
                                               100.0,
                                               500.0,
                                               1000.0,
                                               5000.0,
                                               10000.0},
                                    'ndalgo': {'nd'},
                                    'numborder': [320.0,
                                                  3791.0,
                                                  8860.0,
                                                  17546.0,
                                                  100090.0,
                                                  91985.0],
                                    'numclusterpts': [24875629.0,
                                                      24859769.0,
                                                      24824591.0,
                                                      24795161.0,
                                                      24501634.0,
                                                      24141423.0],
                                    'numclusters': [84.0,
                                                    63.0,
                                                    26.0,
                                                    21.0,
                                                    19.0,
                                                    8.0],
                                    'numcore': [24875293.0,
                                                24855827.0,
                                                24815481.0,
                                                24776376.0,
                                                24400085.0,
                                                24049438.0],
                                    'numgrids': [9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0],
                                    'numnoise': [1365.0,
                                                 17360.0,
                                                 52637.0,
                                                 83056.0,
                                                 376803.0,
                                                 735555.0],
                                    'numprocs': {72.0},
                                    'numpts': [24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0],
                                    'numpts_attr': {24876978.0},
                                    'rho': {0.01},
                                    'rounds': {3.0},
                                    'serialalgo': {'parallel'},
                                    'testcount': 6,
                                    'totaltime': [0.617045,
                                                  0.616913,
                                                  0.653097,
                                                  0.72552,
                                                  1.55488,
                                                  3.09036],
                                    'variable': 'minpts',
                                    'x': [10.0,
                                          100.0,
                                          500.0,
                                          1000.0,
                                          5000.0,
                                          10000.0]},
                 '7D_HouseHold_2M': {'algo': {'exact'},
                                     'assignbordertime': [0.016397,
                                                          0.130963,
                                                          0.406264,
                                                          0.799581,
                                                          2.52851,
                                                          2.13503],
                                     'assigngridtime': [0.030941,
                                                        0.029834,
                                                        0.0306032,
                                                        0.035567,
                                                        0.0359311,
                                                        0.0279322],
                                     'buildcoreptquadtree': [-1,
                                                             -1,
                                                             -1,
                                                             -1,
                                                             -1,
                                                             -1],
                                     'buildgetnbrkdt': [0.0363011,
                                                        0.0295811,
                                                        0.031019,
                                                        0.0554922,
                                                        0.038228,
                                                        0.0330958],
                                     'clustercoretime': [0.369947,
                                                         0.196477,
                                                         0.104098,
                                                         0.063798,
                                                         0.0178201,
                                                         0.0194211],
                                     'config-id': '07-07-real2',
                                     'configuration': 'nd-approx/nd-exactbcp/nd-exactquadtree/nd-exactbcpbucketing: '
                                                      'after the kdtree '
                                                      'scanleft change, to '
                                                      'obtain a new result for '
                                                      'household dataset; '
                                                      'jemalloc for all, '
                                                      'bucketing only for '
                                                      'nd-exactquadtree, array '
                                                      'kdt for all, array '
                                                      'quadtree for any config '
                                                      'that involve a '
                                                      'quadtree, long variable '
                                                      'type for any config '
                                                      'that involve a '
                                                      'quadtree, double '
                                                      'datatype, commit: ',
                                     'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                     'dataset': '7D_HouseHold_2M.pbbs',
                                     'dim': {7.0},
                                     'dimname': '7D_HouseHold_',
                                     'eps': {2000.0},
                                     'machine': 'aws-c5.18x',
                                     'markcoretime': [2.05946,
                                                      3.36061,
                                                      5.09814,
                                                      6.19156,
                                                      12.7452,
                                                      15.8771],
                                     'minpts': {10.0,
                                                100.0,
                                                500.0,
                                                1000.0,
                                                5000.0,
                                                10000.0},
                                     'ndalgo': {'nd'},
                                     'numborder': [42452.0,
                                                   108607.0,
                                                   174591.0,
                                                   209145.0,
                                                   318927.0,
                                                   233083.0],
                                     'numclusterpts': [1910253.0,
                                                       1721856.0,
                                                       1462453.0,
                                                       1319491.0,
                                                       874953.0,
                                                       514766.0],
                                     'numclusters': [599.0,
                                                     27.0,
                                                     13.0,
                                                     13.0,
                                                     8.0,
                                                     4.0],
                                     'numcore': [1867325.0,
                                                 1613187.0,
                                                 1287762.0,
                                                 1109405.0,
                                                 555715.0,
                                                 281683.0],
                                     'numgrids': [613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0],
                                     'numnoise': [139503.0,
                                                  327486.0,
                                                  586927.0,
                                                  730730.0,
                                                  1174638.0,
                                                  1534514.0],
                                     'numprocs': {72.0},
                                     'numpts': [2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0],
                                     'numpts_attr': {2049280.0},
                                     'rho': {0.01},
                                     'rounds': {3.0},
                                     'serialalgo': {'parallel'},
                                     'testcount': 6,
                                     'totaltime': [2.52562,
                                                   3.76948,
                                                   5.71068,
                                                   7.16733,
                                                   15.3989,
                                                   18.1734],
                                     'variable': 'minpts',
                                     'x': [10.0,
                                           100.0,
                                           500.0,
                                           1000.0,
                                           5000.0,
                                           10000.0]}},
 'numprocsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                      'assignbordertime': [0.00467992,
                                                           0.00345778,
                                                           0.00283694,
                                                           0.0022471,
                                                           0.00233102,
                                                           0.00398993],
                                      'assigngridtime': [0.513782,
                                                         0.293544,
                                                         0.184625,
                                                         0.158424,
                                                         0.1497,
                                                         0.15243],
                                      'buildcoreptquadtree': [-1,
                                                              -1,
                                                              -1,
                                                              -1,
                                                              -1,
                                                              -1],
                                      'buildgetnbrkdt': [0.000809908,
                                                         0.000739098,
                                                         0.000684023,
                                                         0.000683069,
                                                         0.000669003,
                                                         0.00125694],
                                      'clustercoretime': [0.56114,
                                                          0.537209,
                                                          0.428111,
                                                          0.383468,
                                                          0.367871,
                                                          0.440317],
                                      'config-id': '07-07-real2',
                                      'configuration': 'nd-approx/nd-exactbcp/nd-exactquadtree/nd-exactbcpbucketing: '
                                                       'after the kdtree '
                                                       'scanleft change, to '
                                                       'obtain a new result '
                                                       'for household dataset; '
                                                       'jemalloc for all, '
                                                       'bucketing only for '
                                                       'nd-exactquadtree, '
                                                       'array kdt for all, '
                                                       'array quadtree for any '
                                                       'config that involve a '
                                                       'quadtree, long '
                                                       'variable type for any '
                                                       'config that involve a '
                                                       'quadtree, double '
                                                       'datatype, commit: ',
                                      'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                      'dataset': '3D_GeoLife_24M.pbbs',
                                      'dim': {3.0},
                                      'dimname': '3D_GeoLife_',
                                      'eps': {40.0},
                                      'machine': 'aws-c5.18x',
                                      'markcoretime': [0.159937,
                                                       0.0836661,
                                                       0.0418119,
                                                       0.0300159,
                                                       0.0215521,
                                                       0.018616],
                                      'minpts': {100.0},
                                      'ndalgo': {'nd'},
                                      'numborder': [3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0],
                                      'numclusterpts': [24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0],
                                      'numclusters': [63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0],
                                      'numcore': [24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0],
                                      'numgrids': [9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0],
                                      'numnoise': [17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0],
                                      'numprocs': {4.0,
                                                   8.0,
                                                   16.0,
                                                   24.0,
                                                   36.0,
                                                   72.0},
                                      'numpts': [24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0],
                                      'numpts_attr': {24876978.0},
                                      'rho': {0.01},
                                      'rounds': {3.0},
                                      'serialalgo': {'parallel'},
                                      'testcount': 6,
                                      'totaltime': [1.24085,
                                                    0.919174,
                                                    0.658662,
                                                    0.57503,
                                                    0.542381,
                                                    0.616913],
                                      'variable': 'numprocs',
                                      'x': [4.0, 8.0, 16.0, 24.0, 36.0, 72.0]},
                   '7D_HouseHold_2M': {'algo': {'exact'},
                                       'assignbordertime': [0.896907,
                                                            0.485303,
                                                            0.270944,
                                                            0.18338,
                                                            0.134368,
                                                            0.130963],
                                       'assigngridtime': [0.232747,
                                                          0.117543,
                                                          0.0674858,
                                                          0.0477061,
                                                          0.0315769,
                                                          0.029834],
                                       'buildcoreptquadtree': [-1,
                                                               -1,
                                                               -1,
                                                               -1,
                                                               -1,
                                                               -1],
                                       'buildgetnbrkdt': [0.163122,
                                                          0.0986199,
                                                          0.0539191,
                                                          0.0421569,
                                                          0.030879,
                                                          0.0295811],
                                       'clustercoretime': [0.824867,
                                                           0.467608,
                                                           0.288285,
                                                           0.245162,
                                                           0.180428,
                                                           0.196477],
                                       'config-id': '07-07-real2',
                                       'configuration': 'nd-approx/nd-exactbcp/nd-exactquadtree/nd-exactbcpbucketing: '
                                                        'after the kdtree '
                                                        'scanleft change, to '
                                                        'obtain a new result '
                                                        'for household '
                                                        'dataset; jemalloc for '
                                                        'all, bucketing only '
                                                        'for nd-exactquadtree, '
                                                        'array kdt for all, '
                                                        'array quadtree for '
                                                        'any config that '
                                                        'involve a quadtree, '
                                                        'long variable type '
                                                        'for any config that '
                                                        'involve a quadtree, '
                                                        'double datatype, '
                                                        'commit: ',
                                       'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                       'dataset': '7D_HouseHold_2M.pbbs',
                                       'dim': {7.0},
                                       'dimname': '7D_HouseHold_',
                                       'eps': {2000.0},
                                       'machine': 'aws-c5.18x',
                                       'markcoretime': [24.4634,
                                                        12.5619,
                                                        6.53197,
                                                        4.70932,
                                                        3.51991,
                                                        3.36061],
                                       'minpts': {100.0},
                                       'ndalgo': {'nd'},
                                       'numborder': [108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0],
                                       'numclusterpts': [1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0],
                                       'numclusters': [27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0],
                                       'numcore': [1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0],
                                       'numgrids': [613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0],
                                       'numnoise': [327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0],
                                       'numprocs': {4.0,
                                                    8.0,
                                                    16.0,
                                                    24.0,
                                                    36.0,
                                                    72.0},
                                       'numpts': [2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0],
                                       'numpts_attr': {2049280.0},
                                       'rho': {0.01},
                                       'rounds': {3.0},
                                       'serialalgo': {'parallel'},
                                       'testcount': 6,
                                       'totaltime': [26.6648,
                                                     13.8116,
                                                     7.24564,
                                                     5.28593,
                                                     3.92355,
                                                     3.76948],
                                       'variable': 'numprocs',
                                       'x': [4.0,
                                             8.0,
                                             16.0,
                                             24.0,
                                             36.0,
                                             72.0]}},
 'numptsPlots': {}}