plotData = {'epsPlots': {'3D_GeoLife_24M': {'algo': {'approx'},
                                 'assignbordertime': [0.00511909,
                                                      0.00439095,
                                                      0.0042119,
                                                      0.00143313],
                                 'assigngridtime': [0.194202,
                                                    0.187501,
                                                    0.195481,
                                                    0.193591],
                                 'buildcoreptquadtree': [0.368475,
                                                         0.3425,
                                                         0.332407,
                                                         0.321274],
                                 'buildgetnbrkdt': [0.001791,
                                                    0.00132108,
                                                    0.000433922,
                                                    0.000359774],
                                 'clustercoretime': [0.0241358,
                                                     0.024179,
                                                     0.0217421,
                                                     0.0105979],
                                 'config-id': '07-04-real1-approx',
                                 'configuration': 'nd-approx-bcp: jemalloc, no '
                                                  'bucketing, array kdt, long '
                                                  'variable type, double '
                                                  'datatype, commit: ',
                                 'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                 'dataset': '3D_GeoLife_24M.pbbs',
                                 'dim': {3.0},
                                 'dimname': '3D_GeoLife_',
                                 'eps': {40.0, 80.0, 20.0, 160.0},
                                 'machine': 'aws-c5.18x',
                                 'markcoretime': [0.0627158,
                                                  0.022002,
                                                  0.08652,
                                                  0.00974107],
                                 'minpts': {100.0},
                                 'ndalgo': {'nd'},
                                 'numborder': [7391.0, 3791.0, 3572.0, 990.0],
                                 'numclusterpts': [24846295.0,
                                                   24859769.0,
                                                   24868067.0,
                                                   24873703.0],
                                 'numclusters': [91.0, 63.0, 56.0, 24.0],
                                 'numcore': [24838633.0,
                                             24855827.0,
                                             24864335.0,
                                             24872696.0],
                                 'numgrids': [22919.0, 9684.0, 3612.0, 1694.0],
                                 'numnoise': [30954.0, 17360.0, 9071.0, 3292.0],
                                 'numprocs': {72.0},
                                 'numpts': [24876978.0,
                                            24876978.0,
                                            24876978.0,
                                            24876978.0],
                                 'numpts_attr': {24876978.0},
                                 'rho': {0.01},
                                 'rounds': {3.0},
                                 'serialalgo': {'parallel'},
                                 'testcount': 4,
                                 'totaltime': [0.656873,
                                               0.582158,
                                               0.642561,
                                               0.53718],
                                 'variable': 'eps',
                                 'x': [20.0, 40.0, 80.0, 160.0]},
              '7D_HouseHold_2M': {'algo': {'approx'},
                                  'assignbordertime': [1.78814e-05,
                                                       7.00951e-05,
                                                       2.19345e-05,
                                                       8.01086e-05,
                                                       5.88894e-05,
                                                       7.08103e-05],
                                  'assigngridtime': [0.0237861,
                                                     0.023474,
                                                     0.023443,
                                                     0.0233328,
                                                     0.0236661,
                                                     0.024184],
                                  'buildcoreptquadtree': [0.0546079,
                                                          0.0411892,
                                                          0.056509,
                                                          0.057076,
                                                          0.0582581,
                                                          0.0617189],
                                  'buildgetnbrkdt': [0.000138998,
                                                     0.000144005,
                                                     5.6982e-05,
                                                     0.000129223,
                                                     0.000125885,
                                                     0.000133991],
                                  'clustercoretime': [0.000702143,
                                                      0.000702858,
                                                      0.000710011,
                                                      0.000736952,
                                                      0.000751972,
                                                      0.0008111],
                                  'config-id': '07-04-real1-approx',
                                  'configuration': 'nd-approx-bcp: jemalloc, '
                                                   'no bucketing, array kdt, '
                                                   'long variable type, double '
                                                   'datatype, commit: ',
                                  'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                  'dataset': '7D_HouseHold_2M.pbbs',
                                  'dim': {7.0},
                                  'dimname': '7D_HouseHold_',
                                  'eps': {1000.0,
                                          1400.0,
                                          1800.0,
                                          2200.0,
                                          2600.0,
                                          3000.0},
                                  'machine': 'aws-c5.18x',
                                  'markcoretime': [0.000597,
                                                   0.000647783,
                                                   0.00061512,
                                                   0.00066185,
                                                   0.00061202,
                                                   0.000627041],
                                  'minpts': {100.0},
                                  'ndalgo': {'nd'},
                                  'numborder': [1e-10,
                                                1e-10,
                                                1e-10,
                                                1e-10,
                                                1e-10,
                                                1e-10],
                                  'numclusterpts': [2049280.0,
                                                    2049280.0,
                                                    2049280.0,
                                                    2049280.0,
                                                    2049280.0,
                                                    2049280.0],
                                  'numclusters': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                                  'numcore': [2049280.0,
                                              2049280.0,
                                              2049280.0,
                                              2049280.0,
                                              2049280.0,
                                              2049280.0],
                                  'numgrids': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                                  'numnoise': [1e-10,
                                               1e-10,
                                               1e-10,
                                               1e-10,
                                               1e-10,
                                               1e-10],
                                  'numprocs': {72.0},
                                  'numpts': [2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0],
                                  'numpts_attr': {2049280.0},
                                  'rho': {0.01},
                                  'rounds': {3.0},
                                  'serialalgo': {'parallel'},
                                  'testcount': 6,
                                  'totaltime': [0.07988,
                                                0.0662539,
                                                0.081388,
                                                0.0820441,
                                                0.0835209,
                                                0.0875762],
                                  'variable': 'eps',
                                  'x': [1000.0,
                                        1400.0,
                                        1800.0,
                                        2200.0,
                                        2600.0,
                                        3000.0]}},
 'minptsPlots': {'3D_GeoLife_24M': {'algo': {'approx'},
                                    'assignbordertime': [0.00428104,
                                                         0.00439095,
                                                         0.00384879,
                                                         0.00907183,
                                                         0.103187,
                                                         0.193224],
                                    'assigngridtime': [0.193637,
                                                       0.187501,
                                                       0.186335,
                                                       0.186529,
                                                       0.27276,
                                                       0.18285],
                                    'buildcoreptquadtree': [0.353975,
                                                            0.3425,
                                                            0.348714,
                                                            0.345007,
                                                            0.295889,
                                                            0.311982],
                                    'buildgetnbrkdt': [0.00131392,
                                                       0.00132108,
                                                       0.00141096,
                                                       0.0013001,
                                                       0.00161886,
                                                       0.00183988],
                                    'clustercoretime': [0.0170639,
                                                        0.024179,
                                                        0.0186262,
                                                        0.0135651,
                                                        0.012984,
                                                        0.0147381],
                                    'config-id': '07-04-real1-approx',
                                    'configuration': 'nd-approx-bcp: jemalloc, '
                                                     'no bucketing, array kdt, '
                                                     'long variable type, '
                                                     'double datatype, '
                                                     'commit: ',
                                    'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                    'dataset': '3D_GeoLife_24M.pbbs',
                                    'dim': {3.0},
                                    'dimname': '3D_GeoLife_',
                                    'eps': {40.0},
                                    'machine': 'aws-c5.18x',
                                    'markcoretime': [0.0200391,
                                                     0.022002,
                                                     0.0511839,
                                                     0.127907,
                                                     0.899536,
                                                     2.40558],
                                    'minpts': {10.0,
                                               100.0,
                                               500.0,
                                               1000.0,
                                               5000.0,
                                               10000.0},
                                    'ndalgo': {'nd'},
                                    'numborder': [320.0,
                                                  3791.0,
                                                  8860.0,
                                                  17546.0,
                                                  100090.0,
                                                  91985.0],
                                    'numclusterpts': [24875629.0,
                                                      24859769.0,
                                                      24824591.0,
                                                      24795161.0,
                                                      24501634.0,
                                                      24141423.0],
                                    'numclusters': [84.0,
                                                    63.0,
                                                    26.0,
                                                    21.0,
                                                    19.0,
                                                    8.0],
                                    'numcore': [24875293.0,
                                                24855827.0,
                                                24815481.0,
                                                24776376.0,
                                                24400085.0,
                                                24049438.0],
                                    'numgrids': [9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0],
                                    'numnoise': [1365.0,
                                                 17360.0,
                                                 52637.0,
                                                 83056.0,
                                                 376803.0,
                                                 735555.0],
                                    'numprocs': {72.0},
                                    'numpts': [24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0],
                                    'numpts_attr': {24876978.0},
                                    'rho': {0.01},
                                    'rounds': {3.0},
                                    'serialalgo': {'parallel'},
                                    'testcount': 6,
                                    'totaltime': [0.590489,
                                                  0.582158,
                                                  0.610421,
                                                  0.683634,
                                                  1.58632,
                                                  3.11059],
                                    'variable': 'minpts',
                                    'x': [10.0,
                                          100.0,
                                          500.0,
                                          1000.0,
                                          5000.0,
                                          10000.0]},
                 '7D_HouseHold_2M': {'algo': {'approx'},
                                     'assignbordertime': [6.31809e-05,
                                                          1.5974e-05,
                                                          8.70228e-05,
                                                          7.31945e-05,
                                                          1.5974e-05,
                                                          1.69277e-05],
                                     'assigngridtime': [0.0227091,
                                                        0.0234342,
                                                        0.0231609,
                                                        0.0232961,
                                                        0.023108,
                                                        0.0241132],
                                     'buildcoreptquadtree': [0.062753,
                                                             0.062947,
                                                             0.0625548,
                                                             0.064636,
                                                             0.0636771,
                                                             0.062396],
                                     'buildgetnbrkdt': [0.000155926,
                                                        0.000130892,
                                                        0.000169992,
                                                        0.000145912,
                                                        3.91006e-05,
                                                        0.000124931],
                                     'clustercoretime': [0.000772953,
                                                         0.000721931,
                                                         0.000770092,
                                                         0.000720024,
                                                         0.000656843,
                                                         0.000686169],
                                     'config-id': '07-04-real1-approx',
                                     'configuration': 'nd-approx-bcp: '
                                                      'jemalloc, no bucketing, '
                                                      'array kdt, long '
                                                      'variable type, double '
                                                      'datatype, commit: ',
                                     'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                     'dataset': '7D_HouseHold_2M.pbbs',
                                     'dim': {7.0},
                                     'dimname': '7D_HouseHold_',
                                     'eps': {2000.0},
                                     'machine': 'aws-c5.18x',
                                     'markcoretime': [0.000632048,
                                                      0.000679016,
                                                      0.000622034,
                                                      0.000568867,
                                                      0.000541925,
                                                      0.000614882],
                                     'minpts': {10.0,
                                                100.0,
                                                500.0,
                                                1000.0,
                                                5000.0,
                                                10000.0},
                                     'ndalgo': {'nd'},
                                     'numborder': [1e-10,
                                                   1e-10,
                                                   1e-10,
                                                   1e-10,
                                                   1e-10,
                                                   1e-10],
                                     'numclusterpts': [2049280.0,
                                                       2049280.0,
                                                       2049280.0,
                                                       2049280.0,
                                                       2049280.0,
                                                       2049280.0],
                                     'numclusters': [1.0,
                                                     1.0,
                                                     1.0,
                                                     1.0,
                                                     1.0,
                                                     1.0],
                                     'numcore': [2049280.0,
                                                 2049280.0,
                                                 2049280.0,
                                                 2049280.0,
                                                 2049280.0,
                                                 2049280.0],
                                     'numgrids': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                                     'numnoise': [1e-10,
                                                  1e-10,
                                                  1e-10,
                                                  1e-10,
                                                  1e-10,
                                                  1e-10],
                                     'numprocs': {72.0},
                                     'numpts': [2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0],
                                     'numpts_attr': {2049280.0},
                                     'rho': {0.01},
                                     'rounds': {3.0},
                                     'serialalgo': {'parallel'},
                                     'testcount': 6,
                                     'totaltime': [0.087141,
                                                   0.087956,
                                                   0.0874131,
                                                   0.0894849,
                                                   0.0880659,
                                                   0.0879769],
                                     'variable': 'minpts',
                                     'x': [10.0,
                                           100.0,
                                           500.0,
                                           1000.0,
                                           5000.0,
                                           10000.0]}},
 'numprocsPlots': {'3D_GeoLife_24M': {'algo': {'approx'},
                                      'assignbordertime': [0.0100989,
                                                           0.00543213,
                                                           0.00376797,
                                                           0.00268197,
                                                           0.00280809,
                                                           0.00262785,
                                                           0.00439095],
                                      'assigngridtime': [1.82937,
                                                         0.642094,
                                                         0.351799,
                                                         0.20272,
                                                         0.326662,
                                                         0.206145,
                                                         0.187501],
                                      'buildcoreptquadtree': [7.58327,
                                                              2.8454,
                                                              1.47648,
                                                              0.830949,
                                                              0.585791,
                                                              0.464801,
                                                              0.3425],
                                      'buildgetnbrkdt': [0.000594854,
                                                         0.00101399,
                                                         0.000725031,
                                                         0.000718832,
                                                         0.000803947,
                                                         0.000821114,
                                                         0.00132108],
                                      'clustercoretime': [0.240059,
                                                          0.10132,
                                                          0.0402009,
                                                          0.0678511,
                                                          0.018075,
                                                          0.015548,
                                                          0.024179],
                                      'config-id': '07-04-real1-approx',
                                      'configuration': 'nd-approx-bcp: '
                                                       'jemalloc, no '
                                                       'bucketing, array kdt, '
                                                       'long variable type, '
                                                       'double datatype, '
                                                       'commit: ',
                                      'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                      'dataset': '3D_GeoLife_24M.pbbs',
                                      'dim': {3.0},
                                      'dimname': '3D_GeoLife_',
                                      'eps': {40.0},
                                      'machine': 'aws-c5.18x',
                                      'markcoretime': [0.611812,
                                                       0.166941,
                                                       0.0849841,
                                                       0.0433512,
                                                       0.0301518,
                                                       0.0221469,
                                                       0.022002],
                                      'minpts': {100.0},
                                      'ndalgo': {'nd'},
                                      'numborder': [3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0],
                                      'numclusterpts': [24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0],
                                      'numclusters': [63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0],
                                      'numcore': [24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0],
                                      'numgrids': [9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0],
                                      'numnoise': [17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0],
                                      'numprocs': {1.0,
                                                   4.0,
                                                   8.0,
                                                   16.0,
                                                   24.0,
                                                   36.0,
                                                   72.0},
                                      'numpts': [24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0],
                                      'numpts_attr': {24876978.0},
                                      'rho': {0.01},
                                      'rounds': {3.0},
                                      'serialalgo': {'parallel'},
                                      'testcount': 7,
                                      'totaltime': [10.2755,
                                                    3.7625,
                                                    1.95832,
                                                    1.14847,
                                                    0.964461,
                                                    0.712226,
                                                    0.582158],
                                      'variable': 'numprocs',
                                      'x': [1.0,
                                            4.0,
                                            8.0,
                                            16.0,
                                            24.0,
                                            36.0,
                                            72.0]},
                   '7D_HouseHold_2M': {'algo': {'approx'},
                                       'assignbordertime': [1.90735e-05,
                                                            1.5974e-05,
                                                            1.78814e-05,
                                                            1.5974e-05,
                                                            1.00136e-05,
                                                            8.82149e-06,
                                                            1.5974e-05],
                                       'assigngridtime': [0.142406,
                                                          0.0500829,
                                                          0.0318618,
                                                          0.024744,
                                                          0.022064,
                                                          0.0214479,
                                                          0.0234342],
                                       'buildcoreptquadtree': [0.300317,
                                                               0.109022,
                                                               0.075325,
                                                               0.0568011,
                                                               0.0513701,
                                                               0.0510149,
                                                               0.062947],
                                       'buildgetnbrkdt': [2.90871e-05,
                                                          3.09944e-05,
                                                          2.90871e-05,
                                                          3.40939e-05,
                                                          3.21865e-05,
                                                          2.90871e-05,
                                                          0.000130892],
                                       'clustercoretime': [0.00608897,
                                                           0.00222802,
                                                           0.00133514,
                                                           0.000840902,
                                                           0.000615835,
                                                           0.000626087,
                                                           0.000721931],
                                       'config-id': '07-04-real1-approx',
                                       'configuration': 'nd-approx-bcp: '
                                                        'jemalloc, no '
                                                        'bucketing, array kdt, '
                                                        'long variable type, '
                                                        'double datatype, '
                                                        'commit: ',
                                       'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                       'dataset': '7D_HouseHold_2M.pbbs',
                                       'dim': {7.0},
                                       'dimname': '7D_HouseHold_',
                                       'eps': {2000.0},
                                       'machine': 'aws-c5.18x',
                                       'markcoretime': [0.00706601,
                                                        0.00155401,
                                                        0.000912905,
                                                        0.000634909,
                                                        0.000594854,
                                                        0.000498056,
                                                        0.000679016],
                                       'minpts': {100.0},
                                       'ndalgo': {'nd'},
                                       'numborder': [1e-10,
                                                     1e-10,
                                                     1e-10,
                                                     1e-10,
                                                     1e-10,
                                                     1e-10,
                                                     1e-10],
                                       'numclusterpts': [2049280.0,
                                                         2049280.0,
                                                         2049280.0,
                                                         2049280.0,
                                                         2049280.0,
                                                         2049280.0,
                                                         2049280.0],
                                       'numclusters': [1.0,
                                                       1.0,
                                                       1.0,
                                                       1.0,
                                                       1.0,
                                                       1.0,
                                                       1.0],
                                       'numcore': [2049280.0,
                                                   2049280.0,
                                                   2049280.0,
                                                   2049280.0,
                                                   2049280.0,
                                                   2049280.0,
                                                   2049280.0],
                                       'numgrids': [1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0],
                                       'numnoise': [1e-10,
                                                    1e-10,
                                                    1e-10,
                                                    1e-10,
                                                    1e-10,
                                                    1e-10,
                                                    1e-10],
                                       'numprocs': {1.0,
                                                    4.0,
                                                    8.0,
                                                    16.0,
                                                    24.0,
                                                    36.0,
                                                    72.0},
                                       'numpts': [2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0],
                                       'numpts_attr': {2049280.0},
                                       'rho': {0.01},
                                       'rounds': {3.0},
                                       'serialalgo': {'parallel'},
                                       'testcount': 7,
                                       'totaltime': [0.455947,
                                                     0.162959,
                                                     0.109508,
                                                     0.083096,
                                                     0.074708,
                                                     0.0736451,
                                                     0.087956],
                                       'variable': 'numprocs',
                                       'x': [1.0,
                                             4.0,
                                             8.0,
                                             16.0,
                                             24.0,
                                             36.0,
                                             72.0]}},
 'numptsPlots': {}}