plotData = {'epsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                 'assignbordertime': [0.00340199,
                                                      0.00420094,
                                                      0.00699615,
                                                      0.00121903],
                                 'assigngridtime': [0.196761,
                                                    0.197373,
                                                    0.291578,
                                                    0.333684],
                                 'buildcoreptquadtree': [-1, -1, -1, -1],
                                 'buildgetnbrkdt': [0.00185704,
                                                    0.00123787,
                                                    0.000491858,
                                                    0.00040102],
                                 'clustercoretime': [0.421921,
                                                     0.673423,
                                                     56.0547,
                                                     0.741086],
                                 'config-id': '07-04-real1-exactbcp',
                                 'configuration': 'nd-exact-bcp: jemalloc, no '
                                                  'bucketing, array kdt, long '
                                                  'variable type, double '
                                                  'datatype, commit: '
                                                  'd5bc6b16a36be719eb8671b4ab10f51bdf1276f1',
                                 'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                 'dataset': '3D_GeoLife_24M.pbbs',
                                 'dim': {3.0},
                                 'dimname': '3D_GeoLife_',
                                 'eps': {40.0, 80.0, 20.0, 160.0},
                                 'machine': 'aws-c5.18x',
                                 'markcoretime': [0.0666668,
                                                  0.0215089,
                                                  0.085223,
                                                  0.036839],
                                 'minpts': {100.0},
                                 'ndalgo': {'nd'},
                                 'numborder': [7391.0, 3791.0, 3572.0, 990.0],
                                 'numclusterpts': [24846295.0,
                                                   24859769.0,
                                                   24868067.0,
                                                   24873703.0],
                                 'numclusters': [91.0, 63.0, 56.0, 24.0],
                                 'numcore': [24838633.0,
                                             24855827.0,
                                             24864335.0,
                                             24872696.0],
                                 'numgrids': [22919.0, 9684.0, 3612.0, 1694.0],
                                 'numnoise': [30954.0, 17360.0, 9071.0, 3292.0],
                                 'numprocs': {72.0},
                                 'numpts': [24876978.0,
                                            24876978.0,
                                            24876978.0,
                                            24876978.0],
                                 'numpts_attr': {24876978.0},
                                 'rho': {0.01},
                                 'rounds': {3.0},
                                 'serialalgo': {'parallel'},
                                 'testcount': 4,
                                 'totaltime': [0.690987,
                                               0.8996,
                                               56.4396,
                                               1.11365],
                                 'variable': 'eps',
                                 'x': [20.0, 40.0, 80.0, 160.0]},
              '7D_HouseHold_2M': {'algo': {'exact'},
                                  'assignbordertime': [4.69685e-05,
                                                       1.09673e-05,
                                                       4.50611e-05,
                                                       5.50747e-05,
                                                       1.40667e-05,
                                                       4.50611e-05],
                                  'assigngridtime': [0.022191,
                                                     0.0225499,
                                                     0.0225909,
                                                     0.0223179,
                                                     0.0222201,
                                                     0.022593],
                                  'buildcoreptquadtree': [-1,
                                                          -1,
                                                          -1,
                                                          -1,
                                                          -1,
                                                          -1],
                                  'buildgetnbrkdt': [0.000138998,
                                                     8.82149e-05,
                                                     0.000177145,
                                                     0.00014019,
                                                     4.1008e-05,
                                                     0.000117064],
                                  'clustercoretime': [0.000648022,
                                                      0.000580072,
                                                      0.000618935,
                                                      0.000616789,
                                                      0.000566006,
                                                      0.000686884],
                                  'config-id': '07-04-real1-exactbcp',
                                  'configuration': 'nd-exact-bcp: jemalloc, no '
                                                   'bucketing, array kdt, long '
                                                   'variable type, double '
                                                   'datatype, commit: '
                                                   'd5bc6b16a36be719eb8671b4ab10f51bdf1276f1',
                                  'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                  'dataset': '7D_HouseHold_2M.pbbs',
                                  'dim': {7.0},
                                  'dimname': '7D_HouseHold_',
                                  'eps': {1000.0,
                                          1400.0,
                                          1800.0,
                                          2200.0,
                                          2600.0,
                                          3000.0},
                                  'machine': 'aws-c5.18x',
                                  'markcoretime': [0.000582933,
                                                   0.000600815,
                                                   0.00057292,
                                                   0.000638008,
                                                   0.000552893,
                                                   0.000626087],
                                  'minpts': {100.0},
                                  'ndalgo': {'nd'},
                                  'numborder': [1e-10,
                                                1e-10,
                                                1e-10,
                                                1e-10,
                                                1e-10,
                                                1e-10],
                                  'numclusterpts': [2049280.0,
                                                    2049280.0,
                                                    2049280.0,
                                                    2049280.0,
                                                    2049280.0,
                                                    2049280.0],
                                  'numclusters': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                                  'numcore': [2049280.0,
                                              2049280.0,
                                              2049280.0,
                                              2049280.0,
                                              2049280.0,
                                              2049280.0],
                                  'numgrids': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                                  'numnoise': [1e-10,
                                               1e-10,
                                               1e-10,
                                               1e-10,
                                               1e-10,
                                               1e-10],
                                  'numprocs': {72.0},
                                  'numpts': [2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0],
                                  'numpts_attr': {2049280.0},
                                  'rho': {0.01},
                                  'rounds': {3.0},
                                  'serialalgo': {'parallel'},
                                  'testcount': 6,
                                  'totaltime': [0.0236559,
                                                0.0238509,
                                                0.0240519,
                                                0.023793,
                                                0.0234179,
                                                0.0241141],
                                  'variable': 'eps',
                                  'x': [1000.0,
                                        1400.0,
                                        1800.0,
                                        2200.0,
                                        2600.0,
                                        3000.0]}},
 'minptsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                    'assignbordertime': [0.00383496,
                                                         0.00420094,
                                                         0.00435996,
                                                         0.00919318,
                                                         0.103809,
                                                         0.194711],
                                    'assigngridtime': [0.20042,
                                                       0.197373,
                                                       0.190079,
                                                       0.190939,
                                                       0.14506,
                                                       0.292149],
                                    'buildcoreptquadtree': [-1,
                                                            -1,
                                                            -1,
                                                            -1,
                                                            -1,
                                                            -1],
                                    'buildgetnbrkdt': [0.00131011,
                                                       0.00123787,
                                                       0.00136209,
                                                       0.00129795,
                                                       0.00676799,
                                                       0.002563],
                                    'clustercoretime': [0.55392,
                                                        0.673423,
                                                        0.505484,
                                                        0.571977,
                                                        0.629234,
                                                        0.501935],
                                    'config-id': '07-04-real1-exactbcp',
                                    'configuration': 'nd-exact-bcp: jemalloc, '
                                                     'no bucketing, array kdt, '
                                                     'long variable type, '
                                                     'double datatype, commit: '
                                                     'd5bc6b16a36be719eb8671b4ab10f51bdf1276f1',
                                    'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                    'dataset': '3D_GeoLife_24M.pbbs',
                                    'dim': {3.0},
                                    'dimname': '3D_GeoLife_',
                                    'eps': {40.0},
                                    'machine': 'aws-c5.18x',
                                    'markcoretime': [0.0203068,
                                                     0.0215089,
                                                     0.0517049,
                                                     0.127775,
                                                     0.902515,
                                                     2.38331],
                                    'minpts': {10.0,
                                               100.0,
                                               500.0,
                                               1000.0,
                                               5000.0,
                                               10000.0},
                                    'ndalgo': {'nd'},
                                    'numborder': [320.0,
                                                  3791.0,
                                                  8860.0,
                                                  17546.0,
                                                  100090.0,
                                                  91985.0],
                                    'numclusterpts': [24875629.0,
                                                      24859769.0,
                                                      24824591.0,
                                                      24795161.0,
                                                      24501634.0,
                                                      24141423.0],
                                    'numclusters': [84.0,
                                                    63.0,
                                                    26.0,
                                                    21.0,
                                                    19.0,
                                                    8.0],
                                    'numcore': [24875293.0,
                                                24855827.0,
                                                24815481.0,
                                                24776376.0,
                                                24400085.0,
                                                24049438.0],
                                    'numgrids': [9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0],
                                    'numnoise': [1365.0,
                                                 17360.0,
                                                 52637.0,
                                                 83056.0,
                                                 376803.0,
                                                 735555.0],
                                    'numprocs': {72.0},
                                    'numpts': [24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0],
                                    'numpts_attr': {24876978.0},
                                    'rho': {0.01},
                                    'rounds': {3.0},
                                    'serialalgo': {'parallel'},
                                    'testcount': 6,
                                    'totaltime': [0.783001,
                                                  0.8996,
                                                  0.753337,
                                                  0.901797,
                                                  1.7878,
                                                  3.37503],
                                    'variable': 'minpts',
                                    'x': [10.0,
                                          100.0,
                                          500.0,
                                          1000.0,
                                          5000.0,
                                          10000.0]},
                 '7D_HouseHold_2M': {'algo': {'exact'},
                                     'assignbordertime': [1.4782e-05,
                                                          5.38826e-05,
                                                          5.00679e-05,
                                                          1.40667e-05,
                                                          1.09673e-05,
                                                          9.77516e-06],
                                     'assigngridtime': [0.022362,
                                                        0.0232651,
                                                        0.022325,
                                                        0.022156,
                                                        0.0228701,
                                                        0.0199611],
                                     'buildcoreptquadtree': [-1,
                                                             -1,
                                                             -1,
                                                             -1,
                                                             -1,
                                                             -1],
                                     'buildgetnbrkdt': [0.000102043,
                                                        0.000156879,
                                                        0.000142097,
                                                        0.000124931,
                                                        6.79493e-05,
                                                        3.19481e-05],
                                     'clustercoretime': [0.000572205,
                                                         0.000688076,
                                                         0.000648022,
                                                         0.000677109,
                                                         0.000560999,
                                                         0.000579119],
                                     'config-id': '07-04-real1-exactbcp',
                                     'configuration': 'nd-exact-bcp: jemalloc, '
                                                      'no bucketing, array '
                                                      'kdt, long variable '
                                                      'type, double datatype, '
                                                      'commit: '
                                                      'd5bc6b16a36be719eb8671b4ab10f51bdf1276f1',
                                     'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                     'dataset': '7D_HouseHold_2M.pbbs',
                                     'dim': {7.0},
                                     'dimname': '7D_HouseHold_',
                                     'eps': {2000.0},
                                     'machine': 'aws-c5.18x',
                                     'markcoretime': [0.000589848,
                                                      0.000689983,
                                                      0.000613928,
                                                      0.000588894,
                                                      0.000601053,
                                                      0.000560999],
                                     'minpts': {10.0,
                                                100.0,
                                                500.0,
                                                1000.0,
                                                5000.0,
                                                10000.0},
                                     'ndalgo': {'nd'},
                                     'numborder': [1e-10,
                                                   1e-10,
                                                   1e-10,
                                                   1e-10,
                                                   1e-10,
                                                   1e-10],
                                     'numclusterpts': [2049280.0,
                                                       2049280.0,
                                                       2049280.0,
                                                       2049280.0,
                                                       2049280.0,
                                                       2049280.0],
                                     'numclusters': [1.0,
                                                     1.0,
                                                     1.0,
                                                     1.0,
                                                     1.0,
                                                     1.0],
                                     'numcore': [2049280.0,
                                                 2049280.0,
                                                 2049280.0,
                                                 2049280.0,
                                                 2049280.0,
                                                 2049280.0],
                                     'numgrids': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                                     'numnoise': [1e-10,
                                                  1e-10,
                                                  1e-10,
                                                  1e-10,
                                                  1e-10,
                                                  1e-10],
                                     'numprocs': {72.0},
                                     'numpts': [2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0],
                                     'numpts_attr': {2049280.0},
                                     'rho': {0.01},
                                     'rounds': {3.0},
                                     'serialalgo': {'parallel'},
                                     'testcount': 6,
                                     'totaltime': [0.023664,
                                                   0.0248981,
                                                   0.0238039,
                                                   0.0235829,
                                                   0.024133,
                                                   0.0211661],
                                     'variable': 'minpts',
                                     'x': [10.0,
                                           100.0,
                                           500.0,
                                           1000.0,
                                           5000.0,
                                           10000.0]}},
 'numprocsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                      'assignbordertime': [0.0101039,
                                                           0.00503898,
                                                           0.004004,
                                                           0.00443506,
                                                           0.0143859,
                                                           0.023869,
                                                           0.00420094],
                                      'assigngridtime': [1.68895,
                                                         0.573282,
                                                         0.337961,
                                                         0.186022,
                                                         0.235672,
                                                         0.211845,
                                                         0.197373],
                                      'buildcoreptquadtree': [-1,
                                                              -1,
                                                              -1,
                                                              -1,
                                                              -1,
                                                              -1,
                                                              -1],
                                      'buildgetnbrkdt': [0.000602961,
                                                         0.000847101,
                                                         0.00090003,
                                                         0.00163698,
                                                         0.000967979,
                                                         0.000789165,
                                                         0.00123787],
                                      'clustercoretime': [1.24052,
                                                          0.876732,
                                                          0.481893,
                                                          0.324027,
                                                          0.328563,
                                                          0.545332,
                                                          0.673423],
                                      'config-id': '07-04-real1-exactbcp',
                                      'configuration': 'nd-exact-bcp: '
                                                       'jemalloc, no '
                                                       'bucketing, array kdt, '
                                                       'long variable type, '
                                                       'double datatype, '
                                                       'commit: '
                                                       'd5bc6b16a36be719eb8671b4ab10f51bdf1276f1',
                                      'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                      'dataset': '3D_GeoLife_24M.pbbs',
                                      'dim': {3.0},
                                      'dimname': '3D_GeoLife_',
                                      'eps': {40.0},
                                      'machine': 'aws-c5.18x',
                                      'markcoretime': [0.665847,
                                                       0.164353,
                                                       0.0835459,
                                                       0.0428729,
                                                       0.033304,
                                                       0.0246019,
                                                       0.0215089],
                                      'minpts': {100.0},
                                      'ndalgo': {'nd'},
                                      'numborder': [3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0],
                                      'numclusterpts': [24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0],
                                      'numclusters': [63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0],
                                      'numcore': [24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0],
                                      'numgrids': [9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0],
                                      'numnoise': [17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0],
                                      'numprocs': {1.0,
                                                   4.0,
                                                   8.0,
                                                   16.0,
                                                   24.0,
                                                   36.0,
                                                   72.0},
                                      'numpts': [24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0],
                                      'numpts_attr': {24876978.0},
                                      'rho': {0.01},
                                      'rounds': {3.0},
                                      'serialalgo': {'parallel'},
                                      'testcount': 7,
                                      'totaltime': [3.60637,
                                                    1.62097,
                                                    0.908721,
                                                    0.559352,
                                                    0.613248,
                                                    0.806633,
                                                    0.8996],
                                      'variable': 'numprocs',
                                      'x': [1.0,
                                            4.0,
                                            8.0,
                                            16.0,
                                            24.0,
                                            36.0,
                                            72.0]},
                   '7D_HouseHold_2M': {'algo': {'exact'},
                                       'assignbordertime': [1.50204e-05,
                                                            1.19209e-05,
                                                            1.50204e-05,
                                                            8.82149e-06,
                                                            5.96046e-06,
                                                            1.19209e-05,
                                                            5.38826e-05],
                                       'assigngridtime': [0.128506,
                                                          0.0460432,
                                                          0.0292799,
                                                          0.0223889,
                                                          0.021827,
                                                          0.0230501,
                                                          0.0232651],
                                       'buildcoreptquadtree': [-1,
                                                               -1,
                                                               -1,
                                                               -1,
                                                               -1,
                                                               -1,
                                                               -1],
                                       'buildgetnbrkdt': [2.88486e-05,
                                                          2.5034e-05,
                                                          2.69413e-05,
                                                          2.5034e-05,
                                                          2.81334e-05,
                                                          4.07696e-05,
                                                          0.000156879],
                                       'clustercoretime': [0.00510597,
                                                           0.00197101,
                                                           0.00104403,
                                                           0.00067997,
                                                           0.000612974,
                                                           0.00059104,
                                                           0.000688076],
                                       'config-id': '07-04-real1-exactbcp',
                                       'configuration': 'nd-exact-bcp: '
                                                        'jemalloc, no '
                                                        'bucketing, array kdt, '
                                                        'long variable type, '
                                                        'double datatype, '
                                                        'commit: '
                                                        'd5bc6b16a36be719eb8671b4ab10f51bdf1276f1',
                                       'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                       'dataset': '7D_HouseHold_2M.pbbs',
                                       'dim': {7.0},
                                       'dimname': '7D_HouseHold_',
                                       'eps': {2000.0},
                                       'machine': 'aws-c5.18x',
                                       'markcoretime': [0.00475502,
                                                        0.0014329,
                                                        0.00081706,
                                                        0.000580072,
                                                        0.000505924,
                                                        0.000554085,
                                                        0.000689983],
                                       'minpts': {100.0},
                                       'ndalgo': {'nd'},
                                       'numborder': [1e-10,
                                                     1e-10,
                                                     1e-10,
                                                     1e-10,
                                                     1e-10,
                                                     1e-10,
                                                     1e-10],
                                       'numclusterpts': [2049280.0,
                                                         2049280.0,
                                                         2049280.0,
                                                         2049280.0,
                                                         2049280.0,
                                                         2049280.0,
                                                         2049280.0],
                                       'numclusters': [1.0,
                                                       1.0,
                                                       1.0,
                                                       1.0,
                                                       1.0,
                                                       1.0,
                                                       1.0],
                                       'numcore': [2049280.0,
                                                   2049280.0,
                                                   2049280.0,
                                                   2049280.0,
                                                   2049280.0,
                                                   2049280.0,
                                                   2049280.0],
                                       'numgrids': [1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0],
                                       'numnoise': [1e-10,
                                                    1e-10,
                                                    1e-10,
                                                    1e-10,
                                                    1e-10,
                                                    1e-10,
                                                    1e-10],
                                       'numprocs': {1.0,
                                                    4.0,
                                                    8.0,
                                                    16.0,
                                                    24.0,
                                                    36.0,
                                                    72.0},
                                       'numpts': [2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0],
                                       'numpts_attr': {2049280.0},
                                       'rho': {0.01},
                                       'rounds': {3.0},
                                       'serialalgo': {'parallel'},
                                       'testcount': 7,
                                       'totaltime': [0.138444,
                                                     0.0495009,
                                                     0.031203,
                                                     0.023701,
                                                     0.022999,
                                                     0.0242701,
                                                     0.0248981],
                                       'variable': 'numprocs',
                                       'x': [1.0,
                                             4.0,
                                             8.0,
                                             16.0,
                                             24.0,
                                             36.0,
                                             72.0]}},
 'numptsPlots': {}}