plotData = {'epsPlots': {'3D_GeoLife_24M': {'algo': {'approx'},
                                 'assignbordertime': [0.0519001,
                                                      0.00469303,
                                                      0.004529,
                                                      0.00166702],
                                 'assigngridtime': [0.204167,
                                                    0.193061,
                                                    0.197975,
                                                    0.195843],
                                 'buildcoreptquadtree': [0.426742,
                                                         0.364032,
                                                         0.347039,
                                                         0.323191],
                                 'buildgetnbrkdt': [0.00263,
                                                    0.00176811,
                                                    0.00100684,
                                                    0.000861168],
                                 'clustercoretime': [0.0385568,
                                                     0.01454,
                                                     0.01262,
                                                     0.0107651],
                                 'config-id': '0221-synt4',
                                 'configuration': 'approx-bucketing-real: kdt '
                                                  'scans bothsides, jemalloc, '
                                                  'bucketing on, array kdt, '
                                                  'long variable type in '
                                                  'general, double datatype',
                                 'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                 'dataset': '3D_GeoLife_24M.pbbs',
                                 'dim': {3.0},
                                 'dimname': '3D_GeoLife_',
                                 'eps': {40.0, 80.0, 20.0, 160.0},
                                 'machine': 'aws-c5.18x',
                                 'markcoretime': [0.0220909,
                                                  0.01179,
                                                  0.091701,
                                                  0.00718498],
                                 'minpts': {100.0},
                                 'ndalgo': {'nd'},
                                 'numborder': [7391.0, 3791.0, 3572.0, 990.0],
                                 'numclusterpts': [24846295.0,
                                                   24859769.0,
                                                   24868067.0,
                                                   24873703.0],
                                 'numclusters': [91.0, 63.0, 56.0, 24.0],
                                 'numcore': [24838633.0,
                                             24855827.0,
                                             24864335.0,
                                             24872696.0],
                                 'numgrids': [22919.0, 9684.0, 3612.0, 1694.0],
                                 'numnoise': [30954.0, 17360.0, 9071.0, 3292.0],
                                 'numprocs': {72.0},
                                 'numpts': [24876978.0,
                                            24876978.0,
                                            24876978.0,
                                            24876978.0],
                                 'numpts_attr': {24876978.0},
                                 'rho': {0.01},
                                 'rounds': {3.0},
                                 'serialalgo': {'parallel'},
                                 'testcount': 4,
                                 'totaltime': [0.746836,
                                               0.590118,
                                               0.655019,
                                               0.539698],
                                 'variable': 'eps',
                                 'x': [20.0, 40.0, 80.0, 160.0]},
              '7D_HouseHold_2M': {'algo': {'approx'},
                                  'assignbordertime': [0.155223,
                                                       0.097352,
                                                       0.154594,
                                                       0.241242,
                                                       0.279807,
                                                       0.221241],
                                  'assigngridtime': [0.0459189,
                                                     0.0345769,
                                                     0.042078,
                                                     0.0376818,
                                                     0.036119,
                                                     0.0331941],
                                  'buildcoreptquadtree': [0.0510519,
                                                          0.053241,
                                                          0.0656371,
                                                          0.0661221,
                                                          0.0701549,
                                                          0.0700731],
                                  'buildgetnbrkdt': [0.173249,
                                                     0.0885661,
                                                     0.057426,
                                                     0.0338831,
                                                     0.027288,
                                                     0.017905],
                                  'clustercoretime': [0.2359,
                                                      0.194448,
                                                      0.217179,
                                                      0.50599,
                                                      1.07449,
                                                      3.53019],
                                  'config-id': '0221-synt4',
                                  'configuration': 'approx-bucketing-real: kdt '
                                                   'scans bothsides, jemalloc, '
                                                   'bucketing on, array kdt, '
                                                   'long variable type in '
                                                   'general, double datatype',
                                  'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                  'dataset': '7D_HouseHold_2M.pbbs',
                                  'dim': {7.0},
                                  'dimname': '7D_HouseHold_',
                                  'eps': {1000.0,
                                          1400.0,
                                          1800.0,
                                          2200.0,
                                          2600.0,
                                          3000.0},
                                  'machine': 'aws-c5.18x',
                                  'markcoretime': [2.74451,
                                                   2.84701,
                                                   4.27983,
                                                   9.07415,
                                                   9.98281,
                                                   11.111],
                                  'minpts': {100.0},
                                  'ndalgo': {'nd'},
                                  'numborder': [123077.0,
                                                148926.0,
                                                121447.0,
                                                97189.0,
                                                76854.0,
                                                64485.0],
                                  'numclusterpts': [1220205.0,
                                                    1507976.0,
                                                    1668837.0,
                                                    1760132.0,
                                                    1815454.0,
                                                    1855854.0],
                                  'numclusters': [55.0,
                                                  30.0,
                                                  27.0,
                                                  30.0,
                                                  38.0,
                                                  48.0],
                                  'numcore': [1096868.0,
                                              1358900.0,
                                              1547291.0,
                                              1662856.0,
                                              1738555.0,
                                              1791293.0],
                                  'numgrids': [987740.0,
                                               796144.0,
                                               664053.0,
                                               570752.0,
                                               498785.0,
                                               442979.0],
                                  'numnoise': [829335.0,
                                               541454.0,
                                               380542.0,
                                               289235.0,
                                               233871.0,
                                               193502.0],
                                  'numprocs': {72.0},
                                  'numpts': [2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0],
                                  'numpts_attr': {2049280.0},
                                  'rho': {0.01},
                                  'rounds': {3.0},
                                  'serialalgo': {'parallel'},
                                  'testcount': 6,
                                  'totaltime': [3.42364,
                                                3.33742,
                                                4.84326,
                                                10.0473,
                                                11.5592,
                                                15.0265],
                                  'variable': 'eps',
                                  'x': [1000.0,
                                        1400.0,
                                        1800.0,
                                        2200.0,
                                        2600.0,
                                        3000.0]}},
 'minptsPlots': {'3D_GeoLife_24M': {'algo': {'approx'},
                                    'assignbordertime': [0.00440693,
                                                         0.00469303,
                                                         0.00402093,
                                                         0.0265179,
                                                         0.111098,
                                                         0.204749],
                                    'assigngridtime': [0.200533,
                                                       0.193061,
                                                       0.193735,
                                                       0.198,
                                                       0.205678,
                                                       0.210555],
                                    'buildcoreptquadtree': [0.367522,
                                                            0.364032,
                                                            0.357816,
                                                            0.38169,
                                                            0.300345,
                                                            0.322009],
                                    'buildgetnbrkdt': [0.00182009,
                                                       0.00176811,
                                                       0.00177383,
                                                       0.00171113,
                                                       0.005723,
                                                       0.00170112],
                                    'clustercoretime': [0.0141549,
                                                        0.01454,
                                                        0.0148149,
                                                        0.0286241,
                                                        0.0143781,
                                                        0.023246],
                                    'config-id': '0221-synt4',
                                    'configuration': 'approx-bucketing-real: '
                                                     'kdt scans bothsides, '
                                                     'jemalloc, bucketing on, '
                                                     'array kdt, long variable '
                                                     'type in general, double '
                                                     'datatype',
                                    'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                    'dataset': '3D_GeoLife_24M.pbbs',
                                    'dim': {3.0},
                                    'dimname': '3D_GeoLife_',
                                    'eps': {40.0},
                                    'machine': 'aws-c5.18x',
                                    'markcoretime': [0.0134971,
                                                     0.01179,
                                                     0.042239,
                                                     0.121121,
                                                     0.884483,
                                                     2.52927],
                                    'minpts': {10.0,
                                               100.0,
                                               500.0,
                                               1000.0,
                                               5000.0,
                                               10000.0},
                                    'ndalgo': {'nd'},
                                    'numborder': [320.0,
                                                  3791.0,
                                                  8860.0,
                                                  17546.0,
                                                  100090.0,
                                                  91985.0],
                                    'numclusterpts': [24875629.0,
                                                      24859769.0,
                                                      24824591.0,
                                                      24795161.0,
                                                      24501634.0,
                                                      24141423.0],
                                    'numclusters': [84.0,
                                                    63.0,
                                                    26.0,
                                                    21.0,
                                                    19.0,
                                                    8.0],
                                    'numcore': [24875293.0,
                                                24855827.0,
                                                24815481.0,
                                                24776376.0,
                                                24400085.0,
                                                24049438.0],
                                    'numgrids': [9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0],
                                    'numnoise': [1365.0,
                                                 17360.0,
                                                 52637.0,
                                                 83056.0,
                                                 376803.0,
                                                 735555.0],
                                    'numprocs': {72.0},
                                    'numpts': [24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0],
                                    'numpts_attr': {24876978.0},
                                    'rho': {0.01},
                                    'rounds': {3.0},
                                    'serialalgo': {'parallel'},
                                    'testcount': 6,
                                    'totaltime': [0.602229,
                                                  0.590118,
                                                  0.614684,
                                                  0.757942,
                                                  1.52209,
                                                  3.29194],
                                    'variable': 'minpts',
                                    'x': [10.0,
                                          100.0,
                                          500.0,
                                          1000.0,
                                          5000.0,
                                          10000.0]},
                 '7D_HouseHold_2M': {'algo': {'approx'},
                                     'assignbordertime': [0.0223711,
                                                          0.140101,
                                                          0.490258,
                                                          0.912253,
                                                          2.6559,
                                                          2.23915],
                                     'assigngridtime': [0.041044,
                                                        0.0458329,
                                                        0.0406032,
                                                        0.0351019,
                                                        0.042218,
                                                        0.0371192],
                                     'buildcoreptquadtree': [0.0812221,
                                                             0.0674059,
                                                             0.0440929,
                                                             0.0352499,
                                                             0.0226848,
                                                             0.017803],
                                     'buildgetnbrkdt': [0.0399339,
                                                        0.0489552,
                                                        0.0432029,
                                                        0.0414481,
                                                        0.056113,
                                                        0.04721],
                                     'clustercoretime': [0.429976,
                                                         0.190197,
                                                         0.0979221,
                                                         0.0602961,
                                                         0.0218091,
                                                         0.021482],
                                     'config-id': '0221-synt4',
                                     'configuration': 'approx-bucketing-real: '
                                                      'kdt scans bothsides, '
                                                      'jemalloc, bucketing on, '
                                                      'array kdt, long '
                                                      'variable type in '
                                                      'general, double '
                                                      'datatype',
                                     'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                     'dataset': '7D_HouseHold_2M.pbbs',
                                     'dim': {7.0},
                                     'dimname': '7D_HouseHold_',
                                     'eps': {2000.0},
                                     'machine': 'aws-c5.18x',
                                     'markcoretime': [2.83853,
                                                      4.60943,
                                                      6.53214,
                                                      7.70838,
                                                      14.0489,
                                                      17.4207],
                                     'minpts': {10.0,
                                                100.0,
                                                500.0,
                                                1000.0,
                                                5000.0,
                                                10000.0},
                                     'ndalgo': {'nd'},
                                     'numborder': [42452.0,
                                                   108607.0,
                                                   174591.0,
                                                   209145.0,
                                                   318927.0,
                                                   233083.0],
                                     'numclusterpts': [1910237.0,
                                                       1721856.0,
                                                       1462453.0,
                                                       1318872.0,
                                                       874953.0,
                                                       514766.0],
                                     'numclusters': [595.0,
                                                     27.0,
                                                     13.0,
                                                     12.0,
                                                     8.0,
                                                     4.0],
                                     'numcore': [1867325.0,
                                                 1613187.0,
                                                 1287762.0,
                                                 1109405.0,
                                                 555715.0,
                                                 281683.0],
                                     'numgrids': [613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0,
                                                  613546.0],
                                     'numnoise': [139503.0,
                                                  327486.0,
                                                  586927.0,
                                                  730730.0,
                                                  1174638.0,
                                                  1534514.0],
                                     'numprocs': {72.0},
                                     'numpts': [2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0],
                                     'numpts_attr': {2049280.0},
                                     'rho': {0.01},
                                     'rounds': {3.0},
                                     'serialalgo': {'parallel'},
                                     'testcount': 6,
                                     'totaltime': [3.47449,
                                                   5.13145,
                                                   7.32259,
                                                   8.86215,
                                                   16.8805,
                                                   19.8698],
                                     'variable': 'minpts',
                                     'x': [10.0,
                                           100.0,
                                           500.0,
                                           1000.0,
                                           5000.0,
                                           10000.0]}},
 'numprocsPlots': {'3D_GeoLife_24M': {'algo': {'approx'},
                                      'assignbordertime': [0.010529,
                                                           0.00440383,
                                                           0.0036962,
                                                           0.00328517,
                                                           0.00279498,
                                                           0.0183558,
                                                           0.00469303],
                                      'assigngridtime': [1.87483,
                                                         0.568764,
                                                         0.314301,
                                                         0.19559,
                                                         0.209615,
                                                         0.218456,
                                                         0.193061],
                                      'buildcoreptquadtree': [7.77422,
                                                              2.66349,
                                                              1.51229,
                                                              0.872666,
                                                              0.71319,
                                                              0.502053,
                                                              0.364032],
                                      'buildgetnbrkdt': [0.00250506,
                                                         0.00144601,
                                                         0.00119901,
                                                         0.00203991,
                                                         0.00215602,
                                                         0.00124192,
                                                         0.00176811],
                                      'clustercoretime': [0.163063,
                                                          0.0730271,
                                                          0.033134,
                                                          0.024097,
                                                          0.0610731,
                                                          0.0217202,
                                                          0.01454],
                                      'config-id': '0221-synt4',
                                      'configuration': 'approx-bucketing-real: '
                                                       'kdt scans bothsides, '
                                                       'jemalloc, bucketing '
                                                       'on, array kdt, long '
                                                       'variable type in '
                                                       'general, double '
                                                       'datatype',
                                      'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                      'dataset': '3D_GeoLife_24M.pbbs',
                                      'dim': {3.0},
                                      'dimname': '3D_GeoLife_',
                                      'eps': {40.0},
                                      'machine': 'aws-c5.18x',
                                      'markcoretime': [0.267674,
                                                       0.0752349,
                                                       0.0391901,
                                                       0.021347,
                                                       0.017699,
                                                       0.0124271,
                                                       0.01179],
                                      'minpts': {100.0},
                                      'ndalgo': {'nd'},
                                      'numborder': [3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0,
                                                    3791.0],
                                      'numclusterpts': [24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0],
                                      'numclusters': [63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0],
                                      'numcore': [24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0,
                                                  24855827.0],
                                      'numgrids': [9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0],
                                      'numnoise': [17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0],
                                      'numprocs': {1.0,
                                                   4.0,
                                                   8.0,
                                                   16.0,
                                                   24.0,
                                                   36.0,
                                                   72.0},
                                      'numpts': [24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0],
                                      'numpts_attr': {24876978.0},
                                      'rho': {0.01},
                                      'rounds': {3.0},
                                      'serialalgo': {'parallel'},
                                      'testcount': 7,
                                      'totaltime': [10.0932,
                                                    3.38684,
                                                    1.90424,
                                                    1.11932,
                                                    1.00679,
                                                    0.774576,
                                                    0.590118],
                                      'variable': 'numprocs',
                                      'x': [1.0,
                                            4.0,
                                            8.0,
                                            16.0,
                                            24.0,
                                            36.0,
                                            72.0]},
                   '7D_HouseHold_2M': {'algo': {'approx'},
                                       'assignbordertime': [3.52179,
                                                            1.01471,
                                                            0.565867,
                                                            0.299032,
                                                            0.20428,
                                                            0.155487,
                                                            0.140101],
                                       'assigngridtime': [0.9354,
                                                          0.274415,
                                                          0.143767,
                                                          0.0772219,
                                                          0.0538399,
                                                          0.0479591,
                                                          0.0458329],
                                       'buildcoreptquadtree': [0.820786,
                                                               0.267458,
                                                               0.141444,
                                                               0.094358,
                                                               0.0852609,
                                                               0.082521,
                                                               0.0674059],
                                       'buildgetnbrkdt': [0.806325,
                                                          0.211042,
                                                          0.117088,
                                                          0.0687981,
                                                          0.0480921,
                                                          0.0426879,
                                                          0.0489552],
                                       'clustercoretime': [2.97801,
                                                           1.06653,
                                                           0.629569,
                                                           0.333237,
                                                           0.304297,
                                                           0.230963,
                                                           0.190197],
                                       'config-id': '0221-synt4',
                                       'configuration': 'approx-bucketing-real: '
                                                        'kdt scans bothsides, '
                                                        'jemalloc, bucketing '
                                                        'on, array kdt, long '
                                                        'variable type in '
                                                        'general, double '
                                                        'datatype',
                                       'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                       'dataset': '7D_HouseHold_2M.pbbs',
                                       'dim': {7.0},
                                       'dimname': '7D_HouseHold_',
                                       'eps': {2000.0},
                                       'machine': 'aws-c5.18x',
                                       'markcoretime': [109.357,
                                                        27.7432,
                                                        14.3919,
                                                        7.7999,
                                                        5.81447,
                                                        4.38789,
                                                        4.60943],
                                       'minpts': {100.0},
                                       'ndalgo': {'nd'},
                                       'numborder': [108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0,
                                                     108607.0],
                                       'numclusterpts': [1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0,
                                                         1721856.0],
                                       'numclusters': [27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0,
                                                       27.0],
                                       'numcore': [1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0,
                                                   1613187.0],
                                       'numgrids': [613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0,
                                                    613546.0],
                                       'numnoise': [327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0,
                                                    327486.0],
                                       'numprocs': {1.0,
                                                    4.0,
                                                    8.0,
                                                    16.0,
                                                    24.0,
                                                    36.0,
                                                    72.0},
                                       'numpts': [2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0],
                                       'numpts_attr': {2049280.0},
                                       'rho': {0.01},
                                       'rounds': {3.0},
                                       'serialalgo': {'parallel'},
                                       'testcount': 7,
                                       'totaltime': [118.492,
                                                     30.6756,
                                                     16.0818,
                                                     8.7378,
                                                     6.56229,
                                                     4.98343,
                                                     5.13145],
                                       'variable': 'numprocs',
                                       'x': [1.0,
                                             4.0,
                                             8.0,
                                             16.0,
                                             24.0,
                                             36.0,
                                             72.0]}},
 'numptsPlots': {},
 'rhoPlots': {'3D_GeoLife_24M': {'algo': {'approx'},
                                 'assignbordertime': [0.00469303],
                                 'assigngridtime': [0.193061],
                                 'buildcoreptquadtree': [0.364032],
                                 'buildgetnbrkdt': [0.00176811],
                                 'clustercoretime': [0.01454],
                                 'config-id': '0221-synt4',
                                 'configuration': 'approx-bucketing-real: kdt '
                                                  'scans bothsides, jemalloc, '
                                                  'bucketing on, array kdt, '
                                                  'long variable type in '
                                                  'general, double datatype',
                                 'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                 'dataset': '3D_GeoLife_24M.pbbs',
                                 'dim': {3.0},
                                 'dimname': '3D_GeoLife_',
                                 'eps': {40.0},
                                 'machine': 'aws-c5.18x',
                                 'markcoretime': [0.01179],
                                 'minpts': {100.0},
                                 'ndalgo': {'nd'},
                                 'numborder': [3791.0],
                                 'numclusterpts': [24859769.0],
                                 'numclusters': [63.0],
                                 'numcore': [24855827.0],
                                 'numgrids': [9684.0],
                                 'numnoise': [17360.0],
                                 'numprocs': {72.0},
                                 'numpts': [24876978.0],
                                 'numpts_attr': {24876978.0},
                                 'rho': {0.01},
                                 'rounds': {3.0},
                                 'serialalgo': {'parallel'},
                                 'testcount': 1,
                                 'totaltime': [0.590118],
                                 'variable': 'rho',
                                 'x': [0.01]},
              '7D_HouseHold_2M': {'algo': {'approx'},
                                  'assignbordertime': [0.140101],
                                  'assigngridtime': [0.0458329],
                                  'buildcoreptquadtree': [0.0674059],
                                  'buildgetnbrkdt': [0.0489552],
                                  'clustercoretime': [0.190197],
                                  'config-id': '0221-synt4',
                                  'configuration': 'approx-bucketing-real: kdt '
                                                   'scans bothsides, jemalloc, '
                                                   'bucketing on, array kdt, '
                                                   'long variable type in '
                                                   'general, double datatype',
                                  'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                  'dataset': '7D_HouseHold_2M.pbbs',
                                  'dim': {7.0},
                                  'dimname': '7D_HouseHold_',
                                  'eps': {2000.0},
                                  'machine': 'aws-c5.18x',
                                  'markcoretime': [4.60943],
                                  'minpts': {100.0},
                                  'ndalgo': {'nd'},
                                  'numborder': [108607.0],
                                  'numclusterpts': [1721856.0],
                                  'numclusters': [27.0],
                                  'numcore': [1613187.0],
                                  'numgrids': [613546.0],
                                  'numnoise': [327486.0],
                                  'numprocs': {72.0},
                                  'numpts': [2049280.0],
                                  'numpts_attr': {2049280.0},
                                  'rho': {0.01},
                                  'rounds': {3.0},
                                  'serialalgo': {'parallel'},
                                  'testcount': 1,
                                  'totaltime': [5.13145],
                                  'variable': 'rho',
                                  'x': [0.01]}}}