plotData = {'epsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                 'assignbordertime': [0.00304389,
                                                      0.00465584,
                                                      0.00435591,
                                                      0.00152397],
                                 'assigngridtime': [0.137207,
                                                    0.141422,
                                                    0.134323,
                                                    0.145644],
                                 'buildcoreptquadtree': [0.29457,
                                                         0.293192,
                                                         0.272957,
                                                         0.268753],
                                 'buildgetnbrkdt': [0.00160694,
                                                    0.00109696,
                                                    0.000478029,
                                                    0.000398874],
                                 'clustercoretime': [0.124774,
                                                     0.0244081,
                                                     0.153949,
                                                     0.154289],
                                 'config-id': '07-04-real1-quadtree',
                                 'configuration': 'nd-exact-quadtreer: '
                                                  'jemalloc, no bucketing, '
                                                  'array kdt, array quadtree, '
                                                  'long variable type, double '
                                                  'datatype, commit: ',
                                 'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                 'dataset': '3D_GeoLife_24M.pbbs',
                                 'dim': {3.0},
                                 'dimname': '3D_GeoLife_',
                                 'eps': {40.0, 80.0, 20.0, 160.0},
                                 'machine': 'aws-c5.18x',
                                 'markcoretime': [0.538872,
                                                  0.470362,
                                                  0.420852,
                                                  0.281906],
                                 'minpts': {100.0},
                                 'ndalgo': {'nd'},
                                 'numborder': [7391.0, 3792.0, 3572.0, 990.0],
                                 'numclusterpts': [24846295.0,
                                                   24859769.0,
                                                   24868067.0,
                                                   24873703.0],
                                 'numclusters': [91.0, 63.0, 56.0, 24.0],
                                 'numcore': [24838633.0,
                                             24855826.0,
                                             24864335.0,
                                             24872696.0],
                                 'numgrids': [22919.0, 9684.0, 3612.0, 1694.0],
                                 'numnoise': [30954.0, 17360.0, 9071.0, 3292.0],
                                 'numprocs': {72.0},
                                 'numpts': [24876978.0,
                                            24876978.0,
                                            24876978.0,
                                            24876978.0],
                                 'numpts_attr': {24876978.0},
                                 'rho': {0.01},
                                 'rounds': {3.0},
                                 'serialalgo': {'parallel'},
                                 'testcount': 4,
                                 'totaltime': [1.10053,
                                               0.935409,
                                               0.987247,
                                               0.852835],
                                 'variable': 'eps',
                                 'x': [20.0, 40.0, 80.0, 160.0]},
              '7D_HouseHold_2M': {'algo': {'exact'},
                                  'assignbordertime': [1.5974e-05,
                                                       7.60555e-05,
                                                       6.38962e-05,
                                                       7.10487e-05,
                                                       5.60284e-05,
                                                       1.4782e-05],
                                  'assigngridtime': [0.0216749,
                                                     0.0218649,
                                                     0.0215271,
                                                     0.0218279,
                                                     0.0216188,
                                                     0.0214429],
                                  'buildcoreptquadtree': [0.0515718,
                                                          0.0421529,
                                                          0.0544202,
                                                          0.05582,
                                                          0.0548751,
                                                          0.058557],
                                  'buildgetnbrkdt': [3.69549e-05,
                                                     4.69685e-05,
                                                     0.000128984,
                                                     2.90871e-05,
                                                     0.000101089,
                                                     0.000144005],
                                  'clustercoretime': [0.000671148,
                                                      0.000678062,
                                                      0.000803947,
                                                      0.000643969,
                                                      0.000742912,
                                                      0.000674009],
                                  'config-id': '07-04-real1-quadtree',
                                  'configuration': 'nd-exact-quadtreer: '
                                                   'jemalloc, no bucketing, '
                                                   'array kdt, array quadtree, '
                                                   'long variable type, double '
                                                   'datatype, commit: ',
                                  'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                  'dataset': '7D_HouseHold_2M.pbbs',
                                  'dim': {7.0},
                                  'dimname': '7D_HouseHold_',
                                  'eps': {1000.0,
                                          1400.0,
                                          1800.0,
                                          2200.0,
                                          2600.0,
                                          3000.0},
                                  'machine': 'aws-c5.18x',
                                  'markcoretime': [0.0524902,
                                                   0.0380242,
                                                   0.0547109,
                                                   0.055563,
                                                   0.0542989,
                                                   0.0589051],
                                  'minpts': {100.0},
                                  'ndalgo': {'nd'},
                                  'numborder': [1e-10,
                                                1e-10,
                                                1e-10,
                                                1e-10,
                                                1e-10,
                                                1e-10],
                                  'numclusterpts': [2049280.0,
                                                    2049280.0,
                                                    2049280.0,
                                                    2049280.0,
                                                    2049280.0,
                                                    2049280.0],
                                  'numclusters': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                                  'numcore': [2049280.0,
                                              2049280.0,
                                              2049280.0,
                                              2049280.0,
                                              2049280.0,
                                              2049280.0],
                                  'numgrids': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                                  'numnoise': [1e-10,
                                               1e-10,
                                               1e-10,
                                               1e-10,
                                               1e-10,
                                               1e-10],
                                  'numprocs': {72.0},
                                  'numpts': [2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0,
                                             2049280.0],
                                  'numpts_attr': {2049280.0},
                                  'rho': {0.01},
                                  'rounds': {3.0},
                                  'serialalgo': {'parallel'},
                                  'testcount': 6,
                                  'totaltime': [0.126487,
                                                0.102872,
                                                0.131703,
                                                0.134,
                                                0.13174,
                                                0.139777],
                                  'variable': 'eps',
                                  'x': [1000.0,
                                        1400.0,
                                        1800.0,
                                        2200.0,
                                        2600.0,
                                        3000.0]}},
 'minptsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                    'assignbordertime': [0.00368309,
                                                         0.00465584,
                                                         0.00401497,
                                                         0.00903296,
                                                         0.104802,
                                                         0.1955],
                                    'assigngridtime': [0.148436,
                                                       0.141422,
                                                       0.137824,
                                                       0.137752,
                                                       0.138351,
                                                       0.141686],
                                    'buildcoreptquadtree': [0.282392,
                                                            0.293192,
                                                            0.286934,
                                                            0.286803,
                                                            0.318193,
                                                            0.320327],
                                    'buildgetnbrkdt': [0.00121498,
                                                       0.00109696,
                                                       0.00116205,
                                                       0.00119781,
                                                       0.00118685,
                                                       0.00125813],
                                    'clustercoretime': [0.0282919,
                                                        0.0244081,
                                                        0.099978,
                                                        0.07651,
                                                        0.0781231,
                                                        0.0238469],
                                    'config-id': '07-04-real1-quadtree',
                                    'configuration': 'nd-exact-quadtreer: '
                                                     'jemalloc, no bucketing, '
                                                     'array kdt, array '
                                                     'quadtree, long variable '
                                                     'type, double datatype, '
                                                     'commit: ',
                                    'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                    'dataset': '3D_GeoLife_24M.pbbs',
                                    'dim': {3.0},
                                    'dimname': '3D_GeoLife_',
                                    'eps': {40.0},
                                    'machine': 'aws-c5.18x',
                                    'markcoretime': [0.458514,
                                                     0.470362,
                                                     0.487724,
                                                     0.494931,
                                                     0.646118,
                                                     0.727517],
                                    'minpts': {10.0,
                                               100.0,
                                               500.0,
                                               1000.0,
                                               5000.0,
                                               10000.0},
                                    'ndalgo': {'nd'},
                                    'numborder': [320.0,
                                                  3792.0,
                                                  8875.0,
                                                  17552.0,
                                                  100174.0,
                                                  91834.0],
                                    'numclusterpts': [24875629.0,
                                                      24859769.0,
                                                      24824591.0,
                                                      24795161.0,
                                                      24501620.0,
                                                      24141105.0],
                                    'numclusters': [84.0,
                                                    63.0,
                                                    26.0,
                                                    21.0,
                                                    19.0,
                                                    8.0],
                                    'numcore': [24875293.0,
                                                24855826.0,
                                                24815466.0,
                                                24776370.0,
                                                24399987.0,
                                                24049271.0],
                                    'numgrids': [9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0,
                                                 9684.0],
                                    'numnoise': [1365.0,
                                                 17360.0,
                                                 52637.0,
                                                 83056.0,
                                                 376817.0,
                                                 735873.0],
                                    'numprocs': {72.0},
                                    'numpts': [24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0,
                                               24876978.0],
                                    'numpts_attr': {24876978.0},
                                    'rho': {0.01},
                                    'rounds': {3.0},
                                    'serialalgo': {'parallel'},
                                    'testcount': 6,
                                    'totaltime': [0.92273,
                                                  0.935409,
                                                  1.01781,
                                                  1.00656,
                                                  1.28717,
                                                  1.41053],
                                    'variable': 'minpts',
                                    'x': [10.0,
                                          100.0,
                                          500.0,
                                          1000.0,
                                          5000.0,
                                          10000.0]},
                 '7D_HouseHold_2M': {'algo': {'exact'},
                                     'assignbordertime': [6.19888e-05,
                                                          5.31673e-05,
                                                          6.50883e-05,
                                                          1.78814e-05,
                                                          6.48499e-05,
                                                          6.19888e-05],
                                     'assigngridtime': [0.021874,
                                                        0.0215909,
                                                        0.0219719,
                                                        0.0221281,
                                                        0.0222142,
                                                        0.0229521],
                                     'buildcoreptquadtree': [0.060199,
                                                             0.0611691,
                                                             0.0603032,
                                                             0.060714,
                                                             0.062098,
                                                             0.061229],
                                     'buildgetnbrkdt': [0.000109196,
                                                        0.00010705,
                                                        5.19753e-05,
                                                        0.000146151,
                                                        3.91006e-05,
                                                        0.000139952],
                                     'clustercoretime': [0.000795126,
                                                         0.000764847,
                                                         0.000708818,
                                                         0.000694036,
                                                         0.00078702,
                                                         0.000827074],
                                     'config-id': '07-04-real1-quadtree',
                                     'configuration': 'nd-exact-quadtreer: '
                                                      'jemalloc, no bucketing, '
                                                      'array kdt, array '
                                                      'quadtree, long variable '
                                                      'type, double datatype, '
                                                      'commit: ',
                                     'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                     'dataset': '7D_HouseHold_2M.pbbs',
                                     'dim': {7.0},
                                     'dimname': '7D_HouseHold_',
                                     'eps': {2000.0},
                                     'machine': 'aws-c5.18x',
                                     'markcoretime': [0.0608728,
                                                      0.0610008,
                                                      0.061265,
                                                      0.0612638,
                                                      0.0624979,
                                                      0.060415],
                                     'minpts': {10.0,
                                                100.0,
                                                500.0,
                                                1000.0,
                                                5000.0,
                                                10000.0},
                                     'ndalgo': {'nd'},
                                     'numborder': [1e-10,
                                                   1e-10,
                                                   1e-10,
                                                   1e-10,
                                                   1e-10,
                                                   1e-10],
                                     'numclusterpts': [2049280.0,
                                                       2049280.0,
                                                       2049280.0,
                                                       2049280.0,
                                                       2049280.0,
                                                       2049280.0],
                                     'numclusters': [1.0,
                                                     1.0,
                                                     1.0,
                                                     1.0,
                                                     1.0,
                                                     1.0],
                                     'numcore': [2049280.0,
                                                 2049280.0,
                                                 2049280.0,
                                                 2049280.0,
                                                 2049280.0,
                                                 2049280.0],
                                     'numgrids': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                                     'numnoise': [1e-10,
                                                  1e-10,
                                                  1e-10,
                                                  1e-10,
                                                  1e-10,
                                                  1e-10],
                                     'numprocs': {72.0},
                                     'numpts': [2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0,
                                                2049280.0],
                                     'numpts_attr': {2049280.0},
                                     'rho': {0.01},
                                     'rounds': {3.0},
                                     'serialalgo': {'parallel'},
                                     'testcount': 6,
                                     'totaltime': [0.143967,
                                                   0.144741,
                                                   0.144418,
                                                   0.144994,
                                                   0.147732,
                                                   0.145674],
                                     'variable': 'minpts',
                                     'x': [10.0,
                                           100.0,
                                           500.0,
                                           1000.0,
                                           5000.0,
                                           10000.0]}},
 'numprocsPlots': {'3D_GeoLife_24M': {'algo': {'exact'},
                                      'assignbordertime': [0.0103381,
                                                           0.00528717,
                                                           0.00397491,
                                                           0.00383902,
                                                           0.00247908,
                                                           0.00261903,
                                                           0.00465584],
                                      'assigngridtime': [1.67167,
                                                         0.571185,
                                                         0.317971,
                                                         0.173888,
                                                         0.150384,
                                                         0.143965,
                                                         0.141422],
                                      'buildcoreptquadtree': [7.49222,
                                                              2.61551,
                                                              1.44157,
                                                              0.841572,
                                                              0.62924,
                                                              0.406774,
                                                              0.293192],
                                      'buildgetnbrkdt': [0.000614882,
                                                         0.000757933,
                                                         0.000772953,
                                                         0.000756979,
                                                         0.000710011,
                                                         0.00072813,
                                                         0.00109696],
                                      'clustercoretime': [0.264481,
                                                          0.113911,
                                                          0.050209,
                                                          0.033895,
                                                          0.024184,
                                                          0.0287929,
                                                          0.0244081],
                                      'config-id': '07-04-real1-quadtree',
                                      'configuration': 'nd-exact-quadtreer: '
                                                       'jemalloc, no '
                                                       'bucketing, array kdt, '
                                                       'array quadtree, long '
                                                       'variable type, double '
                                                       'datatype, commit: ',
                                      'datafile': {'../../../datasets//3D_GeoLife_24M.pbbs'},
                                      'dataset': '3D_GeoLife_24M.pbbs',
                                      'dim': {3.0},
                                      'dimname': '3D_GeoLife_',
                                      'eps': {40.0},
                                      'machine': 'aws-c5.18x',
                                      'markcoretime': [7.92693,
                                                       2.89588,
                                                       1.44561,
                                                       0.966308,
                                                       0.715717,
                                                       0.536379,
                                                       0.470362],
                                      'minpts': {100.0},
                                      'ndalgo': {'nd'},
                                      'numborder': [3792.0,
                                                    3792.0,
                                                    3792.0,
                                                    3792.0,
                                                    3792.0,
                                                    3792.0,
                                                    3792.0],
                                      'numclusterpts': [24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0,
                                                        24859769.0],
                                      'numclusters': [63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0,
                                                      63.0],
                                      'numcore': [24855826.0,
                                                  24855826.0,
                                                  24855826.0,
                                                  24855826.0,
                                                  24855826.0,
                                                  24855826.0,
                                                  24855826.0],
                                      'numgrids': [9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0,
                                                   9684.0],
                                      'numnoise': [17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0,
                                                   17360.0],
                                      'numprocs': {1.0,
                                                   4.0,
                                                   8.0,
                                                   16.0,
                                                   24.0,
                                                   36.0,
                                                   72.0},
                                      'numpts': [24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0,
                                                 24876978.0],
                                      'numpts_attr': {24876978.0},
                                      'rho': {0.01},
                                      'rounds': {3.0},
                                      'serialalgo': {'parallel'},
                                      'testcount': 7,
                                      'totaltime': [17.3667,
                                                    6.20302,
                                                    3.26046,
                                                    2.02049,
                                                    1.52293,
                                                    1.11947,
                                                    0.935409],
                                      'variable': 'numprocs',
                                      'x': [1.0,
                                            4.0,
                                            8.0,
                                            16.0,
                                            24.0,
                                            36.0,
                                            72.0]},
                   '7D_HouseHold_2M': {'algo': {'exact'},
                                       'assignbordertime': [2.00272e-05,
                                                            2.09808e-05,
                                                            1.28746e-05,
                                                            1.09673e-05,
                                                            1.09673e-05,
                                                            1.00136e-05,
                                                            5.31673e-05],
                                       'assigngridtime': [0.130474,
                                                          0.0489521,
                                                          0.0314329,
                                                          0.022557,
                                                          0.021095,
                                                          0.0195711,
                                                          0.0215909],
                                       'buildcoreptquadtree': [0.296163,
                                                               0.113756,
                                                               0.070904,
                                                               0.053093,
                                                               0.0490031,
                                                               0.047353,
                                                               0.0611691],
                                       'buildgetnbrkdt': [3.19481e-05,
                                                          2.69413e-05,
                                                          2.71797e-05,
                                                          3.19481e-05,
                                                          4.1008e-05,
                                                          2.69413e-05,
                                                          0.00010705],
                                       'clustercoretime': [0.00604606,
                                                           0.00222397,
                                                           0.00130916,
                                                           0.000787973,
                                                           0.000653028,
                                                           0.000627995,
                                                           0.000764847],
                                       'config-id': '07-04-real1-quadtree',
                                       'configuration': 'nd-exact-quadtreer: '
                                                        'jemalloc, no '
                                                        'bucketing, array kdt, '
                                                        'array quadtree, long '
                                                        'variable type, double '
                                                        'datatype, commit: ',
                                       'datafile': {'../../../datasets//7D_HouseHold_2M.pbbs'},
                                       'dataset': '7D_HouseHold_2M.pbbs',
                                       'dim': {7.0},
                                       'dimname': '7D_HouseHold_',
                                       'eps': {2000.0},
                                       'machine': 'aws-c5.18x',
                                       'markcoretime': [0.291952,
                                                        0.110047,
                                                        0.0698798,
                                                        0.0545571,
                                                        0.0497229,
                                                        0.048418,
                                                        0.0610008],
                                       'minpts': {100.0},
                                       'ndalgo': {'nd'},
                                       'numborder': [1e-10,
                                                     1e-10,
                                                     1e-10,
                                                     1e-10,
                                                     1e-10,
                                                     1e-10,
                                                     1e-10],
                                       'numclusterpts': [2049280.0,
                                                         2049280.0,
                                                         2049280.0,
                                                         2049280.0,
                                                         2049280.0,
                                                         2049280.0,
                                                         2049280.0],
                                       'numclusters': [1.0,
                                                       1.0,
                                                       1.0,
                                                       1.0,
                                                       1.0,
                                                       1.0,
                                                       1.0],
                                       'numcore': [2049280.0,
                                                   2049280.0,
                                                   2049280.0,
                                                   2049280.0,
                                                   2049280.0,
                                                   2049280.0,
                                                   2049280.0],
                                       'numgrids': [1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0,
                                                    1.0],
                                       'numnoise': [1e-10,
                                                    1e-10,
                                                    1e-10,
                                                    1e-10,
                                                    1e-10,
                                                    1e-10,
                                                    1e-10],
                                       'numprocs': {1.0,
                                                    4.0,
                                                    8.0,
                                                    16.0,
                                                    24.0,
                                                    36.0,
                                                    72.0},
                                       'numpts': [2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0,
                                                  2049280.0],
                                       'numpts_attr': {2049280.0},
                                       'rho': {0.01},
                                       'rounds': {3.0},
                                       'serialalgo': {'parallel'},
                                       'testcount': 7,
                                       'totaltime': [0.724709,
                                                     0.275053,
                                                     0.173587,
                                                     0.131066,
                                                     0.120551,
                                                     0.116032,
                                                     0.144741],
                                       'variable': 'numprocs',
                                       'x': [1.0,
                                             4.0,
                                             8.0,
                                             16.0,
                                             24.0,
                                             36.0,
                                             72.0]}},
 'numptsPlots': {}}